### ISSUE TITLE
knn for high dimension sparse vectors?

### ISSUE THREAD

**Issue by hiyijian** [spotify/annoy#115]
for high dimension, i mean size of vector larger than 3000
for sparse, i mean vector with none zero less than 1%
is annoy a good choice for this kind of knn task? if answer is no,  what can we do?

**Comment by erikbern** [comment]
It might work, but what probably works much better is to do dimensionality
reduction before you put the data in Annoy.

For instance Spotify typically runs some latent factor model to get he
number of dimensions down to 40-100 and then uses Annoy to find similar
items.
