### ISSUE TITLE
Does windows support now?

### ISSUE THREAD

**Issue by cadobe** [spotify/annoy#130]
I am working on a win10 desktop, encountering the same issue that C:\Users\v-xusha\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe' failed with exit status 2.

**Comment by erikbern** [comment]
sorry not sure what's going on. i don't have access to a windows machine. maybe you can help me out by trouble shooting this and see if you can find out what the issue is?

**Comment by pommedeterresautee** [comment]
this may help https://github.com/spotify/annoy/issues/97

**Comment by pommedeterresautee** [comment]
for what it worth, no way to install Annoy on Python 3.5 (mingw is not yet ready and VS 2015 is missing a header)

**Comment by birolkuyumcu** [comment]
for windows 10 64 bit
python 2.7.x 64 bit - Anaconda distribution -
TDM-GCC 64
download source code
'python setup.py install'
![annoysetup](https://cloud.githubusercontent.com/assets/8981828/16524912/a95a2796-3fb2-11e6-806b-f1f60b436f1c.jpg)
works

**Comment by erikbern** [comment]
nice!

**Comment by a1k0n** [comment]
This might have been the fopen mode "wb" fix that went in a little while
back.. when did you last update pypi @erikbern?

**Comment by birolkuyumcu** [comment]
last pypi not working 
https://github.com/spotify/annoy/issues/160

**Comment by erikbern** [comment]
if you can help me fix the pypi version i'd be grateful!

**Comment by birolkuyumcu** [comment]
how can help you ?

**Comment by erikbern** [comment]
figure out what the issue is and suggest a solution :)

**Comment by a1k0n** [comment]
Erik I think you just need to upload the latest version to pypi. Or does
that happen automatically somehow?

**Comment by birolkuyumcu** [comment]
for windows version you must be  use a mingw compiler 
but between version of compiler Binary incompatibility exist
http://mingw.5.n7.nabble.com/MinGW-GCC-4-7-0-released-td21925.html

> Binary incompatibility notice!
> ------------------------------
> The C and C++ ABI have changed, which means in general **you can't link
> together binaries compiled with this version of the compiler and any
> previous version.**

so simply re-build it

**Comment by erikbern** [comment]
i can upload latest version but don't know if anything window specific changed. but will do

**Comment by tjrileywisc** [comment]
Doesn't work for me unfortunately (on Windows 7).  I just cloned the repo and tried to build with gcc included in TDM-GCC-64 (gcc is version 5.1). I get this when trying to compile (below are arguments sent to gcc):

undefined reference to '__imp_Py_InitModule4'

**Comment by birolkuyumcu** [comment]
http://stackoverflow.com/questions/2842469/python-undefined-reference-to-imp-py-initmodule4

**Comment by birolkuyumcu** [comment]
try this egg file 
[annoy-1.8.0-py2.7-win-amd64.zip](https://github.com/spotify/annoy/files/360601/annoy-1.8.0-py2.7-win-amd64.zip)

**Comment by tjrileywisc** [comment]
@birolkuyumcu Awesome, I was able to get gcc to build a working annoy and the .egg worked as well.

To get this to build on Windows, I added [build] compiler=mingw32 to the config.cfg file in the repo and '-D=MS_WIN64' in extra_compile_args.

**Comment by tjrileywisc** [comment]
Though now (for me at least) python has a tendency to crash at the end of a session where annoy has been used.

**Comment by erikbern** [comment]
i pushed a new version (1.8.1) to pypi

not sure what went into it :)

**Comment by bnbwn** [comment]
another windows user trying to get this to work... I think I am so close.
I have read **all** the previous issues related to getting annoy compiled and properly loaded on windows.

python 2.7 x64 using miniconda on Win10
downloaded the gcc / c++ complier      using    mingw-w64-install.exe
extract to and save in C:/mingw-w64
add path to bin in PATH
downloaded annoy from github
extract and save into C:/annoy
C:\annoy>python setup.py build --compiler mingw32
C:\annoy>python setup.py install

after many hours... victory.    _I brute forced through every permutation of available compilers and build flags..._

at least for a moment....

![so close](https://cloud.githubusercontent.com/assets/3788107/25723070/2d0d4314-30dc-11e7-86c4-c746dce3ebd8.jpeg)

at this point I am unsure as it seems to be built correctly, and loaded properly, yet still isn't found. the .pyd is the newly created .dll.   python, then help(), then modules does show annoy as an option.

if  @cadobe, @sergeyf, @thirdwing, @birolkuyumcu @tjrileywisc have any ideas, I'm all ears... and thanks again @erikbern 

![image](https://cloud.githubusercontent.com/assets/3788107/25723559/20f4384c-30de-11e7-875c-8fa2c434a830.png)

**Comment by tjrileywisc** [comment]
Maybe have a look at this Largevis repo, they take annoy a step further and
do dimensionally reduction.

They made a few changes to the annoy code to allow compiling on Windows.
I'm not sure if it makes an importable module for annoy in Python though.

https://github.com/lferry007/LargeVis

**Comment by tjrileywisc** [comment]
@bnbwn 

If you're still interested in this, you might want to try my fork that is compiling correctly on Windows (at least in python 3.5/3.6).

https://github.com/tjrileywisc/annoy

**Comment by bnbwn** [comment]
Yes, Thank you!

-ben

**Comment by quole** [comment]
I thought I should mention I wrote a C#/.NET port of the Java (read-only) Annoy as part of my fork of Word2vec.Tools. It appears to work correctly but much too slowly, so it might not be useful in its current state. 

I haven't done performance tests, but it appears that running gensim within a Docker image is much faster, with or without using an index, meaning an indexed (less accurate) lookup is generally far slower than even an unindexed lookup in gensim. Partly this may be because I don't use a Memory Mapped File, but there are many other optimizations lacking (e.g. a lot of objects being created unnecessarily elsewhere in the supporting code).

It can only _read_ an annoy index, not create one (just like the Java version). However, unlike the Java port, it supports index files larger than 4 GB.

I haven't had time to work on it for a while so I thought I'd mention it in case anyone wanted to pick up the project or is looking for a starting point for a more proper C# port.

https://github.com/quole/Word2vec.Tools/blob/master/Word2vec.Tools/AnnoyIndex.cs

**Comment by erikbern** [comment]
> @bnbwn
> 
> If you're still interested in this, you might want to try my fork that is compiling correctly on Windows (at least in python 3.5/3.6).
> 
> https://github.com/tjrileywisc/annoy

@tjrileywisc do you mind sharing a pull request back into annoy?

**Comment by tjrileywisc** [comment]
@erikbern I will submit a PR, just having an issue getting the tests to work after I rearranged the includes to get Linux builds working again (I only have access to Windows Subsystem for Linux so I'm not 100% sure my fix will be correct).

**Comment by erikbern** [comment]
interesting – didn't know about windows subsystem. maybe it's possible for to hook it up with CI

**Comment by tjrileywisc** [comment]
@erikbern PR here for Windows support (only Python 3 for now). I think Linux is working based on my tests in Windows Subsystem for Linux.

https://github.com/spotify/annoy/pull/233

**Comment by tjrileywisc** [comment]
Added Python 2.7 support in this PR https://github.com/spotify/annoy/pull/235

**Comment by MarkWuNLP** [comment]
It works fine on my Windows Server 2012 with Anaconda 3. The only thing I did is to change the compiler=msvc that in the file "C:\Program Files\Anaconda3\Lib\distutils\distutils.cfg".

**Comment by kamalkraj** [comment]
@MarkWuNLP  Thanks.It worked
