### ISSUE TITLE
Euclidean distance instead of angular used?

### ISSUE THREAD

**Issue by wbittremieux** [spotify/annoy#131]
Whether or not I create an index using the angular distance or the Euclidean distance, the distances returned for the nearest neighbor search always seem to be Euclidean distances (`get_nns_by_vector(include_distances=True)`).

I don't know what goes wrong because based on my cursory glance through the source this shouldn't be happening. I also don't know if it's only these distance calculations that are affected or if the whole index always uses the Euclidean distance instead of the angular distance.

**Comment by erikbern** [comment]
I don't think that's true – there's a unit test here: https://github.com/spotify/annoy/blob/master/test/annoy_test.py#L172

**Comment by wbittremieux** [comment]
Ok, see the attached file for an approximation of what I'm doing:
[euclidean.txt](https://github.com/spotify/annoy/files/101872/euclidean.txt)

If I run this, the returned distances are equal to the computed Euclidean distance (I also added the dot product for comparison, the vectors are normalized).

For example, I get the following output:
`annoy_dist = 0.8814489841461182	euclidean = 0.8814489556668296	dot = 0.6115238692769277
annoy_dist = 0.8938978314399719	euclidean = 0.8938978219006966	dot = 0.6004733420005951
annoy_dist = 0.9004353880882263	euclidean = 0.9004354783899279	dot = 0.5946079746283507`

**Comment by erikbern** [comment]
since you are dividing by the norm of the vector, the euclidean and angular distance will be identical

**Comment by wbittremieux** [comment]
Ok, that was silly. Thanks for clearing up the confusion.

**Comment by erikbern** [comment]
np :)
