### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [spotify/annoy#140]
I would like to point out that an identifier like "[`_K`](https://github.com/spotify/annoy/blob/b1a32d5a8676ec2cc2071df729d8281acadc4166/src/annoylib.h#L282)" [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by erikbern** [comment]
Sure wanna send a PR changing the name to `_k` instead?

**Comment by elfring** [comment]
How do you think about to rename also the identifier "`__ERROR_PRINTER_OVERRIDE__`"?

**Comment by erikbern** [comment]
sure, go ahead
