### ISSUE TITLE
norm of splitting points

### ISSUE THREAD

**Issue by nicolamontecchio** [spotify/annoy#142]
(i'm only considering the **angular** case here)

At creation time, the split points are created as a vector difference here 
https://github.com/spotify/annoy/blob/master/src/annoylib.h#L182-L184
This ends up with the split points of different nodes having different norms.

At query time, the margin value that is used as priority for the PQ (https://github.com/spotify/annoy/blob/master/src/annoylib.h#L552), is computed as a dot product: https://github.com/spotify/annoy/blob/master/src/annoylib.h#L165

This means that the norm of the split points ends up having an effect on the order of the traversal of the tree, which I don't think is an intended effect. 

The java version of annoy computes the cosine margin from the split point which sidesteps this problem, and intuitively seems the correct thing to do.

Is there something that I am missing here?

**Comment by erikbern** [comment]
Yes this seems incorrect. There is a missing normalization on line 184

I fixed something similar before and it led to a marginal improvement: https://github.com/spotify/annoy/pull/104

**Comment by erikbern** [comment]
Thanks for noticing! Let me fix it this weekend. Hopefully it improves perf a bit

**Comment by erikbern** [comment]
Curious how come you noticed this?

**Comment by nicolamontecchio** [comment]
i was porting the euclidean part to java and found out that the angular one in c++ was suspicious

**Comment by erikbern** [comment]
cool! let me know if you need help

**Comment by nicolamontecchio** [comment]
:+1:
