### ISSUE TITLE
Crash on windows after save

### ISSUE THREAD

**Issue by jfemiani** [spotify/annoy#144]
I build from source on windows (anaconda) using the following commands: 
```
> git clone https://github.com/spotify/annoy.git 
> conda install mingw libpython
> cd annoy
> python setup.py build -c mingw32
> python setup.py install
```
Then to test it:
```
In [1]: from annoy import AnnoyIndex
In [2]: import numpy as np
In [3]: data = np.load('E:/Data/SMALL_ROI/base_examples.npz')
In [4]: examples = data['base']
In [5]: a = AnnoyIndex(9)
In [6]: for i, rec in enumerate(examples):
   ...:     a.add_item(i, rec[:9].tolist())
   ...:
In [7]: a.build(10)
In [8]: a.get_nns_by_vector(examples[1012,:9].tolist(), 5)
Out[8]: [1012, 24873, 501236, 397680, 65851]
```
All works well until I try to save

```
In [9]: a.save('E:/Data/SMALL_ROI/working.annoy')
Out[9]: True

In [10]: a.get_nns_by_vector(examples[1012,:9].tolist(), 5)

***CRASH***
```
That last line was python.exe crashing (ending the interpreter) with no warning. 
When I try to load the data back in there is a random large number of items loaded. 

Also I tried running your nose tests, same issue (see attached). 

Cheers,
John

![2016-03-09 18_55_42-datapart2 e_](https://cloud.githubusercontent.com/assets/2800407/13656956/95c260ec-e628-11e5-8699-5fdb245df8a5.png)

[env.txt](https://github.com/spotify/annoy/files/166397/env.txt)

**Comment by erikbern** [comment]
sorry i don't have access to any windows computers, so i'm not sure what the issue is

would love it if you can help me figure out!

**Comment by andy256** [comment]
One potential problem is the call to fopen() with "w" instead of "wb" in annoylib.h -- does changing that help?

**Comment by jfemiani** [comment]
I'll make sure to look into that first thing tomorrow and let you know if
changing that helps

**Comment by sergeyf** [comment]
I can confirm. I installed successfully as above, and then tried the Python example from the README. 

The crash occurs on the last line:

```u.get_nns_by_item(0, 1000)```

while getting the nearest neighbors from the object that was not loaded from memory works fine:

```
In [10]: np.array(t.get_nns_by_item(0, 1000))
Out[10]:
array([  0, 477, 547, 746, 949, 580, 877,  29, 748, 543, 175, 341, 634,
       447, 796, 294, 489, 750, 549, 760, 770, 878, 872, 718, 822, 559,
       125, 991, 649, 134, 404, 430, 603, 733, 861, 923, 179, 223,  51...
```

**Comment by erikbern** [comment]
would be great if someone can troubleshoot and come up with a solution!

**Comment by a1k0n** [comment]
@jfemiani did you ever get a chance to try it?

**Comment by jfemiani** [comment]
Yes it worked.

**Comment by a1k0n** [comment]
All right, I'll make a PR

**Comment by erikbern** [comment]
thanks!
