### ISSUE TITLE
[question] Is it possible to find all pairs with `distance > some_given_distance` ?

### ISSUE THREAD

**Issue by dselivanov** [spotify/annoy#145]
This is not an issue, but a question. Is it possible to use `annoy` to find all pairs of points with (cosine) distance more then given threshold with some probability?  I guess this is classical LSH use case, which comes from minhashing. I managed to develop my own implementation, but probably `annoy` is much more optimised, so I want to try it. Here is example of S-curve for performing 400 random projections and then applying "banding" LSH technique (same as in minhash) to sketches:

![image](https://cloud.githubusercontent.com/assets/5123805/13872595/c569b518-ecfc-11e5-9d98-14927ce40934.png)

**Comment by erikbern** [comment]
Haven't thought about this use case. There is no such functionality atm, but shouldn't be too hard to implement. Basically during the search (where you use the priority queue) you would have to keep track of the distances and then use some heuristic stopping rule

**Comment by dselivanov** [comment]
@erikbern thanks for your answer. But I suppose in case of usage some heuristic there is no theoretical guarantee for probability of finding candidates within some given similarity region.

**Comment by erikbern** [comment]
I don't know any way to give theoretical guarantees, but generally don't think that's very important. I believe in empirical results :)

**Comment by dselivanov** [comment]
@erikbern this make sense :+1:
