### ISSUE TITLE
How to remove or update an item?

### ISSUE THREAD

**Issue by wong2** [spotify/annoy#146]
currently there is only `add_item`, but how could we remove or update an added item?

**Comment by erikbern** [comment]
There is no such functionality, sorry

Before you build the index, you can overwrite data using `add_item`

**Comment by wong2** [comment]
will you consider adding that?

**Comment by erikbern** [comment]
I wish I had more time, but it's very unlikely at this point

**Comment by erikbern** [comment]
But would love to see a pull request for it
