### ISSUE TITLE
Strange behavior with extremely large amounts of data.

### ISSUE THREAD

**Issue by shawnjhenry** [spotify/annoy#147]
Hi,

I'm seeing some curious behavior indexing large amounts of data.  If I index 1 million vectors of size 300 in 32 trees, query time with default settings for top 10 is about 0.005 seconds, so if I want to index 20 million vectors, I can create 20 indices with 1 million vectors each and query in 0.1 seconds (plus a negligible amount of time to sort and filter the total result).  It should be faster to create a single index with 20 million vectors, but when I do that query time skyrockets to 5 seconds.  Any idea why that might be?

Thanks,
Shawn

**Comment by erikbern** [comment]
I would guess you're just hitting disk because of the page cache. Does the total size of all indexes fit in RAM? If you do a few thousand queries does the query time start increasing?

**Comment by erikbern** [comment]
Most likely the kernel swaps out the indexes to disk. As you do more and more queries, the kernel will put the indexes back into RAM and you should start seeing substantial speedup. It's just how the page cache works

**Comment by erikbern** [comment]
Another thing you can do to warm up the page cache is to just read them from disk a few time. If you cat all the files to /dev/null a few times you will probably see that the first time it takes a long time, but subsequent times it will be substantially faster

**Comment by piskvorky** [comment]
(if you're on linux, both `ps` and `top` can display the number of page faults, which can be useful for debugging such issues)
