### ISSUE TITLE
Increasing accuracy of search

### ISSUE THREAD

**Issue by eldor4do** [spotify/annoy#148]
I have about 13000 arrays, each of dimension 2048. Currently, I have 10 trees, which I have tried increasing straight to 48 to see if that improves things or not. I am querying 400 results, which would make total default queries to be 10 \* 400 or 48 \* 400.

My problem is, in the results which I am getting, it is missing certain items which have less distances, meaning it can't find those items. Those elements are present in the tree, since querying by get_distance(i,j) gives me the minimum distance, but while querying get_nns_by_item(i, ..), I can't find element 'j' in my result.
How do I increase it's search accuracy, or is there something else I am doing wrong?

**Comment by erikbern** [comment]
Annoy doesn't guarantee to find the nearest items – that's suspected to be an NP complete problem. It will return most of them though.

Try to increase the parameter `search_k` to something larger. That will cause Annoy to search more nodes.

With only 13000 items it's possible you might be better off just doing an exhaustive search.

The other option I would recommend is to pre-process the data set by doing dimensionality reduction. Annoy was built for roughly <100 dimensions, although I've seen it work well up to 1000 dimensions. Not sure what distribution your data set has, but something like a truncated SVD might work well: http://scikit-learn.org/stable/modules/generated/sklearn.decomposition.TruncatedSVD.html

**Comment by piskvorky** [comment]
@eldor4do The "A" stands for "Approximate". SVD tip: if you have a large dataset, you'll run out of memory quickly with sklearn. For fast and memory efficient truncated SVD, you can use [gensim SVD](https://radimrehurek.com/gensim/models/lsimodel.html) instead.

@erikbern NP-complete... hmm. In what var? A brute force linear scan will find the nearest items 100%, and is linear (in the input data size).

**Comment by erikbern** [comment]
@piskvorky sorry i'm drunk. I didn't mean NP-complete – meant that it's suspected that it's impossible to do in *less than linear time* (but this has not been proven)

didn't know gensim has truncated SVD – good to know!

**Comment by thomasjungblut** [comment]
FYI a neat trick has been proposed in [this paper](https://arxiv.org/abs/1602.00370v2) which builds multiple projection trees and then iteratively refines the nearest neighbours.

**Comment by erikbern** [comment]
interesting – might be worth experimenting with

**Comment by a1k0n** [comment]
Isn't that paper pretty much exactly what annoy is already doing? It even
uses a heap as a priority queue. The construction method is the same as
well.

**Comment by erikbern** [comment]
i'm thinking this could work
1. use fewer trees
2. when you get to the leaf nodes, pick some neighbors and search by those neighbors
3. since we're using fewer trees, we get better cache locality
4. fewer trees also means we can avoid searching nodes we already searched, meaning we don't waste time exploring similar nodes

**Comment by erikbern** [comment]
in fact you could actually extend the current priority queue to do this pretty easily. you just need to keep track of (a) what vector are you searching by (b) what's the distance from the initial query point (so that you can add it to the distance)

**Comment by Santimto** [comment]
@erikbern I am doing tests with bases of almost 1million of data and my interest is to improve the precision of the results.

I am currently using:
dims = 2048
n_nearest_neighbors = 30
trees = 1000

To improve accuracy would it indicate reducing the number of trees? And in the part: t = AnnoyIndex (dims), the higher the better?

Congratulations on the project!

**Comment by erikbern** [comment]
i would reduce the number of trees to say 100. This will decrease accuracy, but 100 is more reasonable. Increase search_k during search instead!

**Comment by Santimto** [comment]
I'm not currently passing search_k. As I checked that search_k is n * n_trees, so am I analyzing 30k items coming up for similarity?

I'm going to do the test assigning this value to 200k (1mi base).

Analyzing your articles I really liked the: https://erikbern.com/2018/02/15/new-benchmarks-for-approximate-nearest-neighbors.html. For the task of finding the closest images for a new image on really big bases do you recommend any of them (HNSW, KGraph or other)?

Thanks for the response in such a short time!

**Comment by erikbern** [comment]
Also 2048 is a LOT of dimensions. I would use some kind of dimensionality reduction to have fewer dimensions.

I haven't tried the other methods but HNSW/KGraph is a bit faster and more accurate (though they don't have the ability to save indexes to disk)

**Comment by jay-trivedi** [comment]
@Santimto 

> @erikbern I am doing tests with bases of almost 1million and my interest is to improve the precision of the results.
> 
> I am currently using:
> dims = 2048
> n_nearest_neighbors = 30
> trees = 1000
> 
> To improve accuracy would it indicate reducing the number of trees? And in the part: t = AnnoyIndex (dims), the higher the better?
> 
> Congratulations on the project!

I am dealing with a similar scale of items and facing issues with large index size. can you please share approximate size of your index in your case?

Thanks
