### ISSUE TITLE
Angular distance in Readme 

### ISSUE THREAD

**Issue by benbo** [spotify/annoy#149]
I realize that Annoy uses Euclidean distance of normalized vectors for its angular distance, which for two vectors u,v is equal to 2(1-cos(u,v)). The readme currently mentions cosine similarity but not how it is connected to the angular distance that is actually calculated. It would be nice to have this reflected somewhere in the readme as values greater than 1 in the distance could confuse users who expect the angular 'cosine distance' to be just 1-cos(u,v). I for example spent some time checking for mistakes as I was wondering if I had to normalize the vectors myself before adding them as I was unaware that the definition of angular distance here was 2(1-cos(u,v)) and I mistakenly expected values to lie in [0,1].

**Comment by erikbern** [comment]
sure – do you want to edit the documentation and send a pull request? thanks!

**Comment by benbo** [comment]
Sure. Should I add a tiny section to "How does it work" or rather to "more info"?

**Comment by erikbern** [comment]
Either one of them is fine. Thanks!

**Comment by MonkeyChap** [comment]
Hi,

Just waking up an old thread. Can you clarify if Annoy is normalising all the vectors (e.g. to a 0.0->1.0 range) or if the data must be supplied to it pre-normalised ?  The reason I ask is that I'm getting quite different results with FLANN and ANNOY and I think FLANN normalises before indexing. 

Thanks

Ian

**Comment by erikbern** [comment]
If you use angular distance then there's no need to prenormalize

**Comment by MonkeyChap** [comment]
Thanks for the quick response Erik !
