### ISSUE TITLE
How the n is related to the # of trees?

### ISSUE THREAD

**Issue by StevenLOL** [spotify/annoy#152]
Hi, 

Have similar issues regarding the [accuracy of search](https://github.com/spotify/annoy/issues/148).

I have 400k vectors of 200 dims and

 annoyindexer.build(32)

When query with annoyindexer.get_nns_by_vector(v1,1000) the results (top10) is so much better to annoyindexer.get_nns_by_vector(v1,10)

Should I using more tree to index my data or just simply querying with a big n to get better accuracy?

**Comment by erikbern** [comment]
That's expected. I recently added the `search_k` parameter to be able to vary this separately.

Try `get_nns_by_vector(v1, 10, search_k=1000)`
