### ISSUE TITLE
pip install on Mac OSX

### ISSUE THREAD

**Issue by seanlaw** [spotify/annoy#156]
Not sure why this is happening but on a Macbook Pro (Yosemite)

<pre>pip install annoy</pre>

Causes:

<pre>src/annoylib.h:19:18: fatal error: string: No such file or directory</pre>

However, the same command on a RHEL installs without any problems.

**Comment by erikbern** [comment]
were you able to fix this? since you closed the issue

**Comment by seanlaw** [comment]
It's not entirely clear what happened but restarting my terminal fixed the problem. I tried it on a Mac Mini which worked fine as well and so it could've been a problem with my environment.
