### ISSUE TITLE
Python crashes when using Euclidean distance

### ISSUE THREAD

**Issue by tangfucius** [spotify/annoy#157]
I am following the Python code example on the front page on iPython notebook, but if I change metric to Euclidean python crashes when I run u.get_nns_by_item. 
Has anyone else encountered this problem? I am on Python 2.7 on OS X.

**Comment by erikbern** [comment]
can you share code?

off the top of my head maybe you are changing the metric *after* you already built the index? that would probably lead to a crash

**Comment by tangfucius** [comment]
sorry it was a stupid mistake on my part. I didn't put in the metric argument when I loaded the index.

**Comment by a1k0n** [comment]
still, might be good to catch the error and raise an exception or something instead of crashing...

**Comment by erikbern** [comment]
not sure how to catch the error – there's no marker in the file that says what distance function is used

i guess you could have some sanity checks when you load the index to make sure it's not corrupt (i.e. there's no pointers to offsets outside the file) but it won't be a 100% guarantee

**Comment by a1k0n** [comment]
Yeah, with no header on the format, I guess it's doomed to be error-prone...

I can envision a backward-compatible way to introduce one, though, since it loads indexes from the end rather than the beginning of the file..
