### ISSUE TITLE
Benchmarks on indexing

### ISSUE THREAD

**Issue by ajkl** [spotify/annoy#158]
Is there a benchmark on indexing time against #trees, #items and #features ?

**Comment by erikbern** [comment]
the data is stored in results/ so it should be easy to plot indexing time.

if you do it feel free to submit a PR!

**Comment by csanhuezalobos** [comment]
Maybe this is a starting point?

https://erikbern.com/2014/01/12/benchmarking-nearest-neighbor-libraries-in-python/

**Comment by erikbern** [comment]
yeah also please check out https://github.com/erikbern/ann-benchmarks
