### ISSUE TITLE
save not work porperly at windows

### ISSUE THREAD

**Issue by birolkuyumcu** [spotify/annoy#160]
windows 10 
Anaconda 2.7.x 64 bit

i install annoy by using pip 
simpy try example code 
after save function destroy values as show in ipython notebook screenshot

![annoy](https://cloud.githubusercontent.com/assets/8981828/16516470/f38e3f64-3f80-11e6-9ccf-a5b590173ea5.jpg)

**Comment by erikbern** [comment]
Sorry about this. I don't have Windows but would love it if someone can debug this.

**Comment by birolkuyumcu** [comment]
problem solved
download 
rebuild annoy
i think binary incompatability of compiled libs caused this problem
now code works as expected
