### ISSUE TITLE
Save and load only the index without the vectors

### ISSUE THREAD

**Issue by w4nderlust** [spotify/annoy#163]
Is there a way to save and load only the index and not the vectors themselves? I have more vectors than fits the memory and I will store them in a key-value store, I only need to keep in memory Annoy's index. I understand how then Annoy could not return the distances, but I don't need it, once I know the vectors ids of the knn, I can retrieve them from the key-value store and compute the distance myself. Is there a way to support this use case?

**Comment by erikbern** [comment]
sorry – there's now way. and generally the annoy index takes more space than the vectors
