### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by SkyTodInfi** [spotify/annoy#167]
`building 'annoy.annoylib' extension
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.6 -c src/annoymodule.cc -o build/temp.linux-x86_64-2.6/src/annoymodule.o -O3 -march=native -ffast-math
cc1plus: error: unrecognized command line option "-mbmi-mavx"
error: command 'gcc' failed with exit status 1`

my gcc version is 4.4.6, any ideas?
Thanks~

**Comment by erikbern** [comment]
Were you able to resolve it?

**Comment by SkyTodInfi** [comment]
Yes,  just remove `-march=native` from `setup.py`,  everything is ok.
Thank you.

**Comment by erikbern** [comment]
ok might be worth removing it in the repository

i'll see if other people have the same issue

**Comment by arjunktr** [comment]
I'm facing the same issue, is there any workaround?

**Comment by erikbern** [comment]
are you on any nonstandard platform?

**Comment by arjunktr** [comment]
Thanks for the reply, I'm trying to install on AWS EC2 which has  python
2.6 version

**Comment by arjunktr** [comment]
Hi Erik,
Is there any workaround for this?

Thanks!

**Comment by erikbern** [comment]
i can't reproduce the issue so i have no idea unfortunately

what happens if you remove the `-march=native` flag?

**Comment by fpergola** [comment]
@erikbern remove the -march=native flag allows install and I've had no issues with using the package.
