### ISSUE TITLE
Binary hash vector from random projection

### ISSUE THREAD

**Issue by ajkl** [spotify/annoy#169]
Given an item vector is there an easy way to extract the binary hash vector ?

**Comment by erikbern** [comment]
Sorry, no, Annoy doesn't use a fixed set of projections, it builds up a tree of random projections.

Curious what's your use case?

Closing this for now

**Comment by ajkl** [comment]
Even with random projections, once the index is built, you can generate a binary hash based on the forest of trees built right? I was wondering if i get binary hash of all the items in the index, i can pack them and save on memory footprint and just perform a hamming distance at runtime. Thoughts ?

**Comment by erikbern** [comment]
Sorry not possible, for the reason I just mentioned. It's a tree not a fixed set of projections
