### ISSUE TITLE
What's the recommended way of adding new items after build() has been called?

### ISSUE THREAD

**Issue by Quasimondo** [spotify/annoy#174]
Right now I have to create a new instance, retrieve all the feature vectors by iterating over all the items in the old instance add them to the new one and finally unload the old one. Is there any better way?

It would be really nice to have something like an "unbuild()" method built in which would do that without having to temporarily double the memory requirements.

**Comment by erikbern** [comment]
I'm not sure how useful unbuild() would be in general but I think it's pretty easy to implement

* clear `_roots`
* set `_n_nodes` to `_n_items`

feel free to send a PR :)

**Comment by kylemcdonald** [comment]
this was literally my first question too, not surprised to find you here @Quasimondo :)

for me, the change was adding to `AnnoyIndex`:

```c++
  void unbuild() {
    if (_loaded) {
      showUpdate("You can't unbuild a loaded index\n");
      return;
    }
    
    _roots.clear();
    _n_nodes = _n_items;
  }
```

and to `AnnoyIndexInterface`:

```c++
  virtual void unbuild() = 0;
```

but the more i play with it, the less certain i am that annoy is the right tool for situations with online/realtime updates. however, if you have two sets of things: one big set you can precalculate, and one smaller set of recent additions, it can make sense to keep to annoy instances and do lookups on both with some final filtering/combining step. then when you add recent additions you only need to do a small rebuild instead of a big one.

**Comment by Quasimondo** [comment]
I am already successfully using Annoy for dynamically adding new elements and at least so far the delay through having to copying all old elements to a new instance, then adding the new elements, building the tree is bearable - though my use case is not realtime and so far I am not yet in the million items areae, so the 2 seconds that this takes I can tolerate. Still it feels like it's a bit ineffective that way.

**Comment by Quasimondo** [comment]
Thanks @kylemcdonald for the detailed code example. Since I'm using the Python wrapper there were a few more changes in addition to the ones you mentioned above necessary to make it work:

In annoymodule.cc I had to add the following lines:
```
static PyObject *
py_an_unbuild(py_annoy *self, PyObject *args) {
  if (!self->ptr) 
    Py_RETURN_NONE;
  
  Py_BEGIN_ALLOW_THREADS;
  self->ptr->unbuild();
  Py_END_ALLOW_THREADS;

  Py_RETURN_TRUE;
}
```

as well as augment the AnnoyMethods[]:
```
static PyMethodDef AnnoyMethods[] = {
  {"load",	(PyCFunction)py_an_load, METH_VARARGS, ""},
  {"save",	(PyCFunction)py_an_save, METH_VARARGS, ""},
  {"get_nns_by_item",(PyCFunction)py_an_get_nns_by_item, METH_VARARGS, ""},
  {"get_nns_by_vector",(PyCFunction)py_an_get_nns_by_vector, METH_VARARGS, ""},
  {"get_item_vector",(PyCFunction)py_an_get_item_vector, METH_VARARGS, ""},
  {"add_item",(PyCFunction)py_an_add_item, METH_VARARGS, ""},
  {"build",(PyCFunction)py_an_build, METH_VARARGS, ""},
  {"unbuild",(PyCFunction)py_an_unbuild, METH_VARARGS, ""},
  {"unload",(PyCFunction)py_an_unload, METH_VARARGS, ""},
  {"get_distance",(PyCFunction)py_an_get_distance, METH_VARARGS, ""},
  {"get_n_items",(PyCFunction)py_an_get_n_items, METH_VARARGS, ""},
  {"verbose",(PyCFunction)py_an_verbose, METH_VARARGS, ""},
  {NULL, NULL, 0, NULL}		 /* Sentinel */
};
```

In annoy/__init__.py these lines have to be added:

```
def unbuild(self):
        """
        Allows to add new items after a tree has been build
        """
        return super(AnnoyIndex, self).unbuild()`
```

After increasing the version number, using `pip install .` from inside the main directory it works in my Python as well now.

**Comment by Quasimondo** [comment]
I just realized that there is one snag with unbuild() for the typical use case: right now this does not work with loaded indices. So what I think this would need to work is to first unlink the index from the shared image but keep a copy, then unload() it, then call unbuild(), add the new items, call build() again. Of course then comes the problem that it cannot save the new index to the same file in case other processes are still using it, but at least in my case there is only one instance using it.

Is that a feasible approach?

**Comment by erikbern** [comment]
I'm actually not sure how it would work. Right now I think you would get a page fault or something if you tried to add an item after doing unbuild() on a load()'ed file. However if you mmap with PROT_WRITE then it might be possible to write back data. The problem is what happens once you overflow the size of the mmapped region – I'm not sure how `_allocate_size` should work in that case.

**Comment by erikbern** [comment]
googling it, it seems like it's possible to resize an mmapped region, but i don't have any more details than that :)

**Comment by robclouth** [comment]
@kylemcdonald fancy seeing you here too! yeah i just came across this. i need to be able to dynamically add new vectors. it seems like the sklearn BallTree implementation has this same restriction. ```unbuild``` is a good start though.

**Comment by robclouth** [comment]
Flann for example allows you to add new points after the initial build, but will trigger a new build of the index after a certain number of additions to re-balance it. I can't find any implementations that don't need re-balancing at some point...

**Comment by erikbern** [comment]
If I had unlimited amount of time (I don't) I would rewrite Annoy to use LMDB. That's probably the best strategy to make it support updates. I doubt I'll ever have the time, but feel free to give it a shot :) I think it could be done in a week of full time work – happy to outline the approach

**Comment by vadimkantorov** [comment]
I'm also looking to dynamically update an index, but don't actually need to save it on disk: training a ConvNet, and need to update the index with freshly computed embeddings. Should calling `add_item(index_to_update, new_vector)` and periodically calling `build()` work?

**Comment by erikbern** [comment]
After you call build, you can't add more items. Or at least you're not supposed to – I think it may lead to undefined behavior. With the PR to do unbuild() it would work (assuming you never map it to disk)

**Comment by vadimkantorov** [comment]
But once unbuild() is called, the index cannot answer NN queries, correct?

**Comment by erikbern** [comment]
you would have to call unbuild(), add items, then call build()

**Comment by Quasimondo** [comment]
I have added two tests in annoy_test.py but I am not sure if I did it correctly:
https://github.com/Quasimondo/annoy/commit/20bda288d06ecf9156199f1df800bb468f26c22b

**Comment by stgzr** [comment]
So is there any solutions for adding new items after index file loaded?
I tried `unbuild()` after calling `load()`, but it just showed `"You can't unbuild a loaded index"`...

**Comment by erikbern** [comment]
there is no way atm

**Comment by beniz** [comment]
@erikbern hi, regarding your comment https://github.com/spotify/annoy/issues/174#issuecomment-255596110 on using LMDB thus allowing annoy to support updates, I'd be interested in hearing more, as you suggested you may outline the approach. Thanks!
