### ISSUE TITLE
Support hamming distance

### ISSUE THREAD

**Issue by bobobo1618** [spotify/annoy#179]
I'm hoping to use annoy to index local features extracted from images in order to build a robust content based image retrieval engine.

My features are binary features however and the optimal distance metric would be hamming distance rather than euclidean or cosine.

Not sure how difficult this is but thought it worth asking!

**Comment by erikbern** [comment]
Hamming would be possible to do fairly easily (probably day's work or something)

Right now it's probably easier to do a dimensionality reduction into a continuous space (for instance train an autoencoder to embed everything in R^40) and you might get better results doing so anyway

**Comment by lakshayg** [comment]
I would like to work on this issue. Can you tell me where to get started?

**Comment by erikbern** [comment]
This is already implemented!
