### ISSUE TITLE
Tiny tweaks in building trees

### ISSUE THREAD

**Issue by yixuan** [spotify/annoy#180]
This is just a tiny issue, but it seems that the code to create the `indices` vector in the `build()` function ([line 344-346](https://github.com/spotify/annoy/blob/master/src/annoylib.h#L344-L346)) can be moved out of the `while` loop, since they are passed as `const` in the `_make_tree()` function.

**Comment by erikbern** [comment]
sure yeah would be a very minor optimization (save like 1ms at most).

closing this, feel free to send a PR if you want to
