### ISSUE TITLE
Can't use annoy after installation

### ISSUE THREAD

**Issue by bobonovski** [spotify/annoy#184]
After installation, I run:
`import annoy`

then I the following error messages:
`
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import annoy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "annoy/__init__.py", line 15, in <module>
    from .annoylib import *
ImportError: No module named annoylib
`

then I tried it in python3, got the same error, what to do ?

**Comment by erikbern** [comment]
How did you install it?

**Comment by erikbern** [comment]
If you used pip, can you paste the full output of the installation?

**Comment by bobonovski** [comment]
Collecting annoy
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading annoy-1.8.0.tar.gz (628kB)
    100% |████████████████████████████████| 634kB 21kB/s
Installing collected packages: annoy
  Running setup.py install for annoy ... done
Successfully installed annoy-1.8.0

**Comment by erikbern** [comment]
and which OS is this?

**Comment by bobonovski** [comment]
ubuntu 14.04

**Comment by erikbern** [comment]
is it still broken? closing until you can verify
