### ISSUE TITLE
Not having consistent results after setting seed

### ISSUE THREAD

**Issue by gg2572** [spotify/annoy#188]
Hi Team,
I hope you're all doing well. Thank you for all hard works you put to develop Annoy.
I've noticed that the most recent commit adds the functionality to set seed, and this is really good for making results reproducible. However, when I run the program with the follow code, it does not produce the same results. Would anyone of you can help me to look at it? 

Thank you very much. I appreciate it.

Best,

Gan

```
import numpy as np
from annoy import AnnoyIndex

X = np.random.rand(100000, 60)
Y = np.random.rand(500, 60)

annoy1 = AnnoyIndex(60)
annoy1.set_seed(100)
for i in range(X.shape[0]):
    annoy1.add_item(i, X[i, :])

annoy1.build(10)

annoy2 = AnnoyIndex(60)
annoy2.set_seed(100)
for j in range(X.shape[0]):
    annoy2.add_item(j, X[j, :])

annoy2.build(10)

result1 = []
result2 = []

for k in range(Y.shape[0]):
    print "annoy1", annoy1.get_nns_by_vector(Y[k, :], 3)
    result1 += annoy1.get_nns_by_vector(Y[k, :], 3)
    print "annoy2", annoy2.get_nns_by_vector(Y[k, :], 3)
    result2 += annoy2.get_nns_by_vector(Y[k, :], 3)
```

**Comment by ijklr** [comment]
Hi Gan, I ran your python, it produced the same results for me. Where do
you see the difference?

**Comment by gg2572** [comment]
Hi Yi Cheng,
Thank you for your reply!
Yes, here's what I get.
```annoy1 [23559, 25499, 49827]
annoy2 [23559, 25499, 49827]
annoy1 [97178, 58504, 30602]
annoy2 [97178, 58504, 30602]
annoy1 [16834, 15731, 15958]
annoy2 [16834, 15731, 15958]
annoy1 [13066, 48258, 14626]
annoy2 [40847, 9026, 28475]
annoy1 [82735, 37999, 56475]
annoy2 [49271, 50974, 45406]
annoy1 [8258, 99461, 3842]
annoy2 [74761, 17914, 42611]```

Sometimes I get the same but sometimes they're different.

**Comment by gg2572** [comment]
So I tried with the same code with a different `numpy` version (1.11.3) and now they're the same. Trying to figure out why the latest `numpy` (1.12.0) is causing the problem.

**Comment by yonromai** [comment]
Maybe the Python/C++ binding code contains some static state that interferes when another tree is created within the same file. But the fact that it depends on the numpy version is kinda scary. 


In any case, when I run this code many times, I always get the same result:
```python
import numpy as np
from annoy import AnnoyIndex

np.random.seed(42)

X = np.random.rand(100000, 60)
Y = np.random.rand(500, 60)

annoy1 = AnnoyIndex(60)
annoy1.set_seed(100)
for i in range(X.shape[0]):
    annoy1.add_item(i, X[i, :])

annoy1.build(10)

for k in range(Y.shape[0]):
    print "annoy1", annoy1.get_nns_by_vector(Y[k, :], 3)
```
Also, when I change the annoy seed, I get different neighbors, which means that the change is propagated.

**Comment by gg2572** [comment]
@yonromai Hi Romain Thank you for your reply. I did notice that Numpy 1.2.0 changed something with numpy.random, but not quite sure if that matters.

**Comment by gg2572** [comment]
Actually it may not be the problem with numpy. I ran a few times with `python2.7` and `numpy1.11`, it gives me different results. However when I use `python3.4`, I'm getting consistent results.

**Comment by erikbern** [comment]
i'm not sure if it's ideal to rely on rand/srand – it's possible that numpy uses it somewhere under the hood as well. `set_seed` uses a global state which is pretty bad. we should probably replace it with a local state RNG like using `<random>`? @yonromai is it something you could take a look at? http://www.cplusplus.com/reference/random/

**Comment by a1k0n** [comment]
Or use the RNG someone already contributed? Or boost::random since it's
already using boost...

**Comment by erikbern** [comment]
> Or use the RNG someone already contributed?

yes even better

**Comment by ijklr** [comment]
@gg2572  so I was able to reproduce it finally. I think it's just python trying to do some optimization by use-using objects. Apparently if they are generated in different scope, then you'll be fine, like this https://github.com/ijklr/annoy/blob/python/seed_test.py

btw The python API uses Kiss64 RNG by default and it has the same seed in the constructor, so even if you don't set the seed, the random numbers should be same every time.

**Comment by gg2572** [comment]
@erikbern @yonromai @ijklr Thank you guys for all the effors! This works for me.
