### ISSUE TITLE
New set_seed not always producing consistent results

### ISSUE THREAD

**Issue by pommedeterresautee** [spotify/annoy#190]
I was trying to have reproductible results with Annoy and discovered the `set_seed` feature has been added merged very recently (https://github.com/spotify/annoy/commit/2de9fd3eee45ef83b1e8d6ed372edc370e503a5c).

In my tests, when I compare several times the retrieval for 2 models based on a large dataset (like 1 million random vectors) of 300d for instance, sometimes I get the same results, sometimes not.
Seems to happen more when the dataset is large that when it is small and dimensions > 100.
FYI results are always perfectly exact with 1000 vectors and 50d (tried many times).

When the test is failing, results retrieved from both models are "very similar" but with the same seed I expect exactly the same resutls. Seems to be an issue with `set_seed` only.

Any idea @yonromai @erikbern ?

FYI my code is in Scala, just calling the C++ with JNI, nothing done in between.

```scala
  val seed = 42
  Random.setSeed(seed)
  val numberOfVectors = 1000000
  val dimensions = 300
  val trees = 30
  val vectors = Array.fill(numberOfVectors)(Array.fill(dimensions)(Random.nextGaussian().toFloat)).zipWithIndex

  val annoy1 = AnnoyInstance(new File(""), dimensions, seed = seed, loadModel = false, verbose = true)
  for ((vector, index) ← vectors) {
    annoy1.addItem(index, vector)
  }
  annoy1.build(trees)
  val annoy2 = AnnoyInstance(new File(""), dimensions, seed = seed, loadModel = false, verbose = true)
  for ((vector, index) ← vectors) {
    annoy2.addItem(index, vector)
  }
  annoy2.build(trees)
  assert(annoy1.getNItems == numberOfVectors)
  assert(annoy2.getNItems == numberOfVectors)
  for (_ ← 1 to 500) {
    val elementToTest = Random.nextInt(numberOfVectors)
    assert(annoy1.getNnsByItem(elementToTest, 100).sameElements(annoy2.getNnsByItem(elementToTest, 100)))
  }
```

**Comment by erikbern** [comment]
I'm not able to reproduce this. See https://github.com/spotify/annoy/blob/master/test/annoy_test.py#L528

I increased this to 100k vectors, 300D, 30 trees

Ran it three times, passes every time

**Comment by pommedeterresautee** [comment]
Python version works also for me (tried with 10 millions 10 times).
I close the issue for now.
Will reopen if I find something related to the C++ part.

**Comment by erikbern** [comment]
is it possible you were using an older version of the c++ code? just speculating

**Comment by pommedeterresautee** [comment]
Nope, using the very last version (yesterday), I am using the set_seed function which have been included very recently.
The bug is quite strange... and this kind of issue difficult to fix (usually I blame the concurrency but here there is none).
I am using Annoy in a prod grade system, having small variations in the results is very... annoying.

I plan to try JavaCpp to call C++ code, may be it will help.

If you have any idea/tip... my mind is very open.
