### ISSUE TITLE
Angular distance function still calculating the euclidean distance? (annoylib.h)

### ISSUE THREAD

**Issue by ijklr** [spotify/annoy#193]
--------------------------------------------------
My apologies, This is most certainly not an issue with the code. Please help me to understand:
--------------------------------------------------
For the `Angular` struct's distance function, it looks like it is not calculating the cosine similarity, but rather just the euclidean distance between two (normalized to unit length) vectors. 

For convenience, I've copied the code here:
```
  template<typename T>
  static inline T distance(const T* x, const T* y, int f) {
    // want to calculate (a/|a| - b/|b|)^2
    // = a^2 / a^2 + b^2 / b^2 - 2ab/|a||b|
    // = 2 - 2cos
    T pp = 0, qq = 0, pq = 0;
    for (int z = 0; z < f; z++, x++, y++) {
      pp += (*x) * (*x);
      qq += (*y) * (*y);
      pq += (*x) * (*y);
    }
    T ppqq = pp * qq;
    if (ppqq > 0) return 2.0 - 2.0 * pq / sqrt(ppqq);
    else return 2.0; // cos is 0
  }
```
and this is the version for `Euclidean`, which is euclidean distance between two non-normalized vectors:
```
  template<typename T>
  static inline T distance(const T* x, const T* y, int f) {
    T d = 0.0;
    for (int i = 0; i < f; i++, x++, y++)
      d += ((*x) - (*y)) * ((*x) - (*y));
    return d;
  }
```

**Comment by erikbern** [comment]
Yes this is "working as intended" – let me know if the documentation is unclear and we can fix it

**Comment by geert56** [comment]
It looks like the angular distance still has a normalize_distance function that is a left-over
from when it was wrongly implemented as Euclidean. There is no need for a sqrt() computation
to obtain the final distances of the nearest neighbors (although quite often these distances are
discarded).
