### ISSUE TITLE
index with single vector after save

### ISSUE THREAD

**Issue by tpeng** [spotify/annoy#194]
Hi,

I noticed following code return wrong result:

```python
from annoy import AnnoyIndex

a = AnnoyIndex(3)
a.add_item(0, [1, 0, 0])
a.build(10)
a.save('1.ann')
print(a.get_nns_by_vector([1, 0, 0], 3, include_distances=True)) # ([1, 2, 3], [0.0, 0.0, 0.0])
```

but it works well  without `a.save('1.ann')` (return `([0], [0.0])`)

any thoughts?

**Comment by erikbern** [comment]
this sounds like a bug. let me add a test case for it and see if i can reproduce. thanks!

**Comment by erikbern** [comment]
I'm not able to reproduce this – see #196

did you use the latest version?

**Comment by tpeng** [comment]
hmm, apologies, i use 1.8.0.
checking the commit history, looks like https://github.com/spotify/annoy/commit/c33b84909aa96b75a055fe78b909ef53a9f1ba5c fixed it. closing it.

**Comment by erikbern** [comment]
ok awesome :)
