### ISSUE TITLE
Changelog? Tags? Something?

### ISSUE THREAD

**Issue by loisaidasam** [spotify/annoy#197]
Hi, great lib, I hope this issue doesn't come off as complaining, but ...

I noticed that there aren't any tags, and I can't seem to find any sort of changelog anywhere. Am I missing it?

It would be cool if the versions that were uploaded to pypi got tagged to make it easier to differentiate changesets.

What I was able to deduce was from looking at [the history of `setup.py`](https://github.com/spotify/annoy/commits/master/setup.py) for version changes, for example here's the `1.8.0` release:

https://github.com/spotify/annoy/commit/3b35aebbca24eeba17ef70128c4e4c40d8f157d1

**Comment by erikbern** [comment]
yeah might make sense – i'll try to remember to add a tag next time :)

**Comment by erikbern** [comment]
tagged the latest version

**Comment by loisaidasam** [comment]
I'd love to see some more tags if possible.

I was just trying to compare a few (older) versions and found it very difficult. In the end I used pypi's history (https://pypi.org/project/annoy/#history) and then looked through the project's commit history (https://github.com/spotify/annoy/commits/master) to find related commits around those dates.

This is a bit of a tedious task, but might be helpful to others down the road.

Applying older tags should be as simple as:

```
git checkout 079a6786135e9a229d2ab7ba73c9679bc229a5b5
git tag v1.8.3

...

git checkout f547058b5d9d7f230c9bf2684d1879665e45ea8e
git tag v1.9.3

... etc
```

**Comment by erikbern** [comment]
i've been trying to set tags in git yeah
