### ISSUE TITLE
Annoy performs more poorly than before

### ISSUE THREAD

**Issue by yonromai** [spotify/annoy#198]
NN Distances when indexing and querying the same data, only difference is the version of Annoy:

| Version | Min | Q1 | Median | Q3 | Max | 
| --- | --- | --- | --- | --- | --- |
| v1.5.2 | 0. |   0.239  | 0.264 | 0.288 | 0.424 |
| v1.8.3 | 0.  | 0.483 |  0.508 |  0.530 |  0.643 |

I found similar performance problems on Spotify data when upgrading Annoy. 
@erikbern Has annoy a lower default `search_k` parameter than before or something like that?

---

Reproducing these results:
```sh
pip install virtualenv

virtualenv old_annoy
source old_annoy/bin/activate
pip install numpy annoy==1.5.2 --upgrade
python bench.py
deactivate

virtualenv new_annoy
source new_annoy/bin/activate
pip install numpy annoy --upgrade
python bench.py
deactivate
```

Where `bench.py` is:
```py
import numpy as np
from annoy import AnnoyIndex

np.random.seed(42)

f = 40
N = 300000
t = AnnoyIndex(f)  # Length of item vector that will be indexed
for i in xrange(N):
    t.add_item(i, np.random.random(f))

t.build(10) # 10 trees

d = []
nn = 100
for i in xrange(10000):
    for n in t.get_nns_by_item(i, nn):
        d.append(t.get_distance(i,n))

print np.percentile(d, [0, 25, 50, 75, 100])
```

**Comment by erikbern** [comment]
get_distance actually changed at some point – it looks like if you square all the distances in v.1.8.3 then you get roughly the distances in v1.5.2 (actually marginally better)

**Comment by erikbern** [comment]
https://github.com/spotify/annoy/pull/171

**Comment by erikbern** [comment]
closing this until further notice :)
