### ISSUE TITLE
How to use L1-distance？

### ISSUE THREAD

**Issue by agangzz** [spotify/annoy#199]
annoy supports L2-distance（Euclidean disance）, so how to revise the code for L1-distance?

Could you show me some example? Thank you very much.

**Comment by erikbern** [comment]
it doesn't support L1 distance, but it wouldn't be very hard to add... let me know if you need any pointers

**Comment by natanlaverde** [comment]
I implemented the L1 distance modifying the L2 distance and also the tests for python.
I made a pull request [#206](https://github.com/spotify/annoy/pull/206) containing that.

**Comment by eugenepalovcak** [comment]
Hi, I just installed annoy and I've been having trouble getting the Manhattan distance to work. If I run:
`from annoy import AnnoyIndex 
f = 2
i = AnnoyIndex(f, 'manhattan')
i.add_item(0, [2,2])
i.add_item(0, [2,3])
i.add_item(0, [3,3])
i.build(10)
i.get_nns_by_item(0,3)` then

**Comment by eugenepalovcak** [comment]
Hi, I just installed annoy (on Ubuntu 16.04, with 'pip install annoy', today) but haven't gotten the L1 distance to work. If I run:

from annoy import AnnoyIndex
f = 2
i = AnnoyIndex(f, 'manhattan')
i.add_item(0, [2,2])
i.add_item(1, [3,2])
i.add_item(2, [3,3])
i.build(10)
print i.get_nns_by_vector([2,2],3)

the output is 'None'. The 'angular' distance instead works as expected. Is something wrong?

**Comment by erikbern** [comment]
L1 distance isn't pushed to pypi yet – you have to clone the github repo and build it from scratch

i can bump the latest version on pypi today

**Comment by erikbern** [comment]
i've bumped it to 1.9.0 and uploaded to pypi – can you try again?
