### ISSUE TITLE
Reducing RAM with float16?

### ISSUE THREAD

**Issue by bartolsthoorn** [spotify/annoy#200]
Hi, this is more a question than an issue :smile: is it possible to reduce the RAM while creating the index by setting `type='float16'` on my numpy arrays?

```python
f = 40
t = AnnoyIndex(f)  # Length of item vector that will be indexed
for i in xrange(1000):
    v = [random.gauss(0, 1) for z in xrange(f)]
    t.add_item(i, np.array(v, dtype='float16'))
```
I am dealing with ~40M vectors and I have 8GB of RAM, and now I'm hitting the swap at the end a bit.

**Comment by erikbern** [comment]
sorry won't be enough – annoy uses float32 internally

i tried to compile it with half precision floats and it wasn't necessarily faster. although saves memory so maybe it's worth exposing that option to the end user

**Comment by piskvorky** [comment]
+1 on single precision.

It should make a significant difference in practice (near ~2), both for memory & speed. @erikbern maybe the compiler wasn't generating SIMD/SSE for your CPU properly? Still, I'd expect a speedup, even if just due to more effective caching.

**Comment by andy256** [comment]
float32 *is* single precision​. I don't know if there's any native support for half precision...

**Comment by erikbern** [comment]
I just compiled it with some random half-precision float library I found online. Forgot which. But it ended up being slightly slower because of the overhead (extra arithmetic)

Is there native float16 support in gcc? Only thing I can find is __fp16 but it's only ARM: https://gcc.gnu.org/onlinedocs/gcc-4.5.3/gcc/Half_002dPrecision.html

**Comment by piskvorky** [comment]
Hah, I misread completely. My apologies.

I thought it was weird -- vaguely remembered Annoy being single precision :)

**Comment by bartolsthoorn** [comment]
I am not so concerned about speed, just about RAM, but I wasn't aware that using float16 in C is actually quite a hassle.

**Comment by erikbern** [comment]
there is a number of half precision floating point libraries online – since annoy uses templates it's quite easy to use any of them as a drop in replacement – you can try and lmk what happens! i tried it a long time ago and it definitely works, but was slightly slower than single precision float

**Comment by erikbern** [comment]
closing this for now
