### ISSUE TITLE
features larger than 1000 dimension. 

### ISSUE THREAD

**Issue by masakinakada** [spotify/annoy#201]
Hi,

Thank you very much for providing this amazing project. 
I have features of around 1050 dimension, and am wondering if I can use this for this dataset. 
I saw the description saying that this works the best for the data < 100 dimension. 

Please let me know if anybody has any thought, or have tried this.

Thanks in advance.
Masaki

**Comment by erikbern** [comment]
sure go ahead and try!

generally i would recommend some kind of unsupervised dimensionality reduction *before* putting the items in annoy

**Comment by masakinakada** [comment]
Thanks!

Why is it better to do dimensionally reduction? for the speed or for the
accuracy?

Sorry for the additional question.

On Wed, Apr 19, 2017 at 8:54 AM, Erik Bernhardsson <notifications@github.com

**Comment by erikbern** [comment]
yeah it will probably improve either/both of speed and accuracy

**Comment by masakinakada** [comment]
Thank you very much! I will try that then! 
Masaki
