### ISSUE TITLE
Latest version not performing Euclidean Search ?

### ISSUE THREAD

**Issue by MonkeyChap** [spotify/annoy#211]
Hi,

I've been running a version of Annoy that is a few months old on my Mac up until a couple of days ago when I re-installed. I'm now getting near neighbour searches for Euclidean distance that are different to those I got with the old version. They seem to be the results you'd expect from an angular distance search. I ran a brute-force KNN on the same data, and sure enough - the old Annoy lib gets pretty much the same as a KNN euclidean search. The new version doesn't. Could something have broken with the Euclidean search when the Manhattan search was added ?

I'm calling it with:

myIndex = AnnoyIndex(myData, metric="euclidean")

...but the data it returns when queried looks like cosine/angular distance comparison.

I put print statement in the __init__.py to check the metric variable is being passed, and it's certainly getting that far. Can't tell what's happening inside the compiled library though.

I'll dig around in the C code, but my C is so rusty I doubt I'd be able to spot a bug if there's one there.

Ian

**Comment by erikbern** [comment]
that's weird. i made some changes to the metric argument recently. let me check if i broke something accidentally

**Comment by erikbern** [comment]
actually there are already tests for this, see eg https://github.com/spotify/annoy/blob/master/test/annoy_test.py#L264

so it's likely you're doing something strange.

can you share source code that reproduces the behavior?

**Comment by MonkeyChap** [comment]
Thanks - I couldn't see anything obvious other than the catch-all for unknown metrics...but couldn't see any issues in that. If you need example data let me know and I'll write some scripts to generate it.

**Comment by MonkeyChap** [comment]
Hi

Our code didn't change. I can reproduce the problem by reinstalling (pip) Annoy at either 1.8.3 or 1.9.1. With 1.8.3 we get great results that closely match Euclidean brute KNN. At 1.9.1, with no changes to our code, we get output that looks more like what you'd expect for cosine distance.

Ian

**Comment by erikbern** [comment]
that sounds problematic. can you share relevant code?

**Comment by erikbern** [comment]
i'm able to reproduce this.

```
>>> import annoy
>>> a = annoy.AnnoyIndex(3, metric='euclidean')
>>> a.add_item(0, [1, 0, 0])
>>> a.add_item(1, [2, 0, 0])
>>> a.get_distance(0, 1)
0.0
```

**Comment by erikbern** [comment]
i think the problem is the initialization in c++ is using the `tp_new` member rather than the `tp_init` member, and so the Python layer's code to handle the kwarg is ignored. the solution is either to change `tp_new` into `tp_init`, or remove the subclass constructor and handle the kwarg in the c++ module

i'm somewhat biased towards the later approach since imo the whole python glue code is a bit ugly

**Comment by MonkeyChap** [comment]
Here goes...

First stage - create the index:

`myIndex = AnnoyIndex(myData, metric="euclidean")`

then loop through the data, adding each vector:

```
for i,vector in enumerate(myData) :  
	myIndex.add_item(i,vector)
myIndex.build(10)
myIndex.save('testdata.annoyIndex')
```
Then I'm calling get_nns_by_item to get the six near neighbours for each of the items the user selects:

result = myIndex.get_nns_by_item(selectedItem,6)
			
Pretty simple really, but I get different neighbours in some cases using the two different versions of Annoy. It's not always the case, but it's often enough to stand out when I'm using test datasets I know well. The results look a bit like angular distance comparisons when I run Euclidean on 1.9.1. On 1.8.3 they're pretty close to brute-force KNN - so close in fact that I rarely see a wrong neighbour. In both cases, it's really fast - awesome NN algorithm !

**Comment by MonkeyChap** [comment]
Ah - I'm lagging here - sounds like you've found the problem !

**Comment by erikbern** [comment]
the workaround for now is just don't use the metric=xyz as a kwarg, just pass it as a second argument
