### ISSUE TITLE
Access to more data of annoy building result

### ISSUE THREAD

**Issue by shmida1991** [spotify/annoy#214]
Hello,

I'm trying to visualize the data that is generated by Annoy,
Currently the Python API suuports only ANN search of a specific item/vector.
Is there any way that I'll be able to view the inner trees data and dimensions' sub-divisions using Python? 

Thanks

**Comment by erikbern** [comment]
that would be interesting, but unfortunately there's no way right now

the binary format of annoy is very easy though. you could probably just try to open the annoy index raw in Python and try to parse it. There's some documentation in annoylib.h

closing this for now.
