### ISSUE TITLE
Is the search_k parameter correct?

### ISSUE THREAD

**Issue by phdowling** [spotify/annoy#216]
This issue is a bit of a strange one: I accidentally set search_k=-10 instead if search_k=10, and I was getting good results. Once I switched it to positive 10, the results got worse. I thought maybe I'll just reset it to default, and set it to search_k=-1 (I figured this would be the same behavior as -10), but I got different, but still bad results!

Takeaway for me is that a large negative value works well, but I have no idea what this means. Is it maybe a negative overflow issue and this is roughly the same as using a large positive value?

**Comment by a1k0n** [comment]
Yes, it's (size_t) -10, which is going to be a large positive number. Effective you're doing brute force search of the entire thing, which is why you get better results.

**Comment by erikbern** [comment]
haha that's funny

closing this though
