### ISSUE TITLE
Memory Leakage

### ISSUE THREAD

**Issue by ulges** [spotify/annoy#219]
Hi there,

annoy (great library!) is our goto solution for NN search. I'm creating multiple annoy indices, add multiple samples to each, save each, and unload each:

```
import memory
from annoy import AnnoyIndex
import numpy as np

dim = 49152
nsamples = 209

def vectors_to_add():
    v = nsamples * [None]
    for i in range(len(v)):
        v[i] = np.zeros(dim)
    return v

def build_index(count):
    knn = AnnoyIndex(dim, 'euclidean')
    v = vectors_to_add()
    for i,vector in enumerate(v):
        knn.add_item(i,vector)
    knn.save('knn-%d.aix' %count)
    knn.unload()
    del knn # to make sure (?)

for count in range(100):
    build_index(count)
    print 'Added index no.', count, ': total memory -> ', memory.memory()/(1024**3), 'GB'
```

When running on a (virtualized) Debian 9, I experience massive memory leakage:
Added index no. 0 : total memory ->  0.459384918213 GB
Added index no. 1 : total memory ->  0.769920349121 GB
Added index no. 2 : total memory ->  1.003074646 GB
Added index no. 3 : total memory ->  1.2364730835 GB
Added index no. 4 : total memory ->  1.46962738037 GB
...

When running on an Ubuntu 16.04, things are fine:
Added index no. 0 : total memory ->  0.232261657715 GB
Added index no. 1 : total memory ->  0.231666564941 GB
Added index no. 2 : total memory ->  0.231666564941 GB
Added index no. 3 : total memory ->  0.231666564941 GB
Added index no. 4 : total memory ->  0.231666564941 GB
Added index no. 5 : total memory ->  0.231666564941 GB
...

Remarks:
- I'm not even running build() on the index structure, just adding samples.
- I looked at the C-code in annoylib.h and cannot find any leak.
- I wonder if memory mapping (mmap/munmap) is the issue (?) or anything with the C-Python-interface (?)
- The memory measurement (memory.py) is self-implemented and drawn from [here](https://stackoverflow.com/questions/938733/total-memory-used-by-python-process) (reads from /proc/pid/status, should be OK, I can share if it helps).
- I tried with annoy installed from pip (1.9.3) and from source (same issue).

My questions:
1. Is there any hint to what's going on? (I'm aware this may be rather a platform issue than an issue with annoy itself. Still, any pointers are greatly appreciated ;-) 
2. What system libraries can I check/update?
3. Should I check if MAP_POPULATE (annoylib.h) is set? (and if yes, how do I do that?)

Kind regards (and thank you so much!),
Adrian

**Comment by ulges** [comment]
Hi there,

I did some more testing on different platforms:
- Debian 9 non-virtual -> leakage :-(
- Ubuntu 16.04 virtual -> leakage :-(
- Ubuntu 16.04 non-virtual (different machine) -> no leakage :-)

Any thoughts are welcome ;-)

Cheers,
Adrian

**Comment by ulges** [comment]
Did some more testing... it turns out to work better for older annoy versions, but there are cross-effects with platform and virtualization:

virtual?        Platform        Annoy 1.8.0         Annoy 1.9.3
-----------------------------------------------------------------------------------------------------
yes            Debian 9         LEAK                    LEAK
yes         Ubuntu 16.04       OK                       LEAK
no             Debian 9            OK                      LEAK
no           Ubuntu 16.04       OK                       LEAK

Cheers,
Adrian

**Comment by erikbern** [comment]
memory consumption is hard to measure – did you keep the program running for a while? if there truly is a memory leak then eventually malloc will fail and the program will crash. if it's not then the memory usage will converge to some high amount

your code doesn't even use mmap so i doubt that's the issue. it's entirely possible that it's something out side of Annoy, like just Python GC (although I assume you kept the python version same when you tested 1.8.0 vs 1.9.3)

could use valgrind i guess to see if it helps

nothing has changed related to memory allocation so I'm surprised you're seeing different result.

**Comment by ulges** [comment]
My bad! There was a bug in my measurements earlier (I had placed annoy 1.9.3 in my home, where pip looked it up, i.e. one of my tests accidentally used annoy 1.9.3 instead of 1.8.0). Here's the correct data:

|virtual?   |     Platform      |  Annoy 1.8.0   |      Annoy 1.9.3|
|------------|---------------------|-----------------|---------------------|
| yes    |        Debian 9   |     OK               |     LEAK |
| yes  |       Ubuntu 16.04     |  OK          |             LEAK |
| no    |         Debian 9         |   OK           |           LEAK |
| no     |      Ubuntu 16.04   |    OK            |           LEAK |

It does look like a library issue to me now (same for all platforms). The leak seems to appear when switching from 1.9.2 to 1.9.3.

I'll work with 1.9.0 for now. Let me know if you're interested in further input.

**Comment by erikbern** [comment]
are you saying 1.9.2 doesn't leak? that's very helpful – i'll try to understand what happened between 1.9.2 and 1.9.3

**Comment by ulges** [comment]
Correct. I'm adding my repro script (also see above), should be easy to run.

[repro.zip](https://github.com/spotify/annoy/files/1252939/repro.zip)

Cheers,
Adrian

**Comment by erikbern** [comment]
OK – thanks. It's possible I messed something up when I removed the Python glue.

Off the top of my head it's possible that I need to decrement the refcount to lists or numpy arrays that are passed into the C layer

**Comment by erikbern** [comment]
actually i wonder if the problem is here: https://github.com/spotify/annoy/blob/master/src/annoymodule.cc#L202

probably need a `Py_DECREF(pf)`

let me put together a a pull request and see what happens

**Comment by erikbern** [comment]
https://docs.python.org/2.4/api/refcountDetails.html

*Therefore, the generic functions that return object references, like PyObject_GetItem() and PySequence_GetItem(), always return a new reference (the caller becomes the owner of the reference).*

**Comment by erikbern** [comment]
@ulges can you run your script with latest master and see if it works now?

i'll push a 1.9.4 to pypi once you have confirmed it

**Comment by ulges** [comment]
ACK. Cloned the master, ran the script. It works fine now, the leak is gone.

**Comment by erikbern** [comment]
awesome!

**Comment by erikbern** [comment]
uploaded to pypi now

**Comment by ulges** [comment]
Great - thanks for the quick help!

**Comment by erikbern** [comment]
thanks for all the help identifying the bug and nailing down the problematic version!
