### ISSUE TITLE
Is it possible to use annoy index instance with multiprocess workers?

### ISSUE THREAD

**Issue by jklapuch** [spotify/annoy#222]
```import time
from multiprocessing import Process, Queue
from annoy import AnnoyIndex

def annoy_item_generator():
    i = 0
    while True:
        yield i
        i += 1

annoy_i_gen = annoy_item_generator()

class Worker(Process):
    def __init__(self, queue, index, *args, **kwargs):
        super(Worker, self).__init__(*args, **kwargs)
        self.queue = queue
        self.index = index

    def run(self):
        st = time.time()
        while time.time() - st < 5:
            if not self.queue.empty():
                item_vector = self.queue.get()
                self.index.add_item(annoy_i_gen.next(), item_vector)
                print "Worker {} : {}".format(self.name, self.index.get_n_items())
            time.sleep(0.1)

ai = AnnoyIndex(2)
q = Queue(1000)
n_workers = 4
workers = []

for i in xrange(n_workers):
    p = Worker(queue=q, index=ai)
    p.start()
    workers.append(p)

vectors = [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9)]

for v in vectors:
    q.put(v)

for p in workers:
    p.join()

print "Master: {}".format(ai.get_n_items())
```

```
Worker Worker-4 : 1
Worker Worker-1 : 1
Worker Worker-2 : 1
Worker Worker-3 : 1
Worker Worker-4 : 2
Master: 0
```

**Comment by erikbern** [comment]
to answer the issue title: yes, absolutely

i don't have the energy to understand your code so please explain :)

btw probably makes sense to store the index to a file and load that file independently in each process since mmap is read only so guaranteed to be shared across processes

**Comment by jklapuch** [comment]
Ok, sorry. I tried to create a simple example. In my code I starts 4 processes as workers with shared queue, then the master process fills this queue with the vectors and the workers take them from the queue and put them in the annoy index. When creating a worker, I pass an annoy index instance as a parameter. I checked that each worker shows the index with the same memory address. But when I list the number of vectors in the index, each process only shows the number that it added itself, so the annoy index is not shared. I do not know how to create this shared object. Using shared memory from multiprocessing package works only for dict and list objects...

When I load the built index individually in each process, then I get a lot of memory usage.

**Comment by erikbern** [comment]
ok – for best performance, try to save the index to disk, and then in each worker process, load it from disk. since mmap will share the memory in a read-only way, it will only consume the memory once

**Comment by jklapuch** [comment]
Perfect, thanks. A didn't know that about mmap.

**Comment by piskvorky** [comment]
Seems @jklapuch wants to construct an Annoy index in parallel, using several workers. How does a read-only mmap'ed index help here?

**Comment by erikbern** [comment]
oh sorry, i didn't read the code. yeah you can't create an index across processes. has to be a single process. you can't even use multiple threads afaik
