### ISSUE TITLE
recall rate low in own benchmarks

### ISSUE THREAD

**Issue by jethrokuan** [spotify/annoy#229]
Hi, i'm doing some benchmarking on my own set of data, and annoy seems to give accuracies I do not expect.

My data set has about 300,000 high-dimensional vectors. 

I have built annoy indexes of varying number of trees, and compared the results returned to the ones returned in an exhaustive exact search. For example, a top 50 recall would be the number of elements in the set returned by annoy that intersects with the result returned by the exact search, divided by 50.

It seems that my recall rate plateaus at about 80%, where increasing the number of trees and `search_k` no longer improves the situation.

Is this a result that I should be expecting?

EDIT: removed image, because it might've been too revealing

**Comment by erikbern** [comment]
no it should converge to 100% at some point. you can verify that by setting search_k to some enormous number so that it degenerates into exhaustive search.

but hard to say without knowing more about the data. what's the dimensionality?

**Comment by jethrokuan** [comment]
I think I figured it out. The exact search I was using was using a slightly different metric as compared to the one I used with annoy. Your comment somehow led me down this path of thought. Thanks!!

**Comment by erikbern** [comment]
nice, thanks
