### ISSUE TITLE
Index size reduced to half after save and load

### ISSUE THREAD

**Issue by Thommas2316** [spotify/annoy#230]
Hello,

I'd like to ask for help as I got to end, when I can not figure out what exactly I'm doing wrong :D 
I'm using `annoy 1.9.5` installed via `pip`, using `Pyhon 3.5.2` on my `Desktop Ubuntu 16.04` .

**I tested this functionality here** : 
https://gist.github.com/Thommas2316/cee12449f07099e60c7afbad1b805db3
As you can see on lines `134-135` and `151-154` of this gist **everything goes as expected**.

Here comes the **"but"**- In real project I try to do following :
1. Create indexer instance
2. Add vectors and labels to 2 annoy indexes in class (1 for vectors, 1 for classes as I need to compare additional values for vectors)
3. Add test vectors and labels to buffer, to be later tested against built index
4. Build index
5. Test built index with buffer data
6. Save Index for later use

But I noticed, that when I save the index and load it again - **the index is just 1/2 of his previous size**. So I turned verbose mode on and figured, that **this happen when I'm saving Index to disk**. When annoy tries to save the index, it automatically loads it from file. As you can see in following gist in file `code.txt` on lines `192-202` index really shrinks after save to be exactly 1/2. In gist please also find attached the class I'm using (`Indexer.py`).
https://gist.github.com/Thommas2316/2d0fcb741a5bd43f4a29f0d49c520fd0

If you could briefly look at this issue and try to help me finding the problem here, I'd be really grateful as I find `annoy` perfect for my use-case in project and really easy and fun to use.

Thank you very much in advance.

Tomas

**Comment by erikbern** [comment]
i'm not following exactly what's going on, but are you loading and saving the same index multiple times? that shouldn't be allowed

**Comment by erikbern** [comment]
I think the problem is in your code. Look at this function

```python
    def generateIndexNumber(self):
        return self.Xindex.get_n_items() + 1
```

This means you will add an item at index 0, 2, 4, ...

**Comment by Thommas2316** [comment]
Wow, I didn't realized that. 
Thank you for your quick response, you saved me a lot of time.

Have a wonderful rest of the day,
Tomas
