### ISSUE TITLE
how to create multiple trees

### ISSUE THREAD

**Issue by leafjungle** [spotify/annoy#234]
As far as I know, Annoy tree is created by K-means(K=2).   In this way, we can only create one tree, then how the multiple trees are created in annoy?

**Comment by erikbern** [comment]
just pass a number to the `build` method, eg. `build(40)` and it will build 40 trees

**Comment by leafjungle** [comment]
@erikbern , I mean, how the trees are created inside, not the API.

**Comment by erikbern** [comment]
https://github.com/spotify/annoy/blob/master/src/annoylib.h#L523
