### ISSUE TITLE
Python crashes when loading large index on windows

### ISSUE THREAD

**Issue by hanabi1224** [spotify/annoy#250]
Python crashes when loading large index (both 10g one and a 20g one), but works fine with a 100m test index.

Environment: 
windows server 2016
miniconda python 3.6
annoy 1.10.0
vcbuildtools 2015

**Comment by erikbern** [comment]
probably some 32 bit limitation in windows

**Comment by hanabi1224** [comment]
@erikbern thanks for your response, is there plan to fix this in next release?

**Comment by erikbern** [comment]
annoy doesn't have a plan, it's an open source project i'm working on for fun :)

feel free to try to solve the issue and submit a pull request if you have a solution!

**Comment by tjrileywisc** [comment]
@hanabi1224 Does '10g' mean 10 gigabytes or something else?

**Comment by erikbern** [comment]
I wouldn't be surprised if the limit on Windows is 1GB or 2GB dues to 32 bit issues

**Comment by tjrileywisc** [comment]
@hanabi1224 I saw a Python crash trying to build an index with 100 trees of 10 million 100-d vectors, so I didn't even quite get to the loading part. Did you create your index elsewhere?

**Comment by tjrileywisc** [comment]
Though I think I am probably just coming up against the memory limits of my laptop in that case (I think I used up all 16 GB).

**Comment by hanabi1224** [comment]
@erikbern  FYI, I tried to create a rust-lang(whose tool chain is more windows friendly) port of index serving part of annoy and it works fine on windows with those large indices, I plan to add some compatible c apis for FFI as well

https://github.com/hanabi1224/RuAnnoy

**Comment by erikbern** [comment]
cool!

**Comment by SeanU** [comment]
FWIW, Windows does limit 32-bit processes to 2GB.  64-bit processes should be allowed all they can eat. (Though I've only ever worked in .NET and Java on Windows, so there may be some extra hoops processes have to jump through that the VMs are smoothing over.) 

Anaconda and Miniconda have both 32-bit and 64-bit distributions on Windows, so I'd think the first thing to check, if it hasn't already, is which of those is installed.
