### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [spotify/annoy#251]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like [in the function “py_an_dealloc”](https://github.com/spotify/annoy/blob/bc956daac7d3c662e9dacef958bc7faea90f8220/src/annoymodule.cc#L153 "Update candidate").

**Comment by erikbern** [comment]
ok want to create a pull request instead?

**Comment by elfring** [comment]
No. - Are you quicker to integrate such a tiny adjustment?

**Comment by erikbern** [comment]
lol that's pretty lazy but whatever guess i'll do it...
