### ISSUE TITLE
Segmentation fault when doing add_item

### ISSUE THREAD

**Issue by calz1** [spotify/annoy#254]
I am pulling data from a DB, cleaning it up and one-hot encoding out the dimensions of the vector with Pandas, and then iterating through it to call add_items on each item. Unfortunately, the first item gives me a seg fault. I printed out the values to show I'm trying to pass in an int for the index ('oid__id') and a list for the search vector ('one_list'). 

Any ideas?

```

from annoy import AnnoyIndex
import random
import boto3
import pandas as pd

....

f = df.shape[1] - 1 #get the number of columns minus the index
print(f)
t = AnnoyIndex(f)  # start building the index and pass in the width

df['one_list'] = df.ix[:, df.columns != 'oid__id'].values.tolist()
print('about to start adding items')
for index, row in df.iterrows():
    print (row['one_list'])
    print(len(row['one_list']))
    print(type(['one_list']))
    print(row['oid__id'])
    print(type(row['oid__id']))
    t.add_item(row['oid__id'], row['one_list']) #add this item to the index

```

which gives....

> 
> (indexenv) [ec2-user@ip-**** ~]$ python3 buildindex.py
> f is: 121
> about to start adding items
> [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0]
> 121
> <class 'list'>
> 1339272185
> <class 'int'>
> Segmentation fault
> (indexenv) [ec2-user@ip-**** ~]$
>

**Comment by calz1** [comment]
I think I figured it out:

>  it assumes your items are numbered 0 … n-1. If you need other id's, you will have to keep track of a map yourself.

**Comment by erikbern** [comment]
yeah the id is so large that annoy will try to allocate a ton of memory and it probably fails doing so

**Comment by a1k0n** [comment]
By using id 1339272185 as your first insertion, you are allocating 1339272185 * 4 * 121 bytes of memory (0.6TB).

Annoy isn't a key-value store; you will need to enumerate your items and add them with ids 0, 1, 2, ... and store the mapping to your underlying ids (e.g. 1339272185) separately.
