### ISSUE TITLE
Save and Load not work

### ISSUE THREAD

**Issue by lidaweironaldo** [spotify/annoy#256]
Hi,

I tried to save an index of 1000 binary vectors. The saved size is very small. When loaded, the get_n_items() function only returns 8.

Thanks

**Comment by erikbern** [comment]
source code?

**Comment by lidaweironaldo** [comment]
`
from annoy import AnnoyIndex
f=64
i = AnnoyIndex(f, 'hamming')
imct = 0

for img in imgList:                #imgList is a list of 1000 images
        fet = getFeature(img)  #getFeature returns 64-dim vector of binary values
        i.add_item(imct, fet)
        imct+=1

i.build(10)
i.save('img_index.ann')
print i.get_n_items()
`

**Comment by erikbern** [comment]
wonder if the issue is this line: https://github.com/spotify/annoy/blob/master/src/annoylib.h#L589

looks like `load()` actually might overwrite `_n_items` to the wrong value

**Comment by lidaweironaldo** [comment]
I made a mistake. When loading, I declared u = AnnoyIndex(f) which should be u = AnnoyIndex(f, 'hamming')

**Comment by erikbern** [comment]
oh yeah, that's a classic one. should probably try to catch it
