### ISSUE TITLE
A way to exclude points from result?

### ISSUE THREAD

**Issue by mkoske** [spotify/annoy#258]
Hello,

is there a way to exclude points from the result? I mean if I query one nearest neighbor for my starting point and make it starting point and repeat, I just get these two points alternating.

Thanks!

**Comment by mkoske** [comment]
And well, my usecase is that I try to implement algorithm which requires traversing through the dataset by going from a point to it's nearest neighbor and recording it's class label. I thought to experiment with a-nn instead of exact nn.

**Comment by erikbern** [comment]
there's no way to do it, but you can just filter the results?
