### ISSUE TITLE
Hamming distance and euclidean distance not return the same thing with boolean query vector

### ISSUE THREAD

**Issue by hoanganh928** [spotify/annoy#259]
[test.zip](https://github.com/spotify/annoy/files/1585540/test.zip)

Hi! I'm trying to use hamming distance as the metric to improve the query speed. I attached my dataset that contains boolean arrays and a binary query vector. The dataset is used to test both euclidean and hamming annoy. When using the same query vector, get_nns_by_vector in the euclidean metric returns first 3 items with distance 0,  while it didn't return the same thing when using the hamming metric.
```
from annoy import AnnoyIndex
import numpy as np

import pandas as pd
df=pd.read_csv('data.csv', sep=',',header=None)
array=df.values
#remove first index column
array=np.delete(array,np.s_[0],1)

array=np.asarray(array,dtype=bool)

euclidean_annoy=AnnoyIndex(1056,metric='euclidean')
hamming_annoy=AnnoyIndex(1056,metric='hamming')

for i in range(len(array)):
    item=array[i]

    euclidean_annoy.add_item(i,item)
    hamming_annoy.add_item(i,item)

euclidean_annoy.build(50)
hamming_annoy.build(50)

df=pd.read_csv('test.csv')
vector=df.values
#remove first index column
vector=np.delete(vector,np.s_[0],1)

#query
indices,distances=euclidean_annoy.get_nns_by_vector(vector,10,include_distances=True)

print(indices)
#[29, 42, 1465, 273, 68, 1567, 1001, 530, 94, 1613]
print(distances)
# [0.0, 0.0, 0.0, 14.491376876831055, 15.65247631072998, 15.65247631072998, 15.937376976013184, 16.031219482421875, 16.093477249145508, 16.093477249145508]

#query
indices,distances=hamming_annoy.get_nns_by_vector(vector,10,include_distances=True)

print(indices)
# [273, 1567, 530, 1246, 542, 1984, 1994, 2064, 760, 139]
print(distances)
# [210.0, 245.0, 257.0, 263.0, 276.0, 276.0, 276.0, 287.0, 296.0, 311.0]
```
However, when I reduce the size of dataset to 500, the results are the same:
add
`array=array[:500]`
before
`euclidean_annoy=AnnoyIndex(1056,metric='euclidean')
hamming_annoy=AnnoyIndex(1056,metric='hamming')`

`
indices,distances=euclidean_annoy.get_nns_by_vector(vector,10,include_distances=True)
print(indices)
print(distances)

indices,distances=hamming_annoy.get_nns_by_vector(vector,10,include_distances=True)

print(indices)
print(distances)
`
output:

> 
[29, 42, 273, 68, 94, 142, 96, 101, 389, 139]
[0.0, 0.0, 14.491376876831055, 15.65247631072998, 16.093477249145508, 16.733200073242188, 16.881942749023438, 17.17556381225586, 17.464248657226562, 17.63519287109375]
[29, 42, 273, 68, 94, 142, 96, 101, 389, 139]
[0.0, 0.0, 210.0, 245.0, 259.0, 280.0, 285.0, 295.0, 305.0, 311.0]
Can you help to check this out?

**Comment by erikbern** [comment]
The A in Annoy stands for “approximate”. Try to increase the value of search_k in get_nns_by_vector and see if the problem goes away. If not, please reopen this issue!
