### ISSUE TITLE
how do I get the cosine similarity?  if I use f=400 ,t = AnnoyIndex(f,metric='angular'), after I build it, I use print u.get_nns_by_item(1,250,search_k=-1,include_distances=True),how can I get the cosine similarity?

### ISSUE THREAD

**Issue by sarahyq** [spotify/annoy#264]

**Comment by erikbern** [comment]
See README.md

"Annoy uses Euclidean distance of normalized vectors for its angular distance, which for two vectors u,v is equal to sqrt(2(1-cos(u,v)))"

so you can figure out the cosine similarity through that
