### ISSUE TITLE
memory allocation based on assumed number of items as function of max(id)

### ISSUE THREAD

**Issue by mazorigal** [spotify/annoy#267]
Hi,

from the docs:
"""
Right now it only accepts integers as identifiers for items. Note that it will allocate memory for max(id)+1 items because it assumes your items are numbered 0 … n-1. If you need other id's, you will have to keep track of a map yourself.
"""

It still would be nice if there would be an option to provide the max num of items to be indexed as parameter, rather than just using max(id) +1 as default.
In cases when 1 process build the index file, and other process use it, its quite challenging to maintain the mapping between the original item id and the one used for the indexing.

Thanks,

**Comment by erikbern** [comment]
Hi @mazorigal – I'm confused what you mean. Do you still want to use consecutive integer ids? in that case, Annoy should be fine.

Is it that you want to allocate extra empty memory at the end of the index?

**Comment by mazorigal** [comment]
in my case the ids are integers, but those are items ids and for example an item id could be 256020837, which according to the logic of max(id), annoy would allocate memory for 256020838 items, whereas in reality I have only 2M items.
As a result I get memory errors.

**Comment by erikbern** [comment]
Got it. No, you have to maintain that mapping yourself, unfortunately. Same thing applies if you're using strings as identifiers or anything else. Going to close this, Annoy has no plans to offer support for this
