### ISSUE TITLE
CRUD support

### ISSUE THREAD

**Issue by mskimm** [spotify/annoy#268]
As mentioned in README, annoy builds static index then searches neighbors using it. This library is super efficient that can be employed in the production such as searching all-pairs similarity search.

The static index has many advantages but for some applications(eg, items are changed rapidly) this library is not fit.

Do you have a plan to solve this problem by eliminating this assumption?

If annoy supports various storage options (not only static file but also key-value storage), this library will be much powerful.

The basic idea is summarized as follows.

 - C (add_item)
   - as-is: allocating memory, then add it, not indexed before building the index again. 
   - to-be: adding it to storage, then add it leaves of the prebuilt index. It is possible because node size is variable.
 - R(search nns) 
    - as-is: search all candidates
    - to-be: same, but except empty items (which were deleted)
 - U: del_item then add_item
 - D (del_item)
   - as-is: does not exist
   - to-be: deleting it from storage. while searching nns, dealing it.

I think a single tree is built in background regularly, and removing old trees from the index, CRUD will work properly.

**Comment by erikbern** [comment]
Sorry, there are no plans to support this atm. If I did it, it would probably be as a completely new library, but unfortunately I have way too much going on for that to be realistic :)

**Comment by erikbern** [comment]
I think it's a great idea though! Think you can probably build something on top of eg http://www.lmdb.tech/doc/

Just nothing I personally have time for right now :(

**Comment by mskimm** [comment]
I think it is not impossible. A simple idea is using Storage abstraction as

```
template<typename S, typename T, typename Distance, typename Random, typename Storage>
  class AnnoyIndex : public AnnoyIndexInterface<S, T> {
  ...
  Storage::Storage<S, T> _storage;
  ... 

  void add_item(S item, const T* w) {
    _storage.add_item
  }
}

struct FooStorage {
  template<typename S, typename T>
  class Storage  {
  public:
    void add_item(S item, const T *v, size_t f) {
    ...
    }
    ....
  }
}
```

AnnoyIndex, as-is, has both storage and indexing operations together. My suggestion is splitting them using the abstraction. If the storage does not support one of CRUD, It can be handled using flags. For example, MMapStorage supports only R, so the boolean variable R is only true (others false).

**Comment by erikbern** [comment]
It's definitely possible, and if you're interested, I would definitely encourage you to implement it!

**Comment by mskimm** [comment]
Please check my proposal.

**Comment by erikbern** [comment]
The split looks good, but how do you actually implement updates/deletions etc? I don't want to just split it up in two classes unless there's a use for it. If you have an idea of how the algorithm would work, let me know!

**Comment by mskimm** [comment]
updates/deletions on Memory/MMapStorage are hard to implement I think. So I will try it on top of [RocksDB](http://rocksdb.org) using this abstraction.

**Comment by erikbern** [comment]
nice!

**Comment by mskimm** [comment]
I’m not doing this anymore. The purpose of CRUD is to prevent rebuilding the index due to slightly changed data. I was originally solving this problem to implement CRUD, but I just changed it to rebuild the index quickly.

Anyway, please check out https://github.com/mskimm/ann4s.
