### ISSUE TITLE
Possibility to mask columns

### ISSUE THREAD

**Issue by solipsy** [spotify/annoy#270]
Hi, this is more of a feature request than an issue. Would it be possible to specify a mask when searching, so that only specified columns would be taken into account when finding nearest neighbours?
Let's say I have an index of buildings in a city, with each building being a vector with several values. Some may be transportation-related, some security-related, etc. I'd like to be able to find nearest neighbours for a group of values, without generating a separate index for them, which is of course always an option, but memory-intensive for a big city.
Thanks!

**Comment by a1k0n** [comment]
The size of the index is directly proportional to the dimensionality, with basically no padding IIRC. So 10 separate 10-dimensional indexes should be pretty close to exactly the same size as one 100-dimensional index... so what do you gain by combining them?

**Comment by a1k0n** [comment]
I guess I misread -- you still want to search along multiple axes simultaneously, so if the indexes were separate you'd have to take a union or something. I see. Hmm.

**Comment by erikbern** [comment]
sorry not sure if this makes sense to add to annoy – think it would make it hard to work with how annoy builds the tree structure in advance
