### ISSUE TITLE
The saved index size is -1

### ISSUE THREAD

**Issue by zhuang-li** [spotify/annoy#275]
I got a dataset of 10 millions vectors with 50 dimension. The sample data is like:
>7791555	0.04337627,-0.05541232,0.09155814,0.1206924,-0.09882557,0.2028447,0.06941781,0.07600611,0.05896168,-0.09729408,-0.04764846,0.1130432,0.244801,0.1444245,-0.04512952,0.01088868,0.07317201,0.2211624,0.02474523,-0.1443465,0.1069914,0.094639,0.2009279,-0.1920806,0.1234736,0.09105369,-0.111012,-0.09284879,0.1752469,0.2172582,0.2071828,-0.1586278,0.07932017,0.2078915,-0.1711483,0.210706,-0.1499997,-0.1288135,0.1925072,0.2320567,-0.06748552,-0.009952668,0.122035,-0.1285591,-0.1627748,0.1915918,-0.05911639,-0.1347029,0.231247,-0.09053998
7438617	-0.2069246,-0.2223447,-0.1436701,0.05093231,0.04109709,0.08356889,-0.1388895,0.2219809,0.1370918,-0.03127278,-0.08592196,0.08483837,-0.2005865,0.01684957,-0.2118948,-0.2227536,0.1600862,0.04242159,0.2245194,-0.2076837,0.18219,-0.03277918,0.126232,0.1655802,0.09404644,-0.06242815,-0.005144107,0.02928288,-0.1451606,-0.2034271,-0.1740863,-0.1320828,-0.1434802,0.1632066,0.03454227,-0.1960674,-0.2229871,-0.06071541,-0.03264671,0.1392136,0.1475204,-0.1154355,0.1272989,-0.02833087,-0.1142334,-0.08369788,0.1975068,0.1086942,-0.1253511,-0.1267336
8177394	-0.07901601,-0.2101091,0.1705756,-0.1833357,0.02335487,-0.1923866,-0.08657182,-0.05264037,-0.08694042,0.09466913,0.1569658,0.2156388,-0.1163768,-0.0131144,-0.1069714,0.006891567,0.1321994,0.1879444,0.07747199,-0.1639677,-0.08685502,0.2463191,0.2452128,-0.175229,-0.1207082,-0.04915787,-0.2011081,-0.00590604,-0.1793827,0.1811205,0.009143564,0.09264465,0.1064592,0.163554,0.07450651,-0.04473475,0.151949,0.1192383,0.1272702,-0.001698788,0.1392741,0.1297999,-0.03837683,0.227497,0.03836922,0.2210029,0.2243702,0.06600913,0.2009187,-0.1279135

And the index builder is 
```python
import sys,os
os.path.abspath(os.path.join(os.path.dirname(__file__), os.path.pardir))
from annoy import AnnoyIndex
import sys
import csv
import json
in_path = sys.argv[1]
out_path = sys.argv[2]
d = int(sys.argv[3])
num = int(sys.argv[4])
m = sys.argv[5]
vector_id_map_path = sys.argv[6]
t = AnnoyIndex(d, metric=m)
index_map = {}
tree_idx = 0
with open(in_path, "r") as tsvfile:
    tsvreader = csv.reader(tsvfile, delimiter="\t")
    for line in tsvreader:
        idx = line[0]        
        if idx in index_map:
            tree_idx = index_map[idx]
        else:
            index_map[idx] = tree_idx
            tree_idx+=1
        v = [float(x) for x in line[1].split(",")]
        if  len(v)!=d:
            raise ValueError('Vector Length must equal {}'.format(d))
        t.add_item(index_map[idx], v)
        
        
t.build(num) 
t.save(out_path)
print (t.get_n_items())

with open(vector_id_map_path, 'w') as fp:
    json.dump(index_map, fp)
```

The query code is like
```python
import sys,os
os.path.abspath(os.path.join(os.path.dirname(__file__), os.path.pardir))
from annoy import AnnoyIndex
import sys
import csv
import json

index_path = sys.argv[1]
query_path = sys.argv[2]
out_path = sys.argv[3]
d = int(sys.argv[4])
m = sys.argv[5]
k = int(sys.argv[6])
q_with_v = sys.argv[7] == 'true'
index_map = json.load(open(sys.argv[8]))
t = AnnoyIndex(d, metric=m)
t.load(index_path)
f_out = open(out_path, 'w')
with open(query_path, "r") as tsvfile:
    tsvreader = csv.reader(tsvfile, delimiter="\t")
    for line in tsvreader:
        if q_with_v:
            v = [float(x) for x in line]            
            if  len(v)!=d:
                raise ValueError('Vector Length must equal {}'.format(d))
            f_out.write(",".join(str(e) for e in v) + "\t" + ",".join(str(e) for e in t.get_nns_by_vector(v, k))+"\n")
        else:
            i = index_map[line[0]]
            try:
            	f_out.write(str(i) + "\t" + ",".join(str(e) for e in t.get_nns_by_item(i, k))+"\n")
            except IndexError:
            	print ("Item index "+ str(i) + " is larger than the largest item index")
f_out.close()
```
I sampled some data. When the data is small, it is fine. But when the data became 10 millions, the `t.get_n_items()` in the index builder is still right, but in the query code, it will become -1.  

Thank you in advance.

**Comment by ReneHollander** [comment]
You are probably running out of memory during build. You can try pull request #247, which allows you to build the index on disk directly instead of in RAM. See the added test case on how to use it.

**Comment by erikbern** [comment]
annoy probably needs a bit better handling of allocation errors and file operation errors

**Comment by deathlee** [comment]
@ReneHollander Thank you. I tried your code but still failed. I guess there must be something wrong with the load. But I haven't figured out why.

**Comment by erikbern** [comment]
it's possible the index got corrupted during writing

**Comment by deathlee** [comment]
@ReneHollander @erikbern Pretty weird. It involves with the decimal precision. If I use `build_on_disk`, even 5 data points of only 1 dimension can cause the size of saved index to become -1. The `build in memory` will be fine with only 10 data points but the result would be still wrong with the data points increasing. I am using 'float' and running the program on windows. I don't know whether the same question will happen on linux.

**Comment by Trollgeir** [comment]
I'm having the same problem for large datasets. 

It doesn't seem to be a memory error during build, as `get_n_items()` returns the correct n of items right after it's been built (while it's still in memory), and all the correct functions work. However if i dump the memory with `save`, I notice that a silent crash occurs in python. The mmap file seems to be the correct size though, but when loaded the index is -1.

**Comment by erikbern** [comment]
@Trollgeir can you share the code? Does it only happen for large datasets?

**Comment by Trollgeir** [comment]
I experimented a bit, and it seems like I found a threshold of a certain number of items for my dim that caused the problem.

I'm running python 3.6 on Windows 10 64bit with 16gb ram. I've also tried saving on two different disks.
In the failed attempt, the last thing I see from verbose mode before python exits is 'unloading' after it's attempting to save.

`from annoy import AnnoyIndex
import numpy as np

num_items = 1_030_000 # works (  2 087 769 KB )
num_items = 1_040_000 # fails (  2 108 127 KB )

ann = AnnoyIndex(512, metric='euclidean')
ann.verbose(True)

print("adding items..")
mu, sigma = 0, 0.3
for i in range(num_items):
    ann.add_item(i, np.random.normal(mu, sigma, 512))

print("building index..")
ann.build(1)
print("items:", ann.get_n_items())

print("attemting to save..")
ann.save('tree')

print("attempting to load index")
ann.load('tree')

print("items:", ann.get_n_items())
`

**Comment by erikbern** [comment]
yeah sounds reasonable that it would fail on windows for an index that's around 2GB since that's the limit of an unsigned integer... maybe mmap doesn't work beyond that

**Comment by Trollgeir** [comment]
Confirmed that this is a windows related issue, as I could easily run the code on linux. So in other words, annoy for large indexes on windows is unsupported due to OS constraints?

**Comment by erikbern** [comment]
yeah that's correct, but definitely feel free to try to fix it if you have any idea!

windows does some magic to mmap here, not sure how it works: https://github.com/spotify/annoy/blob/master/src/mman.h
