### ISSUE TITLE
What does Failed splitting ... message mean?

### ISSUE THREAD

**Issue by pommedeterresautee** [spotify/annoy#280]
When I build a model, I get plenty of failed splitting message in verbose mode (may be 50 per tree).
```
pass 56...
Failed splitting 4331721 items
Failed splitting 2165334 items
Failed splitting 1081272 items
Failed splitting 540317 items
Failed splitting 269701 items
Failed splitting 134534 items
Failed splitting 135167 items
Failed splitting 270616 items
Failed splitting 135014 items
Failed splitting 135602 items
Failed splitting 540955 items
Failed splitting 270387 items
Failed splitting 135102 items
Failed splitting 135285 items
Failed splitting 270568 items
Failed splitting 135259 items
Failed splitting 135309 items
Failed splitting 1084062 items
Failed splitting 541502 items
Failed splitting 270502 items
Failed splitting 135178 items
Failed splitting 135324 items
Failed splitting 271000 items
Failed splitting 135296 items
Failed splitting 135704 items
Failed splitting 542560 items
Failed splitting 270440 items
Failed splitting 134890 items
Failed splitting 135550 items
Failed splitting 272120 items
Failed splitting 135977 items
Failed splitting 136143 items
Failed splitting 2166387 items
Failed splitting 1082902 items
Failed splitting 541122 items
Failed splitting 270557 items
Failed splitting 135099 items
Failed splitting 135458 items
Failed splitting 270565 items
Failed splitting 135015 items
Failed splitting 135550 items
Failed splitting 541780 items
Failed splitting 270863 items
Failed splitting 135360 items
Failed splitting 135503 items
Failed splitting 270917 items
Failed splitting 135326 items
Failed splitting 135591 items
Failed splitting 1083485 items
Failed splitting 539910 items
Failed splitting 269548 items
Failed splitting 134505 items
Failed splitting 135043 items
Failed splitting 270362 items
Failed splitting 134798 items
Failed splitting 135564 items
Failed splitting 543575 items
Failed splitting 271303 items
Failed splitting 135558 items
Failed splitting 135745 items
Failed splitting 272272 items
Failed splitting 135972 items
Failed splitting 136300 items
pass 57...
Failed splitting 4331721 items
Failed splitting 2165838 items
Failed splitting 1082226 items
Failed splitting 540914 items
Failed splitting 270159 items
Failed splitting 134759 items
Failed splitting 135400 items
Failed splitting 270755 items
...
...
```

It seems that the points are put in a random place:
https://github.com/spotify/annoy/blob/042fcb4129c97d6b922e8d414c1f1a55849e0c0b/src/annoylib.h#L798

**is my understanding of the meaning of the message correct?**

The final model has not very good perf with 200 trees and k set to -1.
I don't find 3/4 of the points.
When I increase k to the size of the dataset (meaning exhaustive search) I find everything, but of course, it is super slow.

My guess is that I am not supposed to get that many of these error/warning messages.

Data I put in the model are embeddings of sentences (200 dim), and I have slightly more than 4 millions of them.
Looking at ann-benchmark project, my feeling is that if it works well with Glove it should work well with my own embeddings.

Do you have an idea why I get so much of these messages?
What is their real meaning?
Is there something big I am missing?

**Comment by erikbern** [comment]
Yes – it's correct that when Annoy fails to split, it puts them in a random subtree.

It's hard to say why it fails to split but typically it means that the point set is degenerate in some way.  For instance many duplicates. It's quite rare actually – I haven't seen it for any real world applications for a very long time.

**Comment by pommedeterresautee** [comment]
What I am not sure to understand is the numbers in the error message. It's the number of vectors it fails to put somewhere?

Are the quantities shown in error message expected for 4 millions vectors and 200 trees?

For what it worth I am using rcppannoy.

**Comment by erikbern** [comment]
> What I am not sure to understand is the numbers in the error message. It's the number of vectors it fails to put somewhere?

Yes, exactly. Look at the `make_tree` function in `annoylib.h`

> 
> Are the quantities shown in error message expected for 4 millions vectors and 200 trees?

No. I would assume you have some kind of weird data distribution with lots of duplicates or something similar. But it's hard for me to know without knowing your data. Can you tell me a bit about your input data?

**Comment by pommedeterresautee** [comment]
Thanks for the pointer.
It was due to duplicates. I was not aware it may cause this issue.
May be you want to add in the error message that a cause of this issue may be related to the existence of duplicated vectors in the dataset? It may help others to debug... 

I let you clause the issue (in case you want to keep it open until the error message is updated)

**Comment by erikbern** [comment]
yeah might make sense... i'll think of something. thanks for verifying that it was due to duplicates!
