### ISSUE TITLE
Large dataset

### ISSUE THREAD

**Issue by sctrueew** [spotify/annoy#287]
Hello, I have a large dataset.I want to build an index once and then add an item to the Index.
what should I do?

**Comment by zpmmehrdad** [comment]
So, what do you do for Spotify?

**Comment by erikbern** [comment]
Spotify builds the index from scratch every time :)

**Comment by zpmmehrdad** [comment]
I have 50,000,000 items.means, I have to build from scratch every time?
How long does it take?

**Comment by erikbern** [comment]
Maybe you can split it up in several indexes so you don't have to rebuild all of it

Also 50M probably won't fit in RAM? So will be very slow
