### ISSUE TITLE
Windows Build error: INCLUDE environment variable is empty

### ISSUE THREAD

**Issue by chinmayrane** [spotify/annoy#290]
Trying to build on windows 7 with Python 3.4.4
And Miniconda Installation.
Tried using compiler=mingw32, still get the below Error.

![image](https://user-images.githubusercontent.com/1128508/38568103-720d1b14-3cad-11e8-9738-2898784ecbde.png)

INSTALLED VERSIONS
------------------
commit: None
python: 3.4.4.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 45 Stepping 7, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

What INCLUDE Environment Variable should have?

**Comment by erikbern** [comment]
weird, no idea.

i might publish wheels for windows soon, stay tuned :)

**Comment by chinmayrane** [comment]
@erikbern That sounds great! Thanks a ton! Look forward to the wheel files.

**Comment by chinmayrane** [comment]
It might be an issue with Python3.4
I upgraded to 3.5/3.6 and annoy could be built/installed.

Thanks for the Library @erikbern !
