### ISSUE TITLE
Using annoy inside an iOS app

### ISSUE THREAD

**Issue by Aashit-Sharma** [spotify/annoy#291]
# Question 
Is it possible to call annoy functions inside an iOS environment or do we need to do some sort of cross-compilation ? ( Like we need to do for FAISS)

**Comment by erikbern** [comment]
pretty sure it will work!

**Comment by Aashit-Sharma** [comment]
@erikbern Thanks! 
btw your ann_benchmarks are super helpful. Thanks for that too :+1:
