### ISSUE TITLE
More insight on the search_k parameter

### ISSUE THREAD

**Issue by chaitjo** [spotify/annoy#292]
Since the documentation doesn't really tell someone who is unfamiliar with the underlying techniques used, what are the ways to tune search_k vs number of tress?

I'm currently using annoy to do FANN and have mainly used the number of trees parameter to tradeoff accuracy vs time. I've been keeping search_k = -1 and am not sure how to select/experiment with this.

**Comment by erikbern** [comment]
for a fixed search_k: more trees is always better, up until the point where you run out of memory on your computer

for a fixed number of trees: a higher search_k means higher accuracy but at the cost of slower search time

basically pick as large of a n_trees as you can afford, and then pick search_k to be a good tradeoff between accuracy and speed

**Comment by chaitjo** [comment]
Thank you for the insight! If I understand correctly:
- search_k corresponds to some sort of split/thresholding on the k branches of the n_trees trees that were constructed, and can take values between 1 to n * n_trees, where n is the number of nearest neighbors to fetch
- search_k = -1 corresponds to search_k = n * n_trees (i.e. maximizing accuracy)

Am I correct?

**Comment by erikbern** [comment]
> Thank you for the insight! If I understand correctly:
> 
> search_k corresponds to some sort of split/thresholding on the k branches of the n_trees trees that were constructed, and can take values between 1 to n * n_trees, where n is the number of nearest neighbors to fetch
> search_k = -1 corresponds to search_k = n * n_trees (i.e. maximizing accuracy)
> Am I correct?

No – search_k is just the number of total nodes that will be searched. If you have say 1ms to spend searching, set search_k to eg 10-100k.
