### ISSUE TITLE
may be some error in master branch

### ISSUE THREAD

**Issue by nevergiveuphe** [spotify/annoy#294]
i run c++ version precision_test. but get error
![image](https://user-images.githubusercontent.com/11487479/39187440-f08ac2b8-47ff-11e8-9226-659fc2c575fc.png)

**Comment by nevergiveuphe** [comment]
gdb detail
![image](https://user-images.githubusercontent.com/11487479/39187589-49bb25b2-4800-11e8-98ae-0f2e486ad3c5.png)

**Comment by erikbern** [comment]
Can you share code example?

Closing this until then!

**Comment by a1k0n** [comment]
I think he means this? https://github.com/spotify/annoy/blob/master/examples/precision_test.cpp

**Comment by erikbern** [comment]
Ok got it. I'll see if I can repro. Should probably run those as a part of the CI build.
