### ISSUE TITLE
Can't import in Python 3.5 and 3.6

### ISSUE THREAD

**Issue by bermeitinger-b** [spotify/annoy#296]
I have created a new virtual env for the Python versions 3.6.5 and 3.5.5 built locally and installed by pyenv. My system is Fedora 28 64bit, gcc 8.0.1.

I installed Annoy with `pip install annoy` inside each environment. (Currently version 1.11.5)
Immediately after import annoy (`python -c "import annoy"`), I receive the following ImportError:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "env/lib/python3.6/site-packages/annoy/__init__.py", line 16, in <module>
    from .annoylib import Annoy as AnnoyIndex
ImportError: env/lib/python3.6/site-packages/annoy/annoylib.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTVN10__cxxabiv117__class_type_info
```
The same error appears for Python 3.5 (of course with /python3.5/ in the path)

This does not happen on a Python 2.7.14.

**Comment by erikbern** [comment]
what's your operating system?

this is another reason i want to build wheels at some point

**Comment by bermeitinger-b** [comment]
It is Fedora 28 in 64bit.
I tried using clang instead of gcc but either I failed in doing so, or it's the same problem.

**Comment by jhljx** [comment]
It couldn't be installed correctly on Windows 10 operating system with Python 3.5.
The error msg says it couldn't open 'unistd.h' on Windows, no such file or directory, for this file is a linux .h file.

**Comment by erikbern** [comment]
can you share full compiler output?

**Comment by bermeitinger-b** [comment]
At least for me, it is working again. Unfortunately, I do not know what changed. I'm not using Fedora anymore.

**Comment by erikbern** [comment]
I made some recent changes to fix compilation errors, it's possible it resolved it

**Comment by farazBhatti** [comment]
i have installed on windows 8 using 'pip install --user annoy' but cannot import it in python3.6. What solution resolved the problem???

**Comment by erikbern** [comment]
what error are you getting?

**Comment by farazBhatti** [comment]
Hi Erik
![annoy](https://user-images.githubusercontent.com/37732181/56658964-66200900-66b5-11e9-9b17-ce959f93d46e.png)
, error: no module 'annoy'. Although it have been successfully installed. In Python2 it works fine. So i had to to shift my code base to python2

**Comment by erikbern** [comment]
ok, not sure what's going on
