### ISSUE TITLE
Annoy model on disk seems larger than expected

### ISSUE THREAD

**Issue by funnydevnull** [spotify/annoy#302]
I'm trying to estimate the required memory for an annoy index on a set of vectors.  My vectors are length 128 and I've understood from other comments that annoy uses 32 bit vectors under the hook so I expect a vector to 0.5 kb.  However when I look at my annoy models on disk they seem to be ~4 times larger than that.  So an index with ~190k entries is taking about 380mb on disk rather than the 90mb I estimate just for the vector sizes.  While I can imagine some overhead over a pure mmaped numpy matrix, a factor of 4 seems quite large.  Is this reflected in memory usage as well (I haven't really tested yet)?

More generally I'd just like a way to estimate how many vectors of this size I could support with a given amount of RAM (e.g. 64 GB).

**Comment by erikbern** [comment]
how many trees did you add?

**Comment by funnydevnull** [comment]
100

**Comment by erikbern** [comment]
10 trees is probably enough! There’s no golden rule for number of trees, more is always better for accuracy so it really just depends on how much disk space you can afford!

**Comment by funnydevnull** [comment]
You mention disk space but does this also translate into memory usage (disk space is obviously much cheaper than memory).  IIRC annoy mmaps some data structure but is that the entire index file or only part of it?

**Comment by erikbern** [comment]
yes both disk space and RAM – the index will take up the same amount of memory in RAM once you mmap it
