### ISSUE TITLE
use of "nns.size() < search_k" prevents from searching all trees

### ISSUE THREAD

**Issue by madan-ram** [spotify/annoy#304]
Hi, I'm trying to add a function that sets a threshold on distance and only sends results less than equal to distance threshold, while doing I had few questions on below code snippets.

    ```
    std::vector<S> nns;
    while (nns.size() < search_k && !q.empty()) {
      const pair<T, S>& top = q.top();
      T d = top.first;
      S i = top.second;
      Node* nd = _get(i);
      q.pop();
      if (nd->n_descendants == 1 && i < _n_items) {
        nns.push_back(i);
      } else if (nd->n_descendants <= _K) {
        const S* dst = nd->children;
        nns.insert(nns.end(), dst, &dst[nd->n_descendants]);
      } else {
        T margin = D::margin(nd, v, _f);
        q.push(make_pair(D::pq_distance(d, margin, 1), nd->children[1]));
        q.push(make_pair(D::pq_distance(d, margin, 0), nd->children[0]));
      }
    }
```

1. This thresholding "nns.size() < search_k" prevents from searching all trees.
2. Below logic adds every node in binary tree hence without above thresholding your code as to search in every node.
  q.push(make_pair(D::pq_distance(d, margin, 1), nd->children[1]));
  q.push(make_pair(D::pq_distance(d, margin, 0), nd->children[0]));
3. Where is the logic for triming search opertaion?

**Comment by erikbern** [comment]
I'm not sure what your question is. Annoy doesn't traverse all nodes since the whole point is to avoid exhaustive search. If you need exact answers, some bruteforce method is better, like just relying on numpy.

**Comment by madan-ram** [comment]
What I mean is given n_trees =50 and n=10, this code is going to stop after nn.size()>n_trees *n=500. Hence usually it is not going to search for the approx nearest neighbor from all the trees.

**Comment by erikbern** [comment]
Yes, thanks by design
