### ISSUE TITLE
'dot' metric in PyPi

### ISSUE THREAD

**Issue by kkelk** [spotify/annoy#305]
The documentation here mentions the 'dot' metric, but the latest PyPi release doesn't yet support this. Would it be possible to perform a release so that we have easier access to this metric?

Thanks!

**Comment by erikbern** [comment]
sure – will do that later tonight. thanks for reminding me

**Comment by kkelk** [comment]
Cool, thanks for the quick response

**Comment by erikbern** [comment]
this is now done!
