### ISSUE TITLE
C++: How to use hamming distance?

### ISSUE THREAD

**Issue by Karol-G** [spotify/annoy#308]
I work with OpenCV C++ and have binary akaze feature descriptors/vectors of type uchar.
I want to calculate the distances with hamming distance because they are binary but I don't really know how to.
My current approach is:

``AnnoyIndex<int, uchar, ANNOY_NODE_ATTRIBUTE::Hamming, Kiss32Random>  matcher = AnnoyIndex<int, uchar, ANNOY_NODE_ATTRIBUTE::Hamming, Kiss32Random>(dim);``

But this seems not to work. The resulting distances are then also of type uchar and simply "/0".

**Comment by CookingCookie** [comment]
Ok I solved this problem. Just had to use int (any int works). I tried that before but I was passing the vector data to the index the wrong way. Now I am able to build an index.
But what I don't quite understand is the distance result when calling `get_nns_by_vector`. 
Why does it have to be of the same type as my vector data? 
Shouldn't it just be an int value of how many bits are different?

**Comment by erikbern** [comment]
I think it has to be int64 since we're using int64 bit count primitives right?

I suspect if you're using some other size then you might not get the correct bit counts returned correctly

FYI hamming distance is somewhat experimental and the algorithm probably isn't as good as it could be – for instance we're just doing axis-aligned splits so far. I want to do arbitrary splits at some point

**Comment by CookingCookie** [comment]
I tested with uint16_t for a small dataset (100k points) and the results were fine. Just as good as with int64_t. However when I test with larger datasets (int64_t index of 2 million points) the results are pretty bad when compared to FLANN. 

> FYI hamming distance is somewhat experimental and the algorithm probably isn't as good as it could be – for instance we're just doing axis-aligned splits so far. I want to do arbitrary splits at some point

I don't know much about ANN so this does not say anything to me^^
Is that the reason my results are bad?
