### ISSUE TITLE
Multiple definition compilation errors from mman.h on MinGW32

### ISSUE THREAD

**Issue by LTLA** [spotify/annoy#312]
Should the `mmap`, `munmap`, etc. functions in `mman.h` be `inline`d to avoid the ODR? I've been including the `annoylib.h` headers in several `*.cpp` files that are to be used to create a single shared library (in an R package via _RcppAnnoy_, see https://github.com/LTLA/BiocNeighbors) - this works fine, except on Windows where linking [fails](http://bioconductor.org/checkResults/devel/bioc-LATEST/BiocNeighbors/tokay1-install.html) due to multiple definitions of the `mm*` functions. This seems like a standard case for requiring `inline`ing in a header-only library, though I don't have a Windows machine available to confirm it's a fix.

**Comment by erikbern** [comment]
what's ODR?

not sure what's going on since there's definitely an `#ifndef` guard at the top

**Comment by LTLA** [comment]
Ah, sorry - One Definition Rule. The header guard only protects against multiple `include`s in a single translation unit (i.e., each `*.o`, in my case) but it doesn't protect against multiple definitions upon linking different units into a single library, which is the problem here. I'm no expert on this, but `inline`ing the relevant functions seems to help, presumably by forcing the functions to be be defined locally in each unit that includes the header file.

**Comment by erikbern** [comment]
sure if inlining resolves the issue, feel free to submit a pull request!
