### ISSUE TITLE
Catastrophic cancellation with Euclidean distance calculation

### ISSUE THREAD

**Issue by LTLA** [spotify/annoy#314]
The recent updates to the `Euclidean::distance` method at:

https://github.com/spotify/annoy/blob/8729dccb7b4b4a9d3283531dbe5705eb98d52296/src/annoylib.h#L449-L454

... have introduced undesirable behaviour with catastrophic cancellation when `pp`, `pq` and `qq` are all large relative to the final distance between `x` and `y`, _and_ single-precision floats are in use.

To illustrate, we can compile and run this program with the latest `annoylib.h` (as of c1342f2574da88a3433c64fc369e0c247adf16db):

```cpp
#include <cstdio>
#include "annoylib.h"
#include "kissrandom.h"

typedef float ANNOYTYPE;

typedef AnnoyIndex<int, ANNOYTYPE, Euclidean, Kiss64Random> MyAnnoyIndex;

int main() {
    MyAnnoyIndex obj(1);
    
    ANNOYTYPE first=0.7125930, second=0.7123166;
    obj.add_item(0, &first);
    obj.add_item(1, &second);

    obj.build(10);
    
    std::vector<int> stuff;
    std::vector<ANNOYTYPE> outdist;
    obj.get_nns_by_item(0, 2, -1, &stuff, &outdist);

    printf("%i %.10f\n", stuff[0], outdist[0]);
    printf("%i %.10f\n", stuff[1], outdist[1]);
    return 0;
}
```
... which prints out:
```
0 0.0000000000
1 0.0000000000
```
... which is not correct; the distance between items 0 and 1 is equal to 0.0002764. However, if we switch `Euclidean::distance` back to a more direct sum of squares calculation:

```cpp
T d = 0.0;
const T* xp=x->v, *yp=y->v;
for (int i = 0; i < f; i++, xp++, yp++) {
    T tmp=*xp - *yp;
    d += tmp*tmp;
}
return d;
```

... we get a result closer to the truth:

```
0 0.0000000000
1 0.0002764463
```

I know there's a balance between speed and accuracy, but this level of imprecision seems a step too far. I wouldn't consider the above example pathological with respect to numerical precision, yet the program is still failing. Perhaps we should revert back to the old method for computing Euclidean distances. (I suspect at least some of the other distance metrics have similar behaviour but I haven't looked at them in much detail.)

**Comment by erikbern** [comment]
this sounds too large to be attributable to rounding errors. i think there's some arithmetic issue going on.

**Comment by LTLA** [comment]
The individual `pp`, `qq` and `pq` values look fine when I `printf` them out:

```
# printf("%.10f %.10f %.10f\n", pp, qq, pq);
0.5077888370 0.5073949099 0.5075918436
```

But if you were to do the same with `pp + qq` and `2 * pq`, you'd see identical values. I assume that precision is just getting lost when `pp + qq` forms a large-ish intermediate. One could mitigate this with:

```cpp
return (pp - pq) + (qq - pq);
```

... which returns a distance of 0.0002441406... still not great, but at least it's not zero.

**Comment by erikbern** [comment]
Ok, cool. I'll see if I can reproduce this from the Python layer and if your suggestion (`(pp - pq) + (qq - pq)` rather than `pp + qq - 2*pq`) fixes the problem then I'll make that change. Unfortunately a "too smart" compiler might rewrite that line though.

Btw if you truly need precision for Annoy, consider using `double` rather than `float`

**Comment by LTLA** [comment]
If I may: is there a compelling reason to keep the current algorithm for computing the Euclidean distance? From what I can see, `Euclidean::distance` still needs at least one `dot()` call, and that `dot()` call still needs to loop over the dimensions to compute the dot product - there doesn't seem to be any magic that would make it happen super-fast. So, we will have one multiplication and one addition per iteration of the loop, not considering cases where we need multiple `dot()` calls. By comparison, the more numerically stable calculation in my post above would just have an extra subtraction (plus a stack variable). From my perspective, this seems like the time cost - if any - is well worth the extra accuracy, especially if it avoids getting a distance that's very wrong (depending on the whims of the compiler).

**Comment by erikbern** [comment]
See fix in https://github.com/spotify/annoy/pull/315

IIRC the performance benefit was actually slightly small (like maybe 5%) for using the latest distance calculation – the real benefit was I didn't have to have multiple different AVX functions to do different things, but could have a single one (`dot`) that I can use from different places

**Comment by LTLA** [comment]
Ah, I see the `dot<float>` specialization now... would you be willing to consider a `Euclidean::distance<, float>` specialization, written with AVX and using the more-precise algorithm? Similar to `manhattan_distance<float>`? I'm happy to try to write this.

**Comment by erikbern** [comment]
> Ah, I see the `dot<float>` specialization now... would you be willing to consider a `Euclidean::distance<, float>` specialization, written with AVX and using the more-precise algorithm? Similar to `manhattan_distance<float>`? I'm happy to try to write this.

Seems like a bit too much work tbh. Let's merge #315?

**Comment by LTLA** [comment]
I guess I saw this too late, I went ahead and did it before lunch. Well, it's in #316 if it's ever needed.
