### ISSUE TITLE
C++ Build tree waste much memory, if ids are discontinuous

### ISSUE THREAD

**Issue by yuadsl3010** [spotify/annoy#321]
I have a large id list which is not discontinuous
```
annoy_index.add_item(1, f_1);
annoy_index.add_item(2, f_2);
annoy_index.add_item(10001, f_3);
annoy_index.add_item(10002, f_4);
annoy_index.build(40);
annoy_index.save("annoy_tree");
```
then I found index file becomes huge, because in _allocate_size() at annoylib.h
every time realloc depends index pass by add_item(index, feature)

and it's weired to store a mapping of id and index, so I modify add_item(index, feature) to add_item(index, id, feature), that could cause some compatibility problem but for me it works

[annoylib.zip](https://github.com/spotify/annoy/files/2513187/annoylib.zip)

**Comment by erikbern** [comment]
if you have highly discontinuous ids, you will have to maintain a mapping yourself. same thing if your data types are non-ints
