### ISSUE TITLE
data with longitude and latitude 

### ISSUE THREAD

**Issue by Jarlonyan** [spotify/annoy#326]
my data format is longitude and latitude, just like this:
id1, 36.23, 102.56
id2, 32.11, 112.16
id2, 31.89, 111.56
id4, 30.22, 112.61

but I cannot use "angular", "euclidean", "manhattan", "hamming", or "dot for distance metric.
what should I do?

**Comment by erikbern** [comment]
you can convert it to 3d-coordinates and use those instead

see https://github.com/erikbern/ping/blob/master/plot.py#L11 for instance

**Comment by Jarlonyan** [comment]
thank you!
