### ISSUE TITLE
Virtual File System

### ISSUE THREAD

**Issue by AjayP13** [spotify/annoy#328]
Hi Erik,

I built [Magnitude](https://github.com/plasticityai/magnitude/) which makes use of your `annoy`. Thanks again for working on this awesome library.  I'm currently implementing a feature that will stream  vectors over static HTTP server (like Amazon S3) using [HTTP Byte-Range Headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests) so the large multi-gigabyte files don't have to take up disk space on the computer / server.

I would love to be able to stream the `annoy` memory mapped file as well, so you wouldn't need a 2-3GB gigabyte file on your computer, but could keep the file on a CDN server and stream the approximate similarity search results on-demand.

I would need to add a "virtual file system" option to `annoy`, where instead of taking a file name in the `load()` function, it takes virtual file size of virtual file and a pointer to a read-from-virtual-file function.

The small changes when the `virtual` option is enabled on the `load()` function :
1. [Set the `size` variable](https://github.com/spotify/annoy/blob/70219cdf9a509c4972b0ae6b08dfd1fb9b9945ce/src/annoylib.h#L874) to the virtual file size the user provided in the `load()` function.
2. Don't [`mmap` to `_nodes`](https://github.com/spotify/annoy/blob/70219cdf9a509c4972b0ae6b08dfd1fb9b9945ce/src/annoylib.h#L877). `_nodes` will not be used when `virtual` is on.
2. Use the read-from-virtual-file function the user provided in the `load()` function to [return a result from `get_node_ptr`](https://github.com/spotify/annoy/blob/70219cdf9a509c4972b0ae6b08dfd1fb9b9945ce/src/annoylib.h#L109) at `offset = _s * i` and `size = _s`. Cast the bytes the read-from-virtual-file function returns to a `Node*`.

I think the diff would be fairly small and I'd be willing to implement it and document it and the library would still work the same if the `virtual` flag was turn off (off by default). 

Let me know if you would be open to a PR for this. If you don't want it in the project I totally understand, but I think it would be really nice to be able to stream these large files from other places than the filesystem, like the network, by adding this `virtual` option. I can fork a version of `annoy` into the Magnitude project in any case.

Thanks!

**Comment by erikbern** [comment]
Interesting but I'm somewhat skeptical of this since I suspect it would be incredibly slow to do this. Have you tried?

**Comment by AjayP13** [comment]
Yeah, I have done it on the Magnitude SQLite file already (SQLite has a Virtual File System implementation built in) and it worked surprisingly well if you add in a small predictor for sequential reads and a local cache for repeated reads in the same region. It basically let you run query large SQLite queries over static HTTP using the range headers. It really depends on its read patterns and how much data is read from the file

I'll give it a shot on `annoy` and submit a PR in that case, and you can decide whether its worth adding.
