### ISSUE TITLE
Is the annoy index thread safe ?

### ISSUE THREAD

**Issue by perone** [spotify/annoy#332]
Thanks for the nice library ! I've a question regarding the C++ API, is the `AnnoyIndex` method `get_nns_by_vector` thread safe or is there any global state being write, etc ? I want to query the same index from multiple threads. I don't need to create the index from multiple threads but I want to query it.

**Comment by erikbern** [comment]
yeah should be fine – it's a const method iirc so there's no shared state

**Comment by perone** [comment]
Thanks @erikbern !
