### ISSUE TITLE
Bus error in get_nns_by_vector

### ISSUE THREAD

**Issue by mxgr7** [spotify/annoy#335]
We are seeing bus errors in production from time to time when calling `get_nns_by_vector`. The process crashes with SIGBUS. We are stuck because we can't answer the following questions:

1. We are not able to reproduce it in a development environment because we have no idea what could be causing it. Are there any obvious scenarios that would explain the SIGBUS?
2. The core dumps from production don't help us either because we can't get gdb to use the correct symbols and show us function names etc. Is there a way to get that to work without running a debug version of Python in production?

Some more context: 
* We are running two processes, both loading the same index files from disk into memory. 
* After the initial loading at startup, one of them becomes the "query" process which handles incoming requests by searching the loaded indices. 
* The other becomes the "fetch" process which monitors the file system for changes to index files and reloads any changed index. 
* Once the fetch process finishes reloading an index, the roles reverse and it becomes the "query" process while the other becomes the "fetch" process.
* These two processes are started from a main process which runs Flask and which is in turn started by uwsgi inside a docker container. uwsgi is configured to use a single process and a single thread.

At this point we are running out of ideas and any pointers on what to look at would be greatly appreciated.

**Comment by erikbern** [comment]
Interesting. No idea what's going on.

> The other becomes the "fetch" process which monitors the file system for changes to index files and reloads any changed index.

This seems fishy. I'm not sure what happens if you mmap a file and then the file changes. I wouldn't be surprised if it leads to complications. Might make more sense to create a new file, but never modify existing files.

> Once the fetch process finishes reloading an index

How do you reload the index? Again, a bit nervous about reloading. You should probably just create a new index and load a new file from scratch.

**Comment by mxgr7** [comment]
Thank you!

> I'm not sure what happens if you mmap a file and then the file changes.

We had not considered that, but you raise a valid point! If this actually causes problems it could explain the observed failures. Will investigate further.

> How do you reload the index?

We initialize a new `AnnoyIndex` object and call `.load()` to read the file from disk.

**Comment by erikbern** [comment]
> Will investigate further.

nice, let me know what you find!

> We initialize a new `AnnoyIndex` object and call `.load()` to read the file from disk.

Ok, this should be fine.

**Comment by erikbern** [comment]
https://stackoverflow.com/questions/12383900/does-mmap-really-copy-data-to-the-memory

You might definitely get issues if you modify existing files. However the way the Linux kernel works (IIRC) is if you delete the file and create a new one with the same filename, that's considered a different file.

**Comment by mxgr7** [comment]
We actually write the new index to a temporary file and upon completion move it to replace the old one. Not sure if that is problematic.

**Comment by erikbern** [comment]
> We actually write the new index to a temporary file and upon completion move it to replace the old one. Not sure if that is problematic.

That should be fine actually. That would be considered a different file by the kernel so there should be no conflict.

However maybe the issue is that the previous underlying file is _deleted_? not sure what the behavior is for mmap in that case

**Comment by erikbern** [comment]
According to https://stackoverflow.com/questions/51259706/mmap-and-file-deletion-in-macos it should be fine (at least on Mac)

Seeing comments online saying it migh tbe a problem though

**Comment by mxgr7** [comment]
We were able to trigger the error:
1. Load an index file
2. Write a new index containing _fewer_ items to the same file path
3. Call `get_nns_by_vector()` on the original loaded index
4. Get a Bus Error

```
from annoy import AnnoyIndex
import random

f = 40

# Build the initial index
t = AnnoyIndex(f)
for i in range(1000):
    v = [random.gauss(0, 1) for z in range(f)]
    t.add_item(i, v)
t.build(10)
t.save('test.ann')

# Load index file
t2 = AnnoyIndex(f)
t2.load('test.ann')

# Overwrite index file
t3 = AnnoyIndex(f)
for i in range(500):
    v = [random.gauss(0, 1) for z in range(f)]
    t3.add_item(i, v)
t3.build(10)
t3.save('test.ann')

# Get nearest neighbors
v = [random.gauss(0, 1) for z in range(f)]
nns = t2.get_nns_by_vector(v, 1000)
```

However, we were not able to reproduce this behavior when writing the new index to a different file path, then using `os.rename()` to replace the old one. It worked fine even for large index files. This is what we do in production, so we are still not 100% sure what is causing the error there. It does seem likely that it is related to the error above though. We decided to change our logic a bit so that we never touch nor replace existing index files and hope that this will solve the issue.

By the way, is there a way to catch this error in Python so that the process doesn't completely crash? We would have had a much easier time locating the error.

**Comment by erikbern** [comment]
I'm highly confused why this would fail. Just writing to the same filename shouldn't do anything with the existing file that's open – and the existing test.ann file shouldn't be deleted until all references are closed. Doesn't make any sense to me.

Unfortunately I can't think of an easy way to catch this error

**Comment by erikbern** [comment]
What OS are you on? You're on Linux right?

**Comment by erikbern** [comment]
I can reproduce the on my Mac laptop and it doesn't crash if I change `test.ann` to `test2.ann` on L24 so at least that's a good starting point.

Will see if I can figure out what's going on. This is highly confusing.

@a1k0n feels like you might have any good ideas about how mmap would behave if the underlying file is deleted?

**Comment by a1k0n** [comment]
If the underlying file is deleted (unlinked), then the contents of the file are actually preserved on the filesystem until all handles to the file are closed. So it's completely safe to do that, and any existing references to the file will continue on as if nothing happened in the background.

If the underlying file is *overwritten* (recreated with O_TRUNC), then the contents of the file are replaced and the length of the file becomes 0, then however big it's rewritten to. The mmap region becomes invalid, hence the SIGBUS -- references within the file point outside the virtual address space of the file. So when you overwrite with a smaller index, references to data outside the length of the index cause a SIGBUS; even if you overwrite with a larger index, you will end up with invalid data on the existing process.

So the upshot is if you want to safely replace an index, write to a tmp location, unlink the old one, then rename the new one into place. Existing references to the old one will be none the wiser until they reload.

**Comment by erikbern** [comment]
> f the underlying file is _overwritten_ (recreated with O_TRUNC), then the contents of the file are replaced and the length of the file becomes 0, then however big it's rewritten to

Oh wow, this is super interesting. I thought overwriting generally is the same thing as creating a new file.

It seems like `fopen` on https://github.com/spotify/annoy/blob/master/src/annoylib.h#L835 really runs an open under the hood with `O_TRUNC` set. I wonder if I can replace the `fopen` call with an `open` call without `O_TRUNC`

(this seems like kind of marginal value from a user value, but thought it was interesting so why not fix it)

**Comment by erikbern** [comment]
actually probably what i want to do is to check if the file exists and delete it prior to the `fopen` call

**Comment by erikbern** [comment]
See #339 – turns out the fix is a one liner
