### ISSUE TITLE
Faster search face in base with more than 1 million images.

### ISSUE THREAD

**Issue by psyapathy** [spotify/annoy#336]
Hello!

I use for face recognition python library https://github.com/ageitgey/face_recognition
I want to faster to find 1 face in more than 1 million faces.

Face recognition give me a encodings (a list of 128 real-valued numbers) for each images.

Can i faster find 1 face in more than 1M faces with Annoy? Find similar with distance?
How store 1M dataset (or encodings) for this?

Thank you

**Comment by erikbern** [comment]
Yes sounds like the use case it’s built for!

**Comment by Andtheworld** [comment]
@arpsyapathy Were you able able to solve the problem using annoy?
