### ISSUE TITLE
Information Retrieval Closest Senence

### ISSUE THREAD

**Issue by bamba518** [spotify/annoy#346]
Came to this git from this post
https://www.quora.com/How-can-I-use-sentence-similarity-in-information-retrieval-task

Basically, if I have a list of 100,000 sentences, how would I find the closest sentence in that list to a given sentence

**Comment by erikbern** [comment]
You'd have to use some method to project the sentences to vectors, but then you could def use Annoy to look up similar sentences

**Comment by danieliversen** [comment]
And here's one example of how to do that: https://github.com/vineetm/tf-similar-sentences
