### ISSUE TITLE
Redis support

### ISSUE THREAD

**Issue by changzeng** [spotify/annoy#347]
Does this package support redis storage?

**Comment by erikbern** [comment]
No :(

**Comment by erikbern** [comment]
Wouldn't be a bad idea to build a nearest neighbor library on top of Redis though. But quite different scope.

**Comment by changzeng** [comment]
Build a nearest neighbor library on top of Redis will allow the package to handle a wider scale of data.

**Comment by H3zi** [comment]
FYI https://github.com/RedisAI/VectorSimilarity
