### ISSUE TITLE
on_disk_build bug

### ISSUE THREAD

**Issue by Slikus** [spotify/annoy#353]
```
from annoy import AnnoyIndex

a = AnnoyIndex(4)

a.add_item(0, [0, 0, 0, 0])
a.add_item(1, [0, 0, 6, 0])
a.add_item(2, [0, 5, 0, 0])
a.add_item(3, [0, 4, 0, 0])
a.add_item(4, [0, 0, 3, 0])
a.add_item(5, [2, 2, 0, 0])
a.add_item(6, [0, 0, 0, 0])
a.add_item(7, [0, 0, 0, 0])

a.build(-1)
a.save('C:/Users/home/Desktop/test1.tree')
a.unload()


b = AnnoyIndex(4)
b.on_disk_build('C:/Users/home/Desktop/test2.tree')

b.add_item(0, [4, 0, 0, 0])
b.add_item(1, [0, 4, 0, 0])
b.add_item(2, [0, 3, 2, 0])
b.add_item(3, [0, 0, 2, 0])
b.add_item(4, [0, 0, 0, 0])
b.add_item(5, [0, 4, 2, 0])
b.add_item(6, [0, 0, 2, 0])
b.add_item(7, [0, 0, 1, 0])

b.build(-1)
b.unload()



c = AnnoyIndex(4)
c.load('C:/Users/home/Desktop/test1.tree')
print('1 length:', c.get_n_items())


d = AnnoyIndex(4)
d.load('C:/Users/home/Desktop/test2.tree')
print('2 length:', d.get_n_items())

```

output:
1 length: 8
2 length: 0

so get_nns_by_vector and etc is not works too

![image](https://user-images.githubusercontent.com/8903862/51776066-dd6eec80-2108-11e9-9b38-20ebe71b7987.png)

upd:
I deleted zeros at the end of the file (not on picture), and it worked. But there were only 3M lines in the file (50k 128D records), if the file is more than 100+ times longer I will not be able to do it. Need to fix it

**Comment by Slikus** [comment]
also if i add only 3 items (add_item) it works fine

**Comment by Slikus** [comment]
**and 1 more problem:**
if i add item with id more than ~4000000 and 128 points i got python crashing. Why? How to add 10-20-30-100M rows? Is it possible?

**Comment by erikbern** [comment]
4000000 * 128 * 4 = 2G which is the max that Windows can handle afaik

**Comment by Slikus** [comment]
> 4000000 * 128 * 4 = 2G which is the max that Windows can handle afaik

what about linux? And on_disk_build bug?

**Comment by erikbern** [comment]
yeah linux should handle >2GB

the on disk build bug is separate, i'll look at it at some point

**Comment by erikbern** [comment]
@ReneHollander actually do you know what's going on?

**Comment by ReneHollander** [comment]
Can confirm the mentioned bug under WSL, was not able to check Windows yet. I tried the latest release under native Linux und can confirm, it does not happen there.

I guess the issue has something todo with the ftruncate call to cut the unneeded memory after the build finished. This is known bug under WSL and was also mentioned in the PR #274. I am pretty sure I tested it under Windows and had it working correctly.

@Slikus, did you try it with native Windows, or did you use the WSL?

**Comment by Slikus** [comment]
@ReneHollander native windows 7 x64

**Comment by ReneHollander** [comment]
The bug does not happen on Linux and it should be able to support well over 2GB large memory maps.
Maybe check how much storage space you will need: Fully build an index with 1000000 items, then multiply the size by 100 to get to 100 million (I think you should be able to get a good approximation). Make sure to have maybe twice as much space on your harddisk (preferably SSD, I think it will take too long without), otherwise the build will fail at some point.

**Comment by ReneHollander** [comment]
@erikbern I will fix those issues and improve the things mentioned in #274 when I get to the next stage of my own project that is using annoy :)

**Comment by erikbern** [comment]
Awesome @renehollander!

**Comment by Dobatymo** [comment]
I have the same problem in Windows 10 x64, Python 3.7.2
When using `on_disk_build`, `load` doesn't load the index.

**Comment by vbod** [comment]
@Dobatymo @Slikus If you ever have the opportunity to test with the master branch, it'd be awesome to know if this PR does fix it indeed! Please tell me if it does - or not 😉

**Comment by erikbern** [comment]
Closing this for now! Will reopen if bug persists

**Comment by Dobatymo** [comment]
I didn't do extensive testing. But the few examples I tried all worked 👍
