### ISSUE TITLE
On what does the search time depend on?

### ISSUE THREAD

**Issue by CookingCookie** [spotify/annoy#354]
I set the number of trees to one and search_k at a fixed value of 400. I then build multiple indexes with different amounts of items in the index. Meaning I build an index with 100k items, one with 400k items, ... and one with 1M items. When doing test searches the accuracy for all the indexes stayed good and the search time was constant. 

I do not have so much insight on how annoy works, but when choosing a fixed search_k value, does this mean that the search time will be constant no matter the size of the index? 
If this is true, shouldn't the accuracy degrade when the index becomes to big? 

So summarized:
What is the relationship between search_k, index size, search time and accuracy?

**Comment by erikbern** [comment]
That sounds right. with a fixed search_k and varying the number of trees, it should take roughly the same time.

More trees will always yield better accuracy (but use more memory)

**Comment by CookingCookie** [comment]
When given a fixed number of trees, a fixed search_k and the index size, is there a way to roughly calculate the accuracy?
In my case for example: Even with an index size of 1M the accuracy was still good. But I would like to be able to make an assumption at what size it will drop significantly.

**Comment by erikbern** [comment]
Sorry, there's no way a priori to estimate it. Depends on the distribution of the underlying data

**Comment by txntxn** [comment]
Yes, but it would be lovely to have a function that actually determines the precision in a data-dependent way, as this parameter changes.
