### ISSUE TITLE
Calculate percentage distance from vector search

### ISSUE THREAD

**Issue by OElesin** [spotify/annoy#356]
Hello team, great work.

Is it possible to possible to calculate the percentage distance from vector search. I have built an index successfully and able to query with `get_nns_by_vector` with `include_distance=True`. 

I would like to convert the returned distance into percentages. Do you have any recommended ways of doing this?

Thanks

**Comment by erikbern** [comment]
Not sure what you mean by percentages?

**Comment by OElesin** [comment]
Thanks for the prompt response, @erikbern .

See example below:

```python
>>>> t = Annoy()
>>>> t.get_nns_by_vector(features[144], 10, search_k=1, include_distances=True)

([144, 0, 89, 8, 85, 112, 44, 37, 3, 97],
 [824.9801635742188, 798.65625, 752.6791381835938, 741.093505859375, 715.7233276367188, 705.79248046875, 698.050537109375, 697.43310546875, 694.0565185546875, 666.2744750976562])
```

Given the distances, I would like to convert the distance to percentage.

**Comment by erikbern** [comment]
ok, sorry, not clear what that means. going to close this for now
