### ISSUE TITLE
Windows 10 and Python 3.6- Not able to pip install annoy

### ISSUE THREAD

**Issue by abhi1489** [spotify/annoy#358]
I am getting the following error while trying to pip install on my machine along with a host of warnings.

 c:\users\abhishek.aigali\appdata\local\temp\pip-install-6qce79eb\annoy\src\annoylib.h(555): error C3861: '__popcnt64': identifier not found
    c:\users\abhishek.aigali\appdata\local\temp\pip-install-6qce79eb\annoy\src\annoylib.h(959): note: see reference to function template instantiation 'T Hamming::distance<S,T>(const Hamming::Node<S,T> *,const Hamming::Node<S,T> *,int)' being compiled
            with
            [
                T=uint64_t,
                S=int32_t
            ]
    c:\users\abhishek.aigali\appdata\local\temp\pip-install-6qce79eb\annoy\src\annoylib.h(958): note: while compiling class template member function 'T AnnoyIndex<int32_t,T,Hamming,Kiss64Random>::get_distance(S,S) const'
            with
            [
                T=uint64_t,
                S=int32_t
            ]
    src/annoymodule.cc(74): note: see reference to function template instantiation 'T AnnoyIndex<int32_t,T,Hamming,Kiss64Random>::get_distance(S,S) const' being compiled
            with
            [
                T=uint64_t,
                S=int32_t
            ]
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2

I have updated my visual studio 2017 build tools. The same command pip install annoy works when i run it through the Anaconda command prompt but when i copied the installed library, from
C:\Users\abhishek.aigali\AppData\Local\Continuum\anaconda3\Lib\site-packages

to:
C:\Users\abhishek.aigali\AppData\Local\Programs\Python\Python36-32\Lib\site-packages

and did -- **import annoy** i got the following error:
ModuleNotFoundError: No module named 'annoy.annoylib'

Any suggestions please?

**Comment by erikbern** [comment]
interesting – should probably define `__popcount64` if it's not defined

**Comment by abhi1489** [comment]
I have also tried to do a python setup.py install after downloading the zip file and faced the same error.I see that the identifier __popcnt64 is defined within the annoylib.h file


#ifndef _MSC_VER
#define popcount __builtin_popcountll
#elif _MSC_VER == 1500
#define isnan(x) _isnan(x)
#define popcount cole_popcount
#else
#define popcount __popcnt64
#endif

**Comment by erikbern** [comment]
looks like we should maybe have a fallback version or just implement it ourselves

i'm happy to rely on this: https://github.com/bengras/minix/blob/master/common/lib/libc/string/popcount64.c

**Comment by PattF** [comment]
I experienced the same issue, however if I specified version 1.15 in pip install, that worked for me. Just my 2 cents :)

**Comment by erikbern** [comment]
Actually looks like this is the same as #293
