### ISSUE TITLE
Jaccard distance?

### ISSUE THREAD

**Issue by gregfriedland** [spotify/annoy#360]
Hello,
Can someone advise what changes would be necessary to implement a Jaccard distance metric based on bit vectors? I saw that Hamming distance uses bit vectors so perhaps it's a relatively straightforward tweak from there... Any pointers would be appreciated.

Thanks!
Greg

**Comment by erikbern** [comment]
shouldn't be super hard to change the hamming distance to add support for jaccard, i think

note that hamming distance is somewhat experimental and might be far from optimal

closing this for now!

**Comment by jolespin** [comment]
Was this ever implemented? Jaccard distance works better for my tasks than hamming.
