### ISSUE TITLE
Angular distance between orthogonal vectors

### ISSUE THREAD

**Issue by braingineer** [spotify/annoy#363]
Hello,

I've read through some of the issues (#162 and #149 and #193) to see if it's my misunderstanding but I'm still coming up short. 

Premises:
- angular distance is computed as the euclidean distance of the 2 normalized vectors.   
- this should be equal to 2(1-cos(theta)) where theta is the angle between the two vectors 

For orthogonal vectors, theta should be 90 (pi/2), cos(theta) should be 0, the angular distance should be 2. Is this correct?  However, if you use the euclidean distance of the 2 vectors, you get the 1.41 answer shown below. 

Test script:
```
from annoy import AnnoyIndex
import numpy as np

annoy_index = AnnoyIndex(f=2, metric="angular")

vec0 = np.array([0, 1])
vec1 = np.array([1, 0])
annoy_index.add_item(i=0, vector=vec0)
annoy_index.add_item(i=1, vector=vec1)

annoy_index.build(n_trees=-1)

print(annoy_index.get_distance(0, 1)) # prints 1.4142135381698608 , the sqrt(2)
```

**Comment by erikbern** [comment]
1.41 is the square root of 2 – see https://github.com/spotify/annoy/blob/master/src/annoylib.h#L959

**Comment by erikbern** [comment]
the euclidean distance of the normalized vectors is sqrt(2)

**Comment by braingineer** [comment]
hi @erikbern 

I feel this may be prematurely closed.  The angular distance distance between 2 orthogonal vectors should not be the square root of 2. The value of cosine for 90 degrees is 0.

**Comment by erikbern** [comment]
See the readme at https://github.com/spotify/annoy

_a.get_distance(i, j) returns the distance between items i and j. NOTE: this used to return the squared distance, but has been changed as of Aug 2016._

_Annoy uses Euclidean distance of normalized vectors for its angular distance, which for two vectors u,v is equal to sqrt(2(1-cos(u,v)))_
