### ISSUE TITLE
annoy.build does not finish. Is there a limit to the items which can be added?

### ISSUE THREAD

**Issue by Paperone80** [spotify/annoy#365]
Hi,

I am on a MacBook Pro with 16GB memory. I successfully installed build annoy v1.15.0 using 
`sudo -H CC=/usr/local/bin//gcc-4.9 CPP=/usr/local/bin//cpp-4.9 CXX=/usr/local/bin//g++-4.9 pip install --upgrade annoy`

I have ~120,000 items which have dims=np.array(49152,). However, to successfully annoy.build(n_trees) I can't add more than ~48,000 items. Any number above and annoy.build() never finishes (I waited 24h+) but I can see disk activity. I tried annoy.on_disk_build() and without, no success. I tried lowering n_trees to 10 but no success. 

48,000 items with n_trees=1500 takes about 1h 27min to successfully build. 

One particularity I do though, is that I choose the number/sample of items randomly from a metadata file and are using the pandas.DataFrame.index integer as the annoy.add_item(int(idx). Not sure whether the numbers need to be a certain sequence or to start with but I understood from the documentation that it shouldn't matter as the annoy will allocate memory for max(i=idx)+1 anyway. 

Thanks in advance for all the help.

**Comment by erikbern** [comment]
49152 dimensions is extremely high. Annoy is built for a few hundred. Try doing some dinensionality reduction of your data?

Not sure why it hangs though

**Comment by Paperone80** [comment]
@erikbern, thanks for your quick reply. Yes, I might be pushing boundaries of annoy a little bit. Here is what I observed:
My tests were with 31,000 samples out of 120,000 and n_tree 1,500. Annoy loads and builds in about 24min. Retrieval of 1 index including all other indices with distances about 1min. 

48,000 builds in 1h 27min retrieval of 1 index with all other indices and distances about 5min.

48,000+1 samples and annoy.build() does not finish within 24hours. Maybe it's Macbook or Mac OS X.

Reason why I am using dims=49152 is because the vectors are images of 128x128x3 and I am retrieving all the nearest indices and respective distances to actually find the least-nearest images to understand and visualise diversity or 'opposite' images in the image set. 

Maybe annoy is not build for that but I got the 32K example working within a day and it runs superfast. 

Now, I was eager to see how the results would look like on the entire dataset...

**Comment by erikbern** [comment]
49152 * 48000 * 4 is about 9GB

Maybe what's happening is your computer runs out of RAM if you build with many trees and it has to resort to swap space. That will typically be 100-1000 times slower (depending on the disk)

Closing this for now since this seems a bit like an extreme case

**Comment by JanakaSandaruwan** [comment]
Same issue with 2M vectors of size 1024.
