### ISSUE TITLE
Can't pickle annoy.Annoy objects

### ISSUE THREAD

**Issue by Axel-CH** [spotify/annoy#367]
Hello,
I have an Issue when I try to pickle an annoy object. Here Is the code generating the exception:
`    def save_checkpoint(self, checkpoint_prefix):
        super().save_checkpoint(checkpoint_prefix)
        with open(os.path.join(self.ap.task_parameters.checkpoint_save_dir, str(checkpoint_prefix) + '.dnd'), 'wb') as f:
            pickle.dump(self.networks['main'].online_network.output_heads[0].DND, f, pickle.HIGHEST_PROTOCOL)`
This code is comming from the [nec_agent](https://github.com/NervanaSystems/coach/blob/master/rl_coach/agents/nec_agent.py) of  Intel / NervanaSystems Coach Deep reinforcement learning librarie.

I'm running that code on:

- windows 10 64bits
- Python 3.6.5
- annoy 1.15.0

Thank for the help,

**Comment by erikbern** [comment]
Annoy doesn't support pickling. Why are you trying to pickle? Just save the index to disk.

**Comment by Axel-CH** [comment]
Thank you for you help @erikbern I will do that.

**Comment by dpalbrecht** [comment]
I am trying to read my saved Annoy model from Google Cloud Storage, but the `load` method seems to require me to have a path as opposed to being able to just read the file from Storage (from a pickled object, for example). Is there a way to load my model without needing a direct path?

**Comment by erikbern** [comment]
no, you'll have to download it locally first

**Comment by dpalbrecht** [comment]
Does it work by loading in the file at any point? If I could simply read the file into memory first and then use an augmented `load` method then that could work. Maybe you could point me to where the method is so I could make those changes if possible? Downloading the file locally feels like the antithesis of what I'm trying to do.

**Comment by erikbern** [comment]
sorry, the main point of using annoy is that it uses mmap to load a file from disk into memory very quickly. that requires the file to be on disk initially. not sure why you can't just download the file to a temporary file and load it that way?

**Comment by dpalbrecht** [comment]
Can you explain this a bit?

> not sure why you can't just download the file to a temporary file and load it that way? 

If I have it loaded as a temporary file object (it would be string at this point I believe), does the model not still have to be loaded in some way given a path?

**Comment by erikbern** [comment]
yeah so just write the bytes to a temporary file and then load it into an index

**Comment by yuanyangeli** [comment]
> Annoy doesn't support pickling. Why are you trying to pickle? Just save the index to disk.

How to add items after saving the index to disk if I want to increase the index?

**Comment by erikbern** [comment]
> How to add items after saving the index to disk if I want to increase the index?

This is not supported by Annoy

**Comment by yuanyangeli** [comment]
> > How to add items after saving the index to disk if I want to increase the index?
> 
> This is not supported by Annoy

ok . Thank you for your help!

**Comment by thvasilo** [comment]
Sorry to resurect this old thread. My usecase is that I'd like to run multiple annoy retrievals in parallel using Python joblib, and that requires the annoy index to be available to each process worker. joblib then tries to pickle the object and send it to the each process.

Any ideas on how to deal with this, given that annoy objects cannot be pickled?

**Comment by erikbern** [comment]
just save it to disk as a temporary file and send the file path probably

**Comment by thvasilo** [comment]
I was trying to do a parallel for over every row in a dataset, so I _think_ that would require loading the index for every call of the function.

In any case, seems like reverting to the multiprocessing backend for joblib fixed the issue. More details [here](https://joblib.readthedocs.io/en/latest/auto_examples/serialization_and_wrappers.html).

**Comment by erikbern** [comment]
> I was trying to do a parallel for over every row in a dataset, so I _think_ that would require loading the index for every call of the function.

loading the index is extremely fast though – probably microseconds
