### ISSUE TITLE
Crash after saving index

### ISSUE THREAD

**Issue by Axel-CH** [spotify/annoy#369]
Hi,
Folowing the [coach issue](https://github.com/NervanaSystems/coach/issues/235)  and #367, I'm trying to save the annoy index in a file. The issue is that when I use the save function, I get this error:

> You can't unbuild a loaded index
Segmentation erro (core dumped)

**Context:**
I'm running a Deep reinforcement learning algorithme with the coach library. During the training I can enable automatic checkpoints saving every X seconds. This is where annoy is used. 
One important thing here is that the **indexes in memory should be saved in files, and then stay in memory the be used in training**.

The index files will be restored after the training completion.

I saw that the save method is doing multiple actions:

- fwrite(_nodes, _s, _n_nodes, f);
- unload();
- return load(filename, prefault=false);

I tried to comment "unload" and "load" the see if the issue persist, like that:

      // unload();
      // return load(filename, prefault=false);

>       return true;

But the issue perssist, obviously it's more complicated than that.

Bellow the part of code triggering the error:
```
           for i in range(len(dicts)):
                # save index for each action
                p = Path(self.ap.task_parameters.checkpoint_save_dir) / "indexes"
                p.mkdir(parents=True, exist_ok=True)
                file_name = "index_" + str(i) + ".idx"
                indexPath = p / file_name
                indexPathStr = str(indexPath.absolute())
                dicts[i].index.save(indexPathStr) //Issue here
```

**Comment by Axel-CH** [comment]
I managed to make It work by doing what I said above, had some isues while testing. Do you think we 
can modify the save function by adding an option to "save_only".

It could be something like that:

**annoylib.h**

```
  bool save(const char* filename, bool prefault=false, bool saveonly=false) {
    if (_on_disk) {
      return true;
    } else {
      // Delete file if it already exists (See issue #335)
      unlink(filename);

      FILE *f = fopen(filename, "wb");
      if (f == NULL)
        return false;

      fwrite(_nodes, _s, _n_nodes, f);
      fclose(f);

      if(saveonly){
        return true;
      } else {
        unload();
        return load(filename, prefault=false);
      }

    }
  }

```

**Comment by erikbern** [comment]
Can you send the full code? There's something I'm missing here. Are you trying to save the same index multiple times? It's not possible (once you save an index, it will become immutable)

I should probably improve the error message, but not sure if this is a bug per se

**Comment by Axel-CH** [comment]
You will find the Agent code [here](https://github.com/NervanaSystems/coach/blob/master/rl_coach/agents/nec_agent.py) the saving operation is at line 206. It's the pickle that i'm trying to remove.

 And the used memory code [here](https://github.com/NervanaSystems/coach/blob/master/rl_coach/memories/non_episodic/differentiable_neural_dictionary.py). It's this par that interact direcly with the AnnoyIndex

**Comment by Axel-CH** [comment]
Below a chema of my understanding of the training process.

![training process (1)](https://user-images.githubusercontent.com/7593404/54087494-a3a91c80-4329-11e9-9d37-d59ad02f79c4.png)

**Comment by erikbern** [comment]
Are you trying to save the same index multiple times?

**Comment by erikbern** [comment]
Or are you trying to save an index that hasn’t been built?

**Comment by Axel-CH** [comment]
At each training episode, the index is rebuilded. (It's not my code I'm figuring out what is happening by debugging now).
The "handle_episode_ended" (nec_agent.py line 194) call the "add" function (differentiable_neural_dictionary.py  line 98 and 100) that rebuild the index.

**Comment by erikbern** [comment]
"One important thing here is that the indexes in memory should be saved in files, and then stay in memory the be used in training."

I don't really see the point of saving in that case. Why are you saving?

I feel like this isn't really a bug as much as just confusing exception message. Let me see if I can come up with a simpler case.

**Comment by erikbern** [comment]
Looked at the code and yeah, you're trying to unbuild a saved index. That's not possible with Annoy.

**Comment by Axel-CH** [comment]
I think what I said was Inaccurate as I saw that at each episode an index is rebuild.Thank you for your help I will find a workaround
