### ISSUE TITLE
centos 6 + python 2.7 can't use metric='dot'

### ISSUE THREAD

**Issue by YuxiangLu** [spotify/annoy#372]

**Comment by erikbern** [comment]
Can you share code and any error messages?

**Comment by YuxiangLu** [comment]
Code:
from annoy import AnnoyIndex
f = 3
i = AnnoyIndex(f, 'dot')
i.add_item(0, [0, 0, 2])
i.add_item(1, [0, 1, 1])
i.add_item(2, [1, 0, 0])
i.build(10)
l, d = i.get_nns_by_vector([2, 2, 2], 3, -1, True)
print(l)
print(d)

Traceback (most recent call last):
  File "a.py", line 8, in <module>
    l, d = i.get_nns_by_vector([2, 2, 2], 3, -1, True)
TypeError: 'NoneType' object is not iterable

**Comment by YuxiangLu** [comment]
Solved, solution as follow:
Download original code from GitHub, and reinstall by :  python setup.py install
