### ISSUE TITLE
Can I get node information of the tree?

### ISSUE THREAD

**Issue by liqima** [spotify/annoy#373]
Hi, very thanks for your share. But I have two confused questions:
Suppose I add some items and build one tree,
1.  Can I get node information of the tree? like node_list = [root, node1, node2 ...] with inorder or postorder, or node_list = [leafnode1, leafnode2, ...];
2.  For a query vector, can I get the "path" when searching, like query_path = [root, node1, node19, node30, leafnode50].

I do this because I want to build a code_book like [node1, node2, node3, ...], and encode my query vectors to {query1: node1, query2: node2 ...}
Thanks for your attention.

**Comment by erikbern** [comment]
sorry, there's no way to get that data!
