### ISSUE TITLE
[Question] About Sparse Vectors

### ISSUE THREAD

**Issue by loretoparisi** [spotify/annoy#375]
We have a sparse Index with ~1M columns tensor, and assumed we measure the `sparsity` like

```python
sparsity = 1.0 - ( count_nonzero(A) / float(A.size) )
```

in our data the sparsity it's about ~ .99, i.e its density is ~ .1.
How address data sparsity in Annoy? Shall we try a dimensionality reduction (SVD, PCA, etc.) before feeding annoy with sparse data?

**Comment by erikbern** [comment]
yeah definitely do some kind of dimensionality reduction first!
