### ISSUE TITLE
Annoy Index mapping

### ISSUE THREAD

**Issue by loretoparisi** [spotify/annoy#377]
Which is the best practice to map the annoy sequential index to the item identifiers?
Assumed that for a given dataset of items of fixed length, let's say 10K items I would have indexes ranging from 0 to 9,999, and I have update my index every day with new items.  Assumed I have a daily diff of 100 items, I will rebuild the new index with +100 keys every day, that means that at some point my `max(id)` will be filled out and then I would need to add 100 new keys at every update. This means that the index keys mapping (from item id to annoy integer id) must be dynamic and must be stored somewhere else than Annoy itself, causing a problem of synchronizing the mapping to the actual index keys (the ones got by the `status` api). So in this case, which is the best approach that honor the Annoy api?

**Comment by erikbern** [comment]
you'll have to store the mapping elsewhere, yes. note that you can't "patch" annoy indexes anyway, so you're just going to have to recreate the mapping every day

**Comment by loretoparisi** [comment]
@erikbern thank you I supposed that, we are using a simple `JSON` structure rather thank other pythonic solution, because in that way we can share the index mapping through python node.js and other clients.
