### ISSUE TITLE
search_k documentation is inconsistent

### ISSUE THREAD

**Issue by txntxn** [spotify/annoy#382]
The documentation for `search_k` is inconsistent.

In some places, it says: "search_k nodes which defaults to n_trees * n if not provided"

In other places, it says: "If search_k is not provided, it will default to n * n_trees * D where n is the number of approximate nearest neighbors and D is a constant depending on the metric."

Which is it?

And if it is `D`, could you enumerate the different `D` values for each metric? I searched the code for a few minutes but I was unable to determine what D is.

**Comment by erikbern** [comment]
where does it say something about D? that seems incorrect

**Comment by txntxn** [comment]
In the README. Perhaps in other places too? But definitely in the README.

**Comment by erikbern** [comment]
ok will take a look and fix
