### ISSUE TITLE
How can I reduced response time 

### ISSUE THREAD

**Issue by young2010** [spotify/annoy#384]
Hi I have about 800million arrays , each of dimension 200, builds a forest of 200 tree, 
I load trees file in a lab which have 8CPUS and 60 memory,
then I search some arrays take about 5000+ millisecond first time(search_k = -1)
How can I reduced response time

**Comment by erikbern** [comment]
the first query sometimes takes a lot of time because it has to read the data from disk. once you've "warmed up" the cache, it will be much faster. try issuing some random queries against the index first

**Comment by young2010** [comment]
Thanks for your reply. still have some issues
1.  I  set annoy_index->load("filepath", true);  I think all data will be in memory 
2.  I searching some random queries 
but it still take a lot of time for almostly every query , if the query never be searched in step 2.

**Comment by erikbern** [comment]
it should get faster and faster though – lmk if not

unless your index doesn't fit in ram

**Comment by young2010** [comment]
Fixed，The search file too large some index doesn't fit in ram

**Comment by chikubee** [comment]
@erikbern When I look at the size of the index file in disk, it is 157 MB, 
when I load it using 
> u.load('test.ann')

 the in-memory space is 4MB.
Which indicates that not the entire file is loaded.
Which page replacement algorithm is used internally?

Also when I try to execute the entire file load in MAC using,
> u.load('test_random.ann', prefault=True)
It gives a platform error related to MAPPOPULATE.

Can you pls help me understand what is happening here. Sorry for the inconvenience but I am not familiar with C++.

**Comment by erikbern** [comment]
if you keep loading it over and over, it's likely that the kernel is caching it, so that's why it might be fast
