### ISSUE TITLE
Add items without copying

### ISSUE THREAD

**Issue by msmk0** [spotify/annoy#389]
This is more of a question than an issue and relates to the C++ implementation.

From my understanding of the code, item elements/weights are copied when using `.add_item(...)`. In our application we already have all items stored in memory. Would it be possible to avoid the copy and use the elements directly by reference/pointer? If so, where in the library would this change have to be implemented?

**Comment by erikbern** [comment]
I think that would be somewhat hard to implement given the memory layout of Annoy indexes, unfortunately!
