### ISSUE TITLE
a.get_nns_by_item() returning distance greater than 1

### ISSUE THREAD

**Issue by vrk7bp** [spotify/annoy#390]
When I run a.get_nns_by_item(i, n, search_k=-1, include_distances=True) with cosine similarity, I'm getting distances that are larger than 1 (things like 1.11, 1.08). In general the results with the largest distance tend to be the most accurate results, but my understanding of cosine similarity is that the values should be between -1 and 1.

Is this a downstream result of approximations being made? And if so, is it still fair to assume that the larger the distance the more accurate the results?

**Comment by erikbern** [comment]
https://github.com/spotify/annoy#summary-of-features

"Cosine distance is equivalent to Euclidean distance of normalized vectors = sqrt(2-2*cos(u, v))"
