### ISSUE TITLE
How to get nearest neighours according to distance threshold?

### ISSUE THREAD

**Issue by liwt31** [spotify/annoy#391]
Is there any API like 
```
a.get_nns_by_item(i, threshold, search_k=-1, include_distances=False)
```
that returns all neighours of `i` whose distances to `i` are smaller than `threshold`?
If not so, are there any suggestions on possible workarounds?
Thanks!

**Comment by erikbern** [comment]
Sorry there’s no such functionality! You would have to search for say 100 neighbors and then filter the results
