### ISSUE TITLE
Is annoy an implementation of LSH Forest algorithm

### ISSUE THREAD

**Issue by jpainam** [spotify/annoy#392]
Hi, I have some difficulties understanding LSH Forest and I would like to know if this software Annoy gives an implementation of LSH Forest algorithm?
Thank you.

**Comment by erikbern** [comment]
No – and honestly I think LSH is a pretty bad method. Annoy constructs a forest of trees, but those splits are chosen in a highly data-informed way (as opposed to LSH where the splits are semi-random)
