### ISSUE TITLE
1.16.0 release for Linux broken

### ISSUE THREAD

**Issue by ixxie** [spotify/annoy#401]
It seems the 1.16.0 release for Linux is broken; it seems a MacOSX build has been pushed instead of the Linux one.

https://pypi.org/project/annoy/1.16.0/#files

**Comment by erikbern** [comment]
Sorry, not sure what happened. I uploaded a raw source distribution. Try
again?

**Comment by ixxie** [comment]
@erikbern looks like it works now! Thanks!
