### ISSUE TITLE
Can't build with gcc 5 where __AVX512F__ is defined

### ISSUE THREAD

**Issue by chyzzqo2** [spotify/annoy#402]
Seems like the `_mm512_*` functions used in the `#ifdef USE_AVX512` block are only present when using gcc 7+. on 5 it fails with errors like 

``` src/annoylib.h: In function ‘T {anonymous}::euclidean_distance(const T*, const T*, int) [with T = float]’:
src/annoylib.h:304:36: error: ‘_mm512_reduce_add_ps’ was not declared in this scope
result = _mm512_reduce_add_ps(d);```

**Comment by erikbern** [comment]
hm ok probably some preprocessor directive would be needed here. if you have any ideas, i'd really appreciate it!

**Comment by chyzzqo2** [comment]
There's always `__GNUC__` but i'm not familiar enough with these intrinsics to know if there is a better choice. Maybe @linhtran174 knows?

**Comment by linhtran174** [comment]
Hey @chyzzqo2,  `__AVX512F__` is defined means that your machine supports those intrinsics used in the block inside `USE_AVX512`, but only in gcc 7+ there are headers/declarations for those functions.

I'd suggest you use gcc 7+ if possible as AVX-512 instructions will provide quite a good performance boost.

I haven't figured out a way to send a notice at build time to suggest using gcc 7+ where AVX-512 is present, and ignoring AVX-512 if people just want to stick with gcc 5. @chyzzqo2 Do you know any directive to check GCC version? Any other suggestions? 

Thanks.

**Comment by chyzzqo2** [comment]
I was hoping for a better way, but if we are just going by gcc version then something like, ```#if defined(__GNUC__) && (__GNUC__ >6)``` should work

**Comment by erikbern** [comment]
ok, i'll add something like that

**Comment by fengyu05** [comment]
+1, is the fix on the agenda

**Comment by erikbern** [comment]
sure i can look

**Comment by fengyu05** [comment]
Not urgent. I just get around it by upgrade ubuntu version with gcc7+ :)
