### ISSUE TITLE
In circleci, pip install fail v1.16.0

### ISSUE THREAD

**Issue by aie2** [spotify/annoy#406]
In circleci(image=circleci/python:3.6.4), When I try to pip install annoy 1.16.0, it fails. 
![スクリーンショット 2019-08-16 11 09 10](https://user-images.githubusercontent.com/45744844/63144562-78400180-c02e-11e9-9d7b-a416a9a8142b.png)

But, I try to pip install annoy 1.15.2, it successes.
and I try to pip install annoy 1.16.0 by local circleci build, it succeses. (I wonder)
I think that it's the same problem #402

**Comment by erikbern** [comment]
interesting, i'll take a look this weekend hopefully

**Comment by aie2** [comment]
in 1.16.2,  build ok!

**Comment by erikbern** [comment]
Cool I think this is the same issue as #402
