### ISSUE TITLE
Input as continuous data

### ISSUE THREAD

**Issue by a11apurva** [spotify/annoy#408]
I understand that the algorithm needs vectorized data as input. All the examples and tutorials are using word2vec/GLOVE embeddings. 

But, my dataset has 30 continuous numerical/float variables (and 50K examples). Can Annoy handle it? Or is there any wrapper or function to convert in the required format?

**Comment by erikbern** [comment]
you probably have to use some dimensionality reduction method to embed it into a vector space. annoy can't handle infinite dimensionality :)
