### ISSUE TITLE
Can't compile annoy by docker?

### ISSUE THREAD

**Issue by WEN-MIN** [spotify/annoy#409]
Hi, thanks for release this project, it did help me a lot. But i encountered some problems when i deploy with docker. it is run well in my Mac system but have no response in docker environment。every-time i start this image it will break down and have no error info. do you have meet this problem?

**Comment by erikbern** [comment]
Can you provide more info?

**Comment by WEN-MIN** [comment]
Hi, thanks for release this  project, it did help me a lot. But i encountered some problems when i deploy with docker. it is run well in my Mac system but have no response in docker environment。every-time i start this image it will break down and have no error info. do you have meet this problem?
