### ISSUE TITLE
Euclidean metric is much slower than Angular?

### ISSUE THREAD

**Issue by ronxin** [spotify/annoy#41]
I am running an experiment with 1.2 million nodes, each represented by a 500-dim vector. On the same machine, when using Angular distance, it takes about 1 minute to build a tree; whereas using Euclidean, it takes about 1 hour. Is this difference caused by Euclidean distance having to calculate an extra offset value, or other things?

**Comment by erikbern** [comment]
See #65 – this makes Euclidean indexes substantially faster
