### ISSUE TITLE
Add more items to an index which is  loaded from disk

### ISSUE THREAD

**Issue by freakeinstein** [spotify/annoy#411]
Bindings: Python
Version: annoy==1.16.0

Hi, I'm using Annoy in a project, which supports data backup for failure recovery. I'm taking frequent backup of Annoy index to the disk. My requirement is to load Annoy index back, when the container restarts. I have used `load()` method to do that. The problem is, when I add more items to the loaded index with `add_item()` method, Annoy is giving an error saying `Exception: You can't add an item to a loaded index`.

To overcome this, I have tried `unbuild()` and `unload()` methods independently. What I observed in each scenario are:
unbuild - it is prevented for loaded indexes
unload - it just get's rid of current index along with its data and creates a fresh empty index - which I didn't wanted.

I can't find a possible method to add new data to loaded index. Please help.

**Comment by erikbern** [comment]
This is unfortunately not possible

**Comment by freakeinstein** [comment]
@erikbern Okay.  Can I retrieve all added vectors from the index instead?

**Comment by erikbern** [comment]
Sure, see documentation

**Comment by freakeinstein** [comment]
@erikbern  Sorry, I don't see one. Do you mean this process?
`all_vectors = a.get_nns_by_item(0, a.get_n_items())`

**Comment by piskvorky** [comment]
@freakeinstein see `a.get_item_vector(i)`, with `i` looping over the entire index.

Alternatively, you could keep the raw vectors separately (say in a text file, so it's easy to append to) and build your Annoy index from that on start up. Depends what "source of truth" and recovery guarantees you want in your backup / recovery pipeline.

**Comment by freakeinstein** [comment]
@piskvorky Thanks. I'm using NumPy disk writing separately and does loading it on startup.
