### ISSUE TITLE
Can't install annoy, Jupyter, Anaconda, Windows 10

### ISSUE THREAD

**Issue by Schrodinger-cat-kz** [spotify/annoy#412]
Would like to try this library for my ongoing project. Windows 10 installation for python instructions still do not exist on official web site. How to resolve this issue?

**Comment by MekeSakensky** [comment]
Installation instructioins for windows 10 are still missing, plz see https://pypi.org/project/annoy/

**Comment by MekeSakensky** [comment]
Any help highly appreciated.

**Comment by erikbern** [comment]
any way you can share the full compiler output?

**Comment by MekeSakensky** [comment]
![image](https://user-images.githubusercontent.com/48585802/64087189-cb6bc100-cd5d-11e9-821d-6042d8f8bc62.png)

**Comment by erikbern** [comment]
looks like the compiler output gets written to install-record.txt, so it would be great if you can paste the output from that file

**Comment by MekeSakensky** [comment]
I looked through the path where record.txt was supposed to be, such file does not exist

**Comment by MekeSakensky** [comment]
![image](https://user-images.githubusercontent.com/48585802/64088840-2bb23100-cd65-11e9-93aa-d9e44fbf9f3e.png)

**Comment by MekeSakensky** [comment]
as you see there are only three folders which do not contain those record.txt file

**Comment by MekeSakensky** [comment]
thank you anyways, annoy doesnt work on windows

**Comment by avtanshpandey** [comment]
Was the installation issue resolved? I am facing the same issue while istalling annoy
windows 10 x64
python-3.7 pip-20.2.4 setuptools-50.3.2 wheels-0.35.1
