### ISSUE TITLE
how to get the similarity score

### ISSUE THREAD

**Issue by Cumberbatch08** [spotify/annoy#417]
after I build the tree model, and I use the method nearest(vec, n) to get the nearest item in the candidate corpus, but I want get the similarity score.
becase, some returned results are not very near. If I have the score of every returned result, I can filter the result.
Is ther any method can do this?

**Comment by erikbern** [comment]
yeah, `get_distance`

**Comment by Cumberbatch08** [comment]
many thanks, I will have a try.
