### ISSUE TITLE
Segmentation fault with repeated builds

### ISSUE THREAD

**Issue by justinchiu** [spotify/annoy#420]
Repeated builds with the same argument leads to segmentations faults after saving then loading.

Repro:
```
import numpy as np
from annoy import AnnoyIndex

t = AnnoyIndex(250, "dot")

for i in range(1000):
    t.add_item(i, np.absolute(np.random.rand(250)))

# segfault
t.build(16)
t.build(16)
t.build(16)
t.save("test.ann")
print(t.get_nns_by_item(0, 10))
```

This may seem contrived, but calling build multiple times may be a bug that pops up when abstracting over AnnoyIndices and was pretty hard to find. A simple catch would be throwing an error if build has already been called, unless there are use-cases for calling build multiple times.

**Comment by erikbern** [comment]
Hi @justinchiu. This seems like a bug. Feel free to take a shot at fixing this. Might take a while for me to get to it!

**Comment by justinchiu** [comment]
Sure. Just to double check: is there a use-case for calling build multiple times? If not, I will throw an error on the second build.

**Comment by aidanlw17** [comment]
@justinchiu since you can alter the number of trees when building, there could be a use-case for experimenting with different parameters in a quick fashion?

**Comment by erikbern** [comment]
you could unbuild and then build, and that's fine. but shouldn't be able to build after building

**Comment by aidanlw17** [comment]
@erikbern If you were to unbuild, can you add more items and then build again?

**Comment by erikbern** [comment]
yeah that's right @aidanlw17

**Comment by aidanlw17** [comment]
@erikbern thanks for confirming. One last thing, if you have saved a build index, can you load that saved file and then unbuild it, add more items, then build and save again?

**Comment by erikbern** [comment]
@aidanlw17 no that’s not possible!

**Comment by aidanlw17** [comment]
@erikbern Ok. Thanks again!
