### ISSUE TITLE
what method used to bulid the tree?

### ISSUE THREAD

**Issue by Cumberbatch08** [spotify/annoy#421]
after add item, build the tree.
I'm interested of the method used to build the tree. does it use the knn or the kmeans?

**Comment by erikbern** [comment]
it splits the set of points recursively by picking semi-random splits based on the data distribution

**Comment by Cumberbatch08** [comment]
> it splits the set of points recursively by picking semi-random splits based on the data distribution

just like in knn, kd tree?
