### ISSUE TITLE
Cannot use after install

### ISSUE THREAD

**Issue by AKSHAYUBHAT** [spotify/annoy#43]
>>> import annoy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "annoy/__init__.py", line 15, in <module>
    from .annoylib import *
ImportError: No module named annoylib

**Comment by erikbern** [comment]
Can you paste the full log of `python setup.py install`?

**Comment by AKSHAYUBHAT** [comment]
(.pyenv)dhcp-ccc-1913:annoy-master aub3$ python setup.py install
running install
running bdist_egg
running egg_info
writing annoy.egg-info/PKG-INFO
writing top-level names to annoy.egg-info/top_level.txt
writing dependency_links to annoy.egg-info/dependency_links.txt
reading manifest file 'annoy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'annoy.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.6-intel/egg
running install_lib
running build_py
running build_ext
creating build/bdist.macosx-10.6-intel/egg
creating build/bdist.macosx-10.6-intel/egg/annoy
copying build/lib.macosx-10.6-intel-2.7/annoy/__init__.py -> build/bdist.macosx-10.6-intel/egg/annoy
copying build/lib.macosx-10.6-intel-2.7/annoy/annoylib.so -> build/bdist.macosx-10.6-intel/egg/annoy
copying build/lib.macosx-10.6-intel-2.7/annoylib.so -> build/bdist.macosx-10.6-intel/egg
byte-compiling build/bdist.macosx-10.6-intel/egg/annoy/__init__.py to __init__.pyc
creating stub loader for annoylib.so
byte-compiling build/bdist.macosx-10.6-intel/egg/annoylib.py to annoylib.pyc
creating build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying annoy.egg-info/PKG-INFO -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying annoy.egg-info/SOURCES.txt -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying annoy.egg-info/dependency_links.txt -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying annoy.egg-info/top_level.txt -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
writing build/bdist.macosx-10.6-intel/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
creating 'dist/annoy-1.0.5-py2.7-macosx-10.6-intel.egg' and adding 'build/bdist.macosx-10.6-intel/egg' to it
removing 'build/bdist.macosx-10.6-intel/egg' (and everything under it)
Processing annoy-1.0.5-py2.7-macosx-10.6-intel.egg
Removing /Users/aub3/Dropbox/.pyenv/lib/python2.7/site-packages/annoy-1.0.5-py2.7-macosx-10.6-intel.egg
Copying annoy-1.0.5-py2.7-macosx-10.6-intel.egg to /Users/aub3/Dropbox/.pyenv/lib/python2.7/site-packages
annoy 1.0.5 is already the active version in easy-install.pth

Installed /Users/aub3/Dropbox/.pyenv/lib/python2.7/site-packages/annoy-1.0.5-py2.7-macosx-10.6-intel.egg
Processing dependencies for annoy==1.0.5
Finished processing dependencies for annoy==1.0.5
(.pyenv)dhcp-ccc-1913:annoy-master aub3$ 

Sure, I also inspected the egg in the site-packages 

Archive:  annoy-1.0.5-py2.7-macosx-10.6-intel.egg
  inflating: annoylib.py             
  inflating: annoylib.pyc            
  inflating: annoylib.so             
  inflating: annoy/__init__.py       
  inflating: annoy/__init__.pyc      
  inflating: annoy/annoylib.so       
  inflating: EGG-INFO/dependency_links.txt  
  inflating: EGG-INFO/native_libs.txt  
  inflating: EGG-INFO/PKG-INFO       
  inflating: EGG-INFO/SOURCES.txt    
  inflating: EGG-INFO/top_level.txt  
  inflating: EGG-INFO/zip-safe

**Comment by erikbern** [comment]
I don't know what's going on. I think if you are in the directory of the repository, you can get issues trying to import annoylib because annoylib.so doesn't get installed in annoy/ – in that case just go to some other directory and try to import annoy, OR create a symlink from build/... to annoy/

Same issue for a pip install?

**Comment by AKSHAYUBHAT** [comment]
Yes, I even deactivated the virtualenv. Even with or without the virtualenv or using pip it still generates the same error, also on ubuntu. 

(.pyenv)dhcp-ccc-1913:annoy-master aub3$ pip uninstall annoy
Uninstalling annoy:
  /Users/aub3/Dropbox/.pyenv/lib/python2.7/site-packages/annoy-1.0.5-py2.7-macosx-10.6-intel.egg
Proceed (y/n)? y
  Successfully uninstalled annoy
(.pyenv)dhcp-ccc-1913:annoy-master aub3$ pip install annoy
Downloading/unpacking annoy
  Downloading annoy-1.0.5.tar.gz (622kB): 622kB downloaded
  Running setup.py egg_info for package annoy
    
Installing collected packages: annoy
  Running setup.py install for annoy
    building 'annoy.annoylib' extension
    /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/annoymodule.cc -o build/temp.macosx-10.6-intel-2.7/src/annoymodule.o
    src/annoymodule.cc:19:20: warning: extra tokens at end of #include directive [-Wextra-tokens]
    #include <stdint.h>:
                       ^
                       //
    1 warning generated.
    src/annoymodule.cc:19:20: warning: extra tokens at end of #include directive [-Wextra-tokens]
    #include <stdint.h>:
                       ^
                       //
    1 warning generated.
    /usr/bin/clang++ -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -g build/temp.macosx-10.6-intel-2.7/src/annoymodule.o -lboost_python -o build/lib.macosx-10.6-intel-2.7/annoy/annoylib.so
    ld: warning: ignoring file /usr/local/lib/libboost_python.dylib, file was built for x86_64 which is not the architecture being linked (i386): /usr/local/lib/libboost_python.dylib
    
Successfully installed annoy
Cleaning up...
(.pyenv)dhcp-ccc-1913:annoy-master aub3$ python
Python 2.7.8 (v2.7.8:ee879c0ffa11, Jun 29 2014, 21:07:35) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import annoy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "annoy/__init__.py", line 15, in <module>
    from .annoylib import *
ImportError: No module named annoylib
>>>

**Comment by AKSHAYUBHAT** [comment]
Also tried from another directory different error, also I get a fatal exception. 

ImportError: No module named annoy
>>> exit()
(.pyenv)dhcp-ccc-1913:~ aub3$ pip install annoy
Downloading/unpacking annoy
  Downloading annoy-1.0.5.tar.gz (622kB): 622kB downloaded
  Running setup.py egg_info for package annoy
    
Installing collected packages: annoy
  Running setup.py install for annoy
    building 'annoy.annoylib' extension
    /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/annoymodule.cc -o build/temp.macosx-10.6-intel-2.7/src/annoymodule.o
    src/annoymodule.cc:19:20: warning: extra tokens at end of #include directive [-Wextra-tokens]
    #include <stdint.h>:
                       ^
                       //
    1 warning generated.
    src/annoymodule.cc:19:20: warning: extra tokens at end of #include directive [-Wextra-tokens]
    #include <stdint.h>:
                       ^
                       //
    1 warning generated.
    /usr/bin/clang++ -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -g build/temp.macosx-10.6-intel-2.7/src/annoymodule.o -lboost_python -o build/lib.macosx-10.6-intel-2.7/annoy/annoylib.so

    ld: warning: ignoring file /usr/local/lib/libboost_python.dylib, file was built for x86_64 which is not the architecture being linked (i386): /usr/local/lib/libboost_python.dylib
    
Successfully installed annoy
Cleaning up...
(.pyenv)dhcp-ccc-1913:~ aub3$ 
(.pyenv)dhcp-ccc-1913:~ aub3$ python
Python 2.7.8 (v2.7.8:ee879c0ffa11, Jun 29 2014, 21:07:35) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import annoy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aub3/Dropbox/.pyenv/lib/python2.7/site-packages/annoy/__init__.py", line 15, in <module>
    from .annoylib import *
ImportError: dlopen(/Users/aub3/Dropbox/.pyenv/lib/python2.7/site-packages/annoy/annoylib.so, 2): Symbol not found: __ZN5boost6python7objects15function_objectERKNS1_11py_functionERKSt4pairIPKNS0_6detail7keywordES9_E
  Referenced from: /Users/aub3/Dropbox/.pyenv/lib/python2.7/site-packages/annoy/annoylib.so
  Expected in: flat namespace
 in /Users/aub3/Dropbox/.pyenv/lib/python2.7/site-packages/annoy/annoylib.so
>>> exit()
(.pyenv)dhcp-ccc-1913:~ aub3$ deactivate
dhcp-ccc-1913:~ aub3$ python
Python 2.7.8 (default, Jul 13 2014, 17:11:32) 
[GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import annoy
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6
dhcp-ccc-1913:~ aub3$

**Comment by erikbern** [comment]
Sounds like the first issue was just the problem with the directory

Now you're having a problem with boost dependencies. That's really annoying – not sure what to do

**Comment by erikbern** [comment]
I was able to run it a fresh macbook by running `brew install boost-python` and then `sudo pip install annoy`. Maybe you have some local installations of something that causes issues?

**Comment by erikbern** [comment]
Boost no longer needed, will close this. Try again, if it's still broken I will reopen

**Comment by AKSHAYUBHAT** [comment]
Thanks I will try.

**Comment by bobonovski** [comment]
Today I tried to install this using pip, after that I had the same problem. How you guys solved this?

**Comment by B4yesC4t** [comment]
@bobonovski I had same problem after i install with pip. Had you solved it?

**Comment by erikbern** [comment]
@B4yesC4t what problem? boost has been removed a long time ago

**Comment by crawftv** [comment]
Late to the party but, I got this error using a jupyter notebook on AWS sagemaker. Restarting my kernel solved the problem.

**Comment by jtlz2** [comment]
@crawftv A restart didn't work for me - any other ideas? :\

**Comment by jtlz2** [comment]
conda install -c conda-forge python-annoy
