### ISSUE TITLE
Index size suddenly blows up after adding 500K items at 1024 dimension size.

### ISSUE THREAD

**Issue by jay-trivedi** [spotify/annoy#438]
Hi,

I am using Annoy to index items with a dimension size of 1024. It works remarkably well during index building until about 500K items with index size reaching upto about 15GB in size. Easy to fit in RAM. However, as soon as I cross 500K items, the index size suddenly blows up and by the time I reach 520K items the index size goes beyond 60GB (= machine RAM) and my machine runs out of memory. I tried reducing the n_trees from 15 to 12 but that doesn't help. Here are some useful details.

os - ubuntu 18.04, 60GB memory, 4 cores
python version 3.6.9
annoy version 1.16.0
dimensions - 1024
metric - euclidian

Thanks for the help in advance!

**Comment by erikbern** [comment]
i would consider a dimensionality reduction of some sort before you add the items. so maybe go from 1024 dimensions down to say 64 first.

**Comment by jay-trivedi** [comment]
hey, sorry was on a break. my teammate did some digging and looks like the issue in extremely large annoy_ids we are passing (reaching upto 100 mill). Annoy breaks down on passing big integers as ids. We will patch them soon. That should fix the issue. Will post here once the issue is fixed.

Thanks for the help though.

**Comment by erikbern** [comment]
Nice!

**Comment by zabatani** [comment]
Hi,

@jay-trivedi, could you please specify whether this issue has already been fixed?

I have ~10M vectors with a dimension size of 300 and my index seem to be blowing up as well (>50GB).

**Comment by jay-trivedi** [comment]
hi @zabatani - in my case, we were using big ints as annoy_ids. If the numbers are too big, the index will blow up. See if that's the case with you as well. We fixed it by resetting the annoy_ids to 0 every time we regenerated the index. Worked for us. Hope this helps. Sorry for a delayed response.

**Comment by SaschaHeyer** [comment]
Does annoy already contains this fix in the current version?

**Comment by erikbern** [comment]
There's no bug here so nothing to fix. You just have to make sure not to use large ids since annoy will allocate memory for max(id)+1 vectors. If you have large integer ids, you have to remap to a small range first.
