### ISSUE TITLE
Add Maximum Inner Product Search

### ISSUE THREAD

**Issue by a1k0n** [spotify/annoy#44]
See http://arxiv.org/pdf/1410.5410v2.pdf

This is pretty easy to implement. I will probably do it myself, but in case I don't get to it, I wanted to jot some notes down and this seems like a good place to do it.

The basic algorithm is very simple and can be used in Annoy Angular mode with the following modifications, assuming we use the recommended m=2, U=0.75 parameters in the paper:

Initialization:
- Add two to the input dimension before any add_item has been called, and pad the last two dimensions with 0s in add_item.

When it is time to `build()`:
- First, find the norm of the largest vector in the input set and compute a scale parameter U / ||x_max||, and then re-scale all vectors by this factor. Re-scaling the universe does not change the argmax of any maximum inner product.
- While rescaling, set the extra two dimensions of each vector to [0.5 - ||x_i||^2, 0.5 - ||x_i||^4]
- Resume the standard build process.

When it is time to query:
- Just append two zeros to the query vector. That's it. The result will be the maximum dot product, instead of the maximum cosine distance, because of the brilliant / insane proofs in the paper above.

**Comment by a1k0n** [comment]
Hmm, and last modification: re-sort based on inner products instead of cosine distance.

**Comment by a1k0n** [comment]
Hmm, and actually the asymmetric LSH stuff doesn't even have to affect the query algorithm at all, only the tree building phase, and so it actually only affects the way the tree nodes are split; the extra two dimensions don't need to be stored.

**Comment by erikbern** [comment]
Yes and it sounds pretty easy to construct a hyperplane if you sample two point from the distribution. If you sample p and q then the boundary becomes `dot(p, x) = dot(q, x)` which is equivalent to `dot(p-q, x)=0` which means you can just compute the sign of `p-q` and `x` for any vector. The problem with this idea though is that if `|p| >> |q|` then almost all vectors will be on the same side of the split. I don't know if that's an issue in practice

**Comment by a1k0n** [comment]
Well, you have to keep in mind that the magnitudes are all scaled to be < 0.75 first, so the last two components are < 0.5 and > -0.06 or so.

**Comment by a1k0n** [comment]
...but then those buckets would be useless on the query side, where those coordinates are 0. Hmm.

**Comment by erikbern** [comment]
I meant without adding extra coordinates, just doing the split in the original space

**Comment by nemo83** [comment]
HI, was this ever implemented?

**Comment by erikbern** [comment]
nope

**Comment by lesterlitch** [comment]
For anyone chasing this dream, check out: https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/XboxInnerProduct.pdf 

Seems to work out reasonably using Annoy.
