### ISSUE TITLE
GZip support for model files?

### ISSUE THREAD

**Issue by jpmatusik** [spotify/annoy#440]
Hi quick question.

I have a pretty big model file (about 1.6GB) and when I gzip it, it gets down to about 360MB. So some decent compression. But as far as I can tell, the load method does not support any compressed files.

I was wondering if I'm wrong about that and if so, would a PR adding support for something like 
the following be welcome?

```
u = AnnoyIndex(f, 'angular')
u.load('model_file.knn.gz')
```

Basically just something to check to see if the file extension ends in 'gz' and handle it.

**Comment by erikbern** [comment]
interesting – i wouldn't have expected files to compress so well.

i think it would be very hard to implement what you're saying due to the mmapping, unfortunately.

**Comment by jpmatusik** [comment]
Oh gotcha. Well I'm almost certainly not the person for the job then lol.

I'll close this out then. I appreciate the response.
