### ISSUE TITLE
Question regarding thread safety.

### ISSUE THREAD

**Issue by altmnt** [spotify/annoy#441]
I am planning to create a webapp that is going to on_disk_build searches and adds vectors to the tree by web requests. Is this going to be an issue if several threads do that concurrently(several web requests)?

**Comment by erikbern** [comment]
Should be fine!

**Comment by erikbern** [comment]
Should be fine!

**Comment by piskvorky** [comment]
Remarkable consistency!

**Comment by erikbern** [comment]
lol, i didn't realize replying to that email would add a comment on github. Funny I wrote the exact same thing. My language model is very low perplexity!

**Comment by altmnt** [comment]
Thanks for the effort:)
