### ISSUE TITLE
Kernel dies when trying to add items

### ISSUE THREAD

**Issue by nishray12096** [spotify/annoy#446]
Hello!

I have ~30k documents transformed into LASER embeddings using the laserembeddings package (1024 dimensions). The documents are now in a pandas DF: indexed by some integer, with all columns being the LASER transformation dimensions.

When I run this:
`Laser_Index = AnnoyIndex(1024, 'angular')
for ind in EmbeddingsFrame.index:
    Laser_Index.add_item(ind, EmbeddingsFrame.loc[ind].tolist())`

The python kernel dies. I've confirmed that ind is an integer and I've tried adding the embeddings as a list, array, and PD series. All yield the same results. I've run `pip install --upgrade annoy`, but the issue persists there as well. The toy example in the Readme works fine - so I figure this has something to do with data types, but am lost as to what I can do to resolve the issue. Thanks for any advice in advance :)

-Nishant

**Comment by erikbern** [comment]
odd. i can see if i can reproduce it on my side. at least shouldn't segfault, that's not great.

**Comment by nishray12096** [comment]
I've seen the same issue on a linux VM + my local machine. I tried to replicate the toy Readme example with 1024 dimensions and ran into the same error: so not anything to do with the data I suppose. My colleagues have been able to create an index with the same dimensions and about 4x the amount of records with a similar compute setup, so unsure if it's a resource issue as well.

-Nishant

**Comment by erikbern** [comment]
> I tried to replicate the toy Readme example with 1024 dimensions and ran into the same error: so not anything to do with the data I suppose.

which toy readme example do you mean? are you running the code verbatim? is the only change that you made to increase the dimensionality? can you share the exact code with me?

**Comment by nishray12096** [comment]
Apologies - found the issue. It seems the integer ID values were too large. I mapped them to smaller values and no issues. Original values ranged from 8004232 to 18194070. Is it possible to add some handling/more informative errors to this?

**Comment by erikbern** [comment]
ok, got it. yeah we could probably handle exceptions with malloc and deal with it. let me see if i can hack something together.

**Comment by erikbern** [comment]
looking at it, realloc doesn't actually fail. it's the OS killing the application when it tries to allocate too much memory. so I think it's nontrivial to catch it inside the library
