### ISSUE TITLE
Save annoy index in databricks/pyspark for later use?

### ISSUE THREAD

**Issue by robotheart** [spotify/annoy#449]
Hi there,

For a project I’m using this library and was able to get a job running in Databricks that uses a lot of data to build the index (takes some time to run). For a follow up task I now need to use annoy in real time to predict on steaming data. Is there a best way to do this? I was hoping to just save the index I built previously and load it for the new job to predict. I see though the index can’t be pickled and when I try to save it with the library method to an s3 bucket path it causes issues. It seems I can only save it as “index.ann” for example, no path name. Is there a good workaround? Thanks!

**Comment by erikbern** [comment]
You can use any path, but it has to be a file. No idea if it lets you write to local disk but that sounds like the only option

**Comment by robotheart** [comment]
Hey thanks for your reply. Could you help me understand your answer better with an example? I know on my end I’ve written to a path that exists say “/mypathname/index.ann” and it still says the file doesn’t exist... and that path is a real thing.  Also I have had read online of other who said they were able to get past where I was (writing it to a bucket but no example code to help me debug my problem) but then in their experience the index will disappear after writing? Have you ever had this happen?

**Comment by erikbern** [comment]
Maybe the directory you’re trying to write to doesn’t exist?

**Comment by robotheart** [comment]
I have can navigate to it manually is the weird thing, so I know it exists... : /

**Comment by robotheart** [comment]
Hey there, found an answer to this. Your path needs to be /dbfs/mnt/pathname not s3 since this isn't a spark thing. Hope it helps anyone else facing the same issue!
