### ISSUE TITLE
What is the best way to scale the compute around annoy index

### ISSUE THREAD

**Issue by eyal13579** [spotify/annoy#450]
Assume I have big annoy index that serves real time production system.
Assume I need more than one machine/pod to handle the traffic.
In addition - from time to time throughout the day - index should be rebuilt.

What's the practice to productize this?

- Should we have some NAS (we've tried aws efs) - that all dockers are attached to? (performance is not well - but logic of replacement is pretty easy - hot swap)

- Should we start syncing big files around the dockers (heavy logic, lots of edge cases)? and if so, any recommendation

(just to make it a bit complicated - assume that each customer we serve has it's own index, so we need to have all dockers access to all indexes - to be able to reply to each query - load-search-unload..)

**Comment by erikbern** [comment]
Thus doesn’t quite seem like a question about Annoy. Maybe upload files to S3 and have the apps download it to local disk and load it?

**Comment by poonam2331** [comment]
> Assume I have big annoy index that serves real time production system.
> Assume I need more than one machine/pod to handle the traffic.
> In addition - from time to time throughout the day - index should be rebuilt.
> 
> What's the practice to productize this?
> 
>     * Should we have some NAS (we've tried aws efs) - that all dockers are attached to? (performance is not well - but logic of replacement is pretty easy - hot swap)
> 
>     * Should we start syncing big files around the dockers (heavy logic, lots of edge cases)? and if so, any recommendation
> 
> 
> (just to make it a bit complicated - assume that each customer we serve has it's own index, so we need to have all dockers access to all indexes - to be able to reply to each query - load-search-unload..)

I'm curious, how did you end up implementing it?
