### ISSUE TITLE
Can on_disk_build mode save memory?

### ISSUE THREAD

**Issue by bit-pku-zdf** [spotify/annoy#451]
As the title, I want to know if the on disk build mode save memory?
Code:

t = AnnoyIndex(f, 'dot')  # Length of item vector that will be indexed
t.on_disk_build('test.ann')
t1 = time.time()
print("t1: %f"%(t1))
for i in range(50000000):
    #print(i)
    #t_1 = time.time()
    v = [random.gauss(0, 1) for z in range(f)]
    #t_3 = time.time()
    t.add_item(i, v)
    #t_2 = time.time()
    #print(t_2-t_1)
t2 = time.time()
print("t2: %f"%(t2))
t.build(100) # 10 trees

If the number of vector is 50million, the dimension is 512, the space of disk is about 100G, how about the memory?

**Comment by bit-pku-zdf** [comment]
Also 100G ? or smaller?

**Comment by queezzy** [comment]
Hi @bit-pku-zdf 

Please what were the results of your experiments ? Have you succeeded in indexing your data ?
How much time did that take ? With how much trees ? 
I also have about 10 millions document with 500 dimensions and im wondering how much time this could take to build

**Comment by SaschaHeyer** [comment]
I am also interested in an answer to this questions. 
Does the index file sizes equals with the memory required in order to search against the index?

**Comment by erikbern** [comment]
it saves a bit of memory while building the index, but it won't affect the memory usage when you query it!
