### ISSUE TITLE
Fixed-radius near neighbors

### ISSUE THREAD

**Issue by appanacca** [spotify/annoy#452]
Hello,
I have seen that in the interface of the AnnoyIndex is not possible to perform ball queries.
Is it possible in theory to support it ? 
I had in mind something like "get_nns_by_item" with a radius parameters. 
Is it possible to do it in Annoy ? Any bibliography on the subject ? 

Thank you  in advance !

**Comment by erikbern** [comment]
i don't know if this is trivially doable – i would just use `get_nns_by_item` and set `include_distances=True` and set `n` to a very high value and then post-process the results
