### ISSUE TITLE
Question about memory allocation and add_item

### ISSUE THREAD

**Issue by fralik** [spotify/annoy#459]
The documentation says that when one calls `a.add_item(i, v)`, then *it* will allocate memory for `max(i) + 1` items. My question is: when this allocation takes places? If I just read this explanation, then it seems to me that this code:
```
a = AnnoyIndex(3, 'angular')
a.add_item(0, [1, 0, 0])
a.add_item(1, [0, 1, 0])
a.add_item(2, [0, 0, 1])
```
will reallocate memory 3 times. First, it will allocate for 1 item, then it will reallocate for 2 items and then for 3. Is it so or do I miss smt?

I tried to look for answer in issues, but have only found question regarding non sequential and non zero-based item ids.

**Comment by erikbern** [comment]
you can look in the code. it allocates memory for something like 1.3 * (max(id) +1) and only reallocates once you cross that limit (to another 1.3x the max id)

**Comment by fralik** [comment]
Can you please explain on the above example? (assume we insert 10 items instead of 3).

For me, your answer contains exactly the same information as in the docs. I am still puzzled about when the reallocation happens.

Let me put it another way. If I want to add a 100 items, won't it be beneficial to do smtg like this:
```
t.add_item(99, v)
for i in range(100):
    v = get_vector() 
    t.add_item(i, v)
```
Thus allocating memory just once.

Thanks!

**Comment by erikbern** [comment]
No it won’t be. Look at the code here for more info. https://github.com/spotify/annoy/blob/335bf82fe082c8c8357361b488598ad915677b9e/src/annoylib.h#L1153
