### ISSUE TITLE
Boost library linking problem on Python 3

### ISSUE THREAD

**Issue by malthe** [spotify/annoy#46]
I needed to ``s/boost_python/boost_python3`` in ``setup.py`` to get a build that would work on Python 3.

This is on Arch Linux.

**Comment by erikbern** [comment]
That's annoying. I should enable Python 3 builds on Travis and fix issues

**Comment by erikbern** [comment]
Doesn't seem like boost for Python 3 is available in apt-get

Hm I should really just drop the dependency on Boost since it's causing so many issues

**Comment by piskvorky** [comment]
+1 on dropping Boost.

**Comment by erikbern** [comment]
Ok let me give it a shot when I have time (could take a few weeks/months, would love it if someone else could give it a shot)

**Comment by piskvorky** [comment]
I bet you would :)

We started an "incubator" thing where we assign open source improvements & algos to students (a year project or thesis or whatever). Mostly gensim, but annoy is a good fit too.

This task may be a bit too non-academic, but if someone suitably hardcore turns up, I'll direct them here. Would be great to have Annoy more accessible and noob-proof.

CC piskvorky/gensim#51

**Comment by erikbern** [comment]
Nice. I think dropping boost isn't more than a few hours though. Whole
annoy is a few hundred lines and the boost part is just a handful lines. I
just need a few spare hours (hard right now)

**Comment by erikbern** [comment]
Getting closer – Boost dependency is now dropped, next step is Python 3 support.

**Comment by erikbern** [comment]
Try now! Will re-open if broken
