### ISSUE TITLE
Same value returned for all distances

### ISSUE THREAD

**Issue by tykiww** [spotify/annoy#464]
Love the tech. Thank you for your work.

I have been trying to use annoy to find the nearest neighbors of a 256x256x1 grayscale image with an appended vector of colors (length 12) and all the reported neighbors have come back with the same distance. It yields surprisingly great results, but the distances are disconcerting.

Is that because my dimensions are too large? 

The table below corresponds with:  ID, Neighbor (n), Distance (n), ... 

![neighbor_same](https://user-images.githubusercontent.com/36966666/76545464-6cdf7800-644f-11ea-8bea-021154d0c676.png)

Thank you for your help!

**Comment by erikbern** [comment]
how many dimesntions?

hard to say what's the issue without having more info

**Comment by tykiww** [comment]
Sure.

Each flattened image is shape (65548,)
Here is the function I use to retrieve the neighbors

```
def annoy(images, labels):
    
    n, f = np.shape(images) # should be (501,65548)
    t = AnnoyIndex(f, 'euclidean') 

    for i in range(n): 
        t.add_item(i, images[i])

    t.build(100) 

    # Use index and match with labels
    lls = np.array(labels)
    tn = t.get_nns_by_item(0, 4, search_k=10, include_distances=True)
    zob = zip(lls[tn[0]], tn[1])
    out = [i for xs in zob for i in xs]

    # Remove first distance.
    three_neighbors = np.delete(out, 1)
    return three_neighbors
```
