### ISSUE TITLE
Exposing _random in AnnoyIndex to python

### ISSUE THREAD

**Issue by jnboehm** [spotify/annoy#465]
I'd like to be able to have more control about the randomness when using annoy.  In essence I'd love to be able to pass a seed, or even better, an instance of numpy.random.RandomGenerator, although a seed will most likely suffice.

I think editing [this line](https://github.com/spotify/annoy/blob/20047ca84b44f471c5739edd6ea7f22484e80fe1/src/annoylib.h#L846) and moving it to the public part would be the first step.

What I'm still unclear on is how the C++ object would relate to the corresponding python object (I assume this is nontrivial). Furthermore, can the `Random` object even be initialized with an int?  In general how Python and C++ work together is still a bit of a mystery to me.

**Comment by erikbern** [comment]
You can actually set the seed in Python, I realize it just never was documented

See https://github.com/spotify/annoy/blob/master/src/annoymodule.cc#L537

I would love it if you want to add it to README.md!

**Comment by jnboehm** [comment]
Oh, I did not notice that myself, thank you! Sure, I'll try to get around to it tomorrow.

**Comment by jnboehm** [comment]
From looking at it, it seems like it's only used in `_make_tree`?  If I understand it correctly, this means that it's only necessary to pass it to the AnnoyIndex before calling build to make the behavior deterministic?  Or did I miss something?

My original assumption was that the retrieval uses the randomness, but the code indicates the opposite.

**Comment by erikbern** [comment]
Thanks for adding it to the documentation!
