### ISSUE TITLE
Hamming distance issue

### ISSUE THREAD

**Issue by dtanase** [spotify/annoy#468]
Hello 

I am encoding about 2M vectors (representing names of streets, as ASCII codes, e.g.: [63,71,179,102,32,222,127,111,...]) and I want to use to retrieve the street ID based on the free user input. Euclidean distance works just fine, but it has a problem: it is susceptible to input length: the user might write "Somestr" instead "Somestreet" which is still a valid input. Hamming distance seems much more robust to the variations in length, but there is either an implementation issue in Annoy or a misunderstanding on my side. Every time I am looking up similar vectors based on my input I get back a list of matches that 1) all have a vector of only 1.0 and 2) all have a 0.0 distance to my query vector:

Query vector: [119, 97, 108, 108, 105, 115, 101, 108, 108, 101, 110, 115, 116, 114, 97, 115, 115, 101, 32, 32, 32, 32, 32, 32, 32]
The best match: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
Distance: 0.0

I also tried to encode the data using continuous values ([0..1]) without any difference. I tried different tree sizes (up to 1000) with no change.

Am I encoding wrongly my data (currently, it is the same routine as the query vector)? Is there any issue in Annoy's implementation of Hamming distance?

I am using the release version: 1.16.3

Thank you
Dorian

**Comment by erikbern** [comment]
Hamming only works on bit strings, so the input data gets truncated to 0-1

**Comment by dtanase** [comment]
Hello Erik

Thank you for your answer!

Could you please add this in the readme so that others don't struggle?

Thank you,
Dorian

**Comment by erikbern** [comment]
> Could you please add this in the readme so that others don't struggle?

Want to add it and send a pull request?
