### ISSUE TITLE
Latest conda-forge build for Linux and Python 3.7 broken

### ISSUE THREAD

**Issue by buhrmann** [spotify/annoy#469]
Sorry for "cross-posting" this: https://github.com/conda-forge/python-annoy-feedstock/issues/32, but I'm not sure which is the best channel to raise this. In short, something must have gone wrong from build 1.16.3-py37he1b5a44_0 to 1.16.3-py37h3340039_1.  I imagine something in the configuration of the build, and resulting binary artifacts not being created correctly (since I don't think there were any code changes)?

**Comment by erikbern** [comment]
Odd. I have no idea how to even troubleshoot this. Any pointers?

**Comment by buhrmann** [comment]
To reproduce this minimal Dockerfile seems to work:

```Dockerfile
FROM continuumio/miniconda3

RUN conda config --prepend channels conda-forge && \
    conda create -n myenv -c conda-forge python=3.7.6 python-annoy=1.16.3=py37he1b5a44_0

RUN rm -f /bin/sh && ln -s /bin/bash /bin/sh
RUN source activate myenv && \
    python -c "import annoy; idx = annoy.AnnoyIndex(2, 'angular'); print('All good :)')"
```

If you build this e.g. with `docker build -t annoy .` it should print "All good :)". However, when you remove the version specification of python-annoy, to get the lastest, the result is a `The command ... returned a non-zero code: 132`.

If you remove the last line in the Dockerfile and execute it manually inside the container instead,  you'll get a "Illegal instruction". 

Does this help?

**Comment by buhrmann** [comment]
It seems in some cases the 132 exit code has to with incompatible CPU instruction sets. As it seems that 5 days ago there were major changes in the conda-forge feedstock, I imagine something isn't correctly configured in those builds.

**Comment by buhrmann** [comment]
The offending change seems to be the merge by @xhochy 5 days ago, not sure how to ping him about it, other than reporting the issue in the feedstock repo.

**Comment by xhochy** [comment]
Should be fixed in ~1h. This came from the `march=native` in the build scripts. The CI now supports AVX2 instructions which not all machines support.

**Comment by buhrmann** [comment]
Ok, great! Thanks for fixing...

**Comment by erikbern** [comment]
Thanks for fixing. Closing this for now.
