### ISSUE TITLE
get_nns_by_vector possibility

### ISSUE THREAD

**Issue by shiranD** [spotify/annoy#473]
Hi,
And thanks for maintaining it!
I wonder if it's possible to have the function above get several vectors, and accordingly output their corresponding nearest heights (and distances)
Best,
Shiran

**Comment by VipanchiRKatthula** [comment]
I would like to get that possibility as well. Because for the use case I am working on, I need to get the closest vector and the distance for an array of 549 images and so on. Which is time consuming to do in a loop.

**Comment by erikbern** [comment]
You can always use a thread pool to speed it up
