### ISSUE TITLE
scalability of annoy

### ISSUE THREAD

**Issue by jasica528** [spotify/annoy#474]
how about the memory, recall and search time changes when annoy scales from one million 128-dimensional features to one billion 128-dimensional features?

**Comment by jasica528** [comment]
how about the memory, recall and search time changes when annoy scales from one million features to one billion features?

**Comment by erikbern** [comment]
annoy probably won't do super well with a billion items – it's built for handling data that can fit in RAM

**Comment by SaschaHeyer** [comment]
Hi @erikbern 

similar question:
Assume we have an index with a size of 4GB will annoy load this file completely into memory?
Or does it require less than 4GB of memory?

Stay healthy
Sascha

**Comment by erikbern** [comment]
it needs to fit into memory, otherwise the kernel will swap it out to disk which could be painfully slow
