### ISSUE TITLE
Need guidance with best approach

### ISSUE THREAD

**Issue by rishabh00100** [spotify/annoy#476]
I want to create an index of n different identities, each identity having multiple vectors.

For example,
Lets say I have 3 identities having the following details:

- Identity_1 has 20 vectors (lets call them vector_1, vector_2 ..... vector_20)
- Identity_2 has 40 vectors (lets call them vector_21, vector_22 ..... vector_60)
- Identity_3 has 15 vectors (lets call them vector_61, vector_62 ..... vector_75)

**Question:**
What should be the best approach in add_item? 

Approach 1:
use index_file.add_item(item_id, vector) with item_id in [1,2,3] and vector in [vector_1, vector_2 ....vector_75] 

Approach 2:
use index_file.add_item(item_id, vector) with item_id in [1,2,........74, 75] and vector in [vector_1, vector_2 ....vector_75] and then map the numbers 1 - 75 with my corresponding Identities separately

TIA

**Comment by erikbern** [comment]
If you only have 100 vectors, why even use Annoy? Just put them in a matrix and do a brute force search – it will be much simpler and faster

**Comment by rishabh00100** [comment]
Thank you for that quick response Erik
Apologies as I could not explain my problem correctly

I actually have around 2.5 lakh vectors corresponding to ~1200 identities
I just tried to explain my problem using a simplified example
