### ISSUE TITLE
finding neighbours takes forever!!

### ISSUE THREAD

**Issue by sumegha19** [spotify/annoy#479]
Hi,
Great work first of all!
I am working with about 10 million,  100 dimensional, vectors with.
I saw that as I increase the number of vectors to be loaded for some clustering that I need for a project I am doing it shows time complexity of the order 2^n
Say for 100k vectors it took 91 seconds to find say 50 similar vectors(angular distance metric used)
for 200k it takes 183 seconds
and for 300 k it takes 268 seconds.
I build the trees for the respective data independently, for processing 10 million vectors it takes forever. 
Can you help me out where I might be getting this wrong.
Thanks

**Comment by erikbern** [comment]
It’s possible your data doesn’t fit in RAM and that’s why it’s so slow

**Comment by sumegha19** [comment]
Thanks for this prompt reply! Well I have kept track of RAM usage and I am working on GCP with 60GB RAM! The entire data gets loaded and I monitor the RAM occupancy any other options I can explore or look into..

**Comment by absin1** [comment]
I think sharding the data and building a choice of indices can help?

**Comment by sumegha19** [comment]
Looked into the code and did some changes in fetching vectors and storing the needed neighbors. Some changes in use of arrays rather than lists did the work.
Thanks a ton team! Closing the issue :)

**Comment by alexvais** [comment]
@sumegha19 what changes did you apply to improve performance? we are with the same issue
