### ISSUE TITLE
Vector metadata

### ISSUE THREAD

**Issue by malthe** [spotify/annoy#48]
It would be convenient to associate each vector with a metadata which would then be saved in the index on disk. Currently, you need to maintain a separate data structure which is inconvenient in some cases.

**Comment by erikbern** [comment]
not sure if i want to add support for that to annoy – strings probably aren't enough, and then you need more complicated data structures etc

**Comment by malthe** [comment]
byte strings are enough.

**Comment by erikbern** [comment]
maybe use http://www.h5py.org/ ?

**Comment by piskvorky** [comment]
I for one wouldn't like Annoy to move toward doubling as a datastore. I really like Annoy's current targeted focus.

@malthe , there are many lightweight ways to supplement the raw ids with additional metadata: built-in `dict`, built-in `shelve`/`anydbm`,  [sqlitedict](https://github.com/piskvorky/sqlitedict)...

**Comment by malthe** [comment]
Definitely. Right now I just do it like this:
```python
with open("index.map", "w") as f:
    for i, j, vector in items:
        u.add_item(i, vector)
        f.write(pack('<L', j))
```
This way I can ``mmap``, or simply seek directly to the vector id – in this example ``j`` – from a vector id.

But perhaps Annoy could grow an API to load data from a stream. This way I can wrap the tree data in my own format and only have a single file on disk.
