### ISSUE TITLE
conda-forge Windows packages

### ISSUE THREAD

**Issue by pavlin-policar** [spotify/annoy#480]
Hi, I've just released a version of openTSNE (https://github.com/pavlin-policar/openTSNE), where I switched over to Annoy for nearest neighbor search. I am extremely happy with Annoy, however, I just noticed that Annoy does not provide Windows packages on conda-forge. This is very problematic, since I need my library to be totally cross-platform, and I am wondering why these packages are not included. Conda-forge takes care of the compilation process, and it shouldn't be too hard to adapt the C++ code to make it work on Windows as well.

A similar C++ only t-SNE implementation (https://github.com/KlugerLab/FIt-SNE) uses Annoy, but I see that they have copied over the source code and modified it slightly.

What are your thoughts on this?

**Comment by pavlin-policar** [comment]
I just noticed that the CI pipeline includes AppVeyor, meaning that Annoy does indeed work on Windows. I had previously thought it was a code compatibility issue, which might require some work to fix, but given that it already works, I am now even more confused why this isn't a thing.

**Comment by erikbern** [comment]
i have no idea how to set this up, but if you can give me some detailed pointers, i can give it a shot! thanks!

**Comment by pavlin-policar** [comment]
Unfortunately, I don't have any specific pointers for conda. Conda is pretty straightforward. If you run into problems it would likely be due to the code itself. I've had issues with getting openMP to work properly before on the mac VM.

I would just remove the [win] flag from the [recipe](https://github.com/conda-forge/python-annoy-feedstock/blob/master/recipe/meta.yaml#L18) and see what happens. Who knows, it might even work straight away. I can't imagine there being any _huge_ problems since you're already running unit tests on appveyor so clearly Annoy already works on windows :smile:

**Comment by pavlin-policar** [comment]
@erikbern I just wanted to let you know that today I copied the source of annoy directly into openTSNE and included it in my build process. I needed to get this done asap. I had absolutely no issues building annoy on either Azure or conda-forge. Your `setup.py` is completely fine and there are no issues running or building on windows. When you guys set up the wheels and conda packages, I'd much rather depend on that. But, building and distributing should be really easy, and I'd be happy to help if you need any help.

**Comment by erikbern** [comment]
ok, i have never used conda so no idea how to fix it. i'll see if i have some time – doubtful of it :/
