### ISSUE TITLE
Annoy model optimization - best practices

### ISSUE THREAD

**Issue by tylerhutcherson** [spotify/annoy#486]
Thanks for an incredible piece of software!

**Context**
I currently leverage Annoy as the primary workhorse for a product image search engine application. I have ~10k items/vectors of 2048 features. The exact number of items and feature values are updated & re-built each day as the underlying data source changes.

Because my application is serving "real-time" results to users, the task is to return nearest neighbors to the query vector as fast as possible (less than 100ms). Pretty straightforward.

**Challenge**
Runtime memory + index build time are not concerns for my particular situation. Setting `n_trees` to something large (between 100-1000) and then tweaking `search_k` from there works reasonably well. However, if I just set the params once and forget them, my searches perform differently day-to-day, depending on the structure of the vector space, i.e. the spatial layout of the feature vectors:

_For example, for constant params, some searches can take up to ~800ms or yield less than ideal results (depending on if `search_k` is too high or too low)._

I'm curious if others have employed strategies to automatically tune the params based on some pre-defined criteria? Thanks!

**Comment by erikbern** [comment]
my guess is that the search time when it takes 800ms is due to the page cache being cold and has nothing to do with parameters. basically your index got swapped out to disk and is no longer in ram. maybe try using the prefault flag and/or turn off swapping?

**Comment by erikbern** [comment]
i don't have expert knowledge and i haven't tried this but maybe run `ps -eo min_flt,maj_flt,cmd` as per https://scoutapm.com/blog/understanding-page-faults-and-memory-swap-in-outs-when-should-you-worry and see if there's a lot of page faults
