### ISSUE TITLE
question: pushing two children nodes to priority_queue 

### ISSUE THREAD

**Issue by ncjin** [spotify/annoy#489]
https://github.com/spotify/annoy/blob/7f2562add33eeb217dcdc755520c201aefc1b021/src/annoylib.h#L1280
I cant understand that you push two children node to priority_queue q, rather than the closet one. Pushing two children will traverse the trees, compute all nodes distance, and cost more time.

**Comment by erikbern** [comment]
We want to traverse both, but we want to do it in the best order :)
