### ISSUE TITLE
installing from pypi or pip

### ISSUE THREAD

**Issue by asharma567** [spotify/annoy#49]
src/annoylib.h:39:10: fatal error: 'boost/version.hpp' file not found
#include <boost/version.hpp>

**Comment by asharma567** [comment]
1 error generated.
error: command 'gcc' failed with exit status 1

**Comment by erikbern** [comment]
Did you install Boost?

I'm planning to drop the dependency on Boost fairly soon. It's been causing a lot of issues for people.

http://www.pyimagesearch.com/2015/04/27/installing-boost-and-boost-python-on-osx-with-homebrew/

**Comment by asharma567** [comment]
I remember liking boost a lot when I was a quant on a trading desk! I'll
install it.

I'm trying to use Annoy instead of a BallTree or KDtree which takes too
long to construct and query: 2.5 million documents TFIDF vectorized.

The goal would be to query 100,000 against 2.5 in a reasonable amount of
time.

Would you have any insight?
- Ajay
ᐧ

On Tue, Apr 28, 2015 at 3:59 PM, Erik Bernhardsson <notifications@github.com
> wrote:

> Did you install Boost?
>
> I'm planning to drop the dependency on Boost fairly soon. It's been
> causing a lot of issues for people.
>
>
> http://www.pyimagesearch.com/2015/04/27/installing-boost-and-boost-python-on-osx-with-homebrew/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/annoy/issues/49#issuecomment-97253536>.
>



-- 
Github <https://github.com/asharma567/> | LinkedIn
<http://www.linkedin.com/in/mrasharma/>

**Comment by erikbern** [comment]
If you come back in a few days the Boost dependency should be dropped.

Yes you can do that. Note however for TF-IDF if the number of terms is high the nearest neighbor quality might not be perfect. You should probably do a dimensionality reduction (using matrix factorization etc) to a representation with 10-100 dimensions at most.

**Comment by asharma567** [comment]
Interesting, I'll try that approach -- Thanks!
ᐧ

On Wed, Apr 29, 2015 at 11:14 AM, Erik Bernhardsson <
notifications@github.com> wrote:

> If you come back in a few days the Boost dependency should be dropped.
>
> Yes you can do that. Note however for TF-IDF if the number of terms is
> high the nearest neighbor quality might not be perfect. You should probably
> do a dimensionality reduction (using matrix factorization etc) to a
> representation with 10-100 dimensions at most.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/annoy/issues/49#issuecomment-97528513>.
>



-- 
Github <https://github.com/asharma567/> | LinkedIn
<http://www.linkedin.com/in/mrasharma/>

**Comment by erikbern** [comment]
Can you try to install from PyPI now? The newest version (1.1.0) should not depend on Boost (thanks to @dvenum)

**Comment by dvenum** [comment]
It's work for me. Debian 8.

**Comment by asharma567** [comment]
works pypi works : OSX

On Wed, Apr 29, 2015 at 6:03 PM, Erik Bernhardsson <notifications@github.com
> wrote:

> Closed #49 <https://github.com/spotify/annoy/issues/49>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/annoy/issues/49#event-293587378>.
>



-- 
Github <https://github.com/asharma567/> | LinkedIn
<http://www.linkedin.com/in/mrasharma/>
