### ISSUE TITLE
Will this library work in my use-case?

### ISSUE THREAD

**Issue by techytushar** [spotify/annoy#491]
I have a search problem in which I have 10 Million vectors of size 10,000. 

1.  For every search query I have to find the top 5 similar vectors.
2.  I'll have to periodically (15 days) update the index to add new vectors.
3.  There might be multiple requests (40-50) at the same time.

Will this library be able to help in this case? If yes, what will be the server requirements in terms of memory and compute that I'll need for efficient working of this tool.

Any help or suggestions would be highly appreciated.

**Comment by piskvorky** [comment]
Are your vectors sparse? 10k dimensionality sounds pretty extreme. A few hundreds are more typical, for dense vectors.

**Comment by techytushar** [comment]
Yes, the vectors are sparse. They are basically the TF-IDF vectors.

**Comment by piskvorky** [comment]
Sparse is not a good fit for Annoy. Are you able to compress your vectors first into dense, with something like SVD maybe?

**Comment by techytushar** [comment]
Please can you tell some problems that I might face in production if I use annoy with sparse vectors? I did an experiment on 200,000 data points and it seemed to work fine, also the inference time was fairly fast.
I also tried compressing the vectors, but that resulted in accuracy drop.
