### ISSUE TITLE
Parallel query

### ISSUE THREAD

**Issue by pvnieo** [spotify/annoy#499]
Hi,

Thank you for the great library.

While using Annoy, I noticed that because the querying is done by element, If I want to query a lot of element, the only solution is to do it in a linear way, and use only 1 core, which is a time consuming.

Is there a way to query multiple elements in parallel? I tried using `multiprocessing` and `joblib`, but I failed because it's unpickable.

Thank you in advance.

**Comment by novoselrok** [comment]
There is no native way to do parallel queries, as far as I know. Perhaps you can try it like this: https://github.com/pavlin-policar/openTSNE/blob/872e8df89d7700bc650e1c2b40a41c0c5a9c1a54/openTSNE/nearest_neighbors.py#L264-L268

**Comment by pvnieo** [comment]
Hi,
Thank you for your response. I tried your proposition, but it doesn't speed up the search. Actually, it's also using one core.

**Comment by erikbern** [comment]
There's a bunch of ways

1. Use multiple threads
2. Use multiple processes, and load the index from disk from each process
