### ISSUE TITLE
Parameters to get annoy to behave as more of an exhaustive search

### ISSUE THREAD

**Issue by abal6725** [spotify/annoy#503]
Hello,

I have a rather odd question that perhaps beats the whole point of annoy, but I would like to know what parameters could be used to get annoy to behave as an an exhaustive search as apposed to approximate. I have a use case where I need to do both approximate and exhaustive search and was wondering if I could get annoy to do both? Thanks in advance for the help!

**Comment by erikbern** [comment]
you could set `search_k` to some very large value (like 2<<31-1 which is the max signed int) and it will basically do this

**Comment by abal6725** [comment]
Thanks for the help!
