### ISSUE TITLE
Distance order

### ISSUE THREAD

**Issue by MonkeyChap** [spotify/annoy#504]
Hi,

This isn't an issue, but I couldn't find a discussion forum for Annoy...so apologies.  

Is there a way to get all the pairs of items, sorted by distance ? i.e. Instead of trying to find the NN for a given item, I just want to know which (for example) 10 vectors are the shortest, or longest. I can always loop over the index, but that seems a little wasteful.

PS - if there is a discussion site for Annoy, please do point me at it.

Thanks

Ian

**Comment by erikbern** [comment]
sorry, there's no way to do that
