### ISSUE TITLE
How to install annoy and ues the c++ interface？

### ISSUE THREAD

**Issue by HLH13297997663** [spotify/annoy#505]
I want to ues the c++ interface, how to install ?

**Comment by novoselrok** [comment]
To install, you just need to clone the repository in your project and #include it.

Take a look at the `examples` directory:
* Example usage: https://github.com/spotify/annoy/blob/master/examples/precision_test.cpp
* How to compile: https://github.com/spotify/annoy/blob/master/examples/s_compile_cpp.sh

**Comment by erikbern** [comment]
Thanks @novoselrok! Closing this
