### ISSUE TITLE
Error occur when I run c++ code

### ISSUE THREAD

**Issue by HLH13297997663** [spotify/annoy#507]
Hello, I #include "annoylib.h" in my c++ project and used code "AnnoyIndex<int, double, Angular, Kiss32Random, AnnoyIndexMultiThreadedBuildPolicy> t = AnnoyIndex<int, double, Angular, Kiss32Random, AnnoyIndexMultiThreadedBuildPolicy>(f);"  in the main function, but got the error below:

error C2065: 'AnnoyIndexMultiThreadedBuildPolicy': undeclared identifier
error C2923: 'AnnoyIndex': 'AnnoyIndexMultiThreadedBuildPolicy' is not a valid template type argument for parameter 'ThreadedBuildPolicy'

What am I supposed to do?

**Comment by novoselrok** [comment]
Can you copy the instruction you are using to compile your C++ project?

**Comment by HLH13297997663** [comment]
> Can you copy the instruction you are using to compile your C++ project?
Hello, I use the Visual Studio 2019 default compiler to compile the code
(1)This is my code：
#include <iostream>
#include <iomanip>
#include "../opencv2/opencv.hpp"  
#include "../opencv2/xfeatures2d.hpp"
#include "kissrandom.h"
#include "annoylib.h"
#include <chrono>
#include <algorithm>
#include <map>
#include <random>

using namespace cv;
using namespace std;

int main() {
    int f = 40;
    AnnoyIndex<int, double, Angular, Kiss32Random, AnnoyIndexMultiThreadedBuildPolicy> t = AnnoyIndex<int, double, Angular, Kiss32Random, AnnoyIndexMultiThreadedBuildPolicy>(f);
	return 0;
}


(2)This is the error:
1>------ Build started: Project: ConsoleApplication1, Configuration: Debug x64 ------
1>ConsoleApplication1.cpp
1>C:\Users\Acer\source\repos\ConsoleApplication1\ConsoleApplication1\ConsoleApplication1.cpp(21,52): error C2065: 'AnnoyIndexMultiThreadedBuildPolicy': undeclared identifier
1>C:\Users\Acer\source\repos\ConsoleApplication1\ConsoleApplication1\ConsoleApplication1.cpp(21,5): error C2923: 'AnnoyIndex': 'AnnoyIndexMultiThreadedBuildPolicy' is not a valid template type argument for parameter 'ThreadedBuildPolicy'
1>C:\Users\Acer\source\repos\ConsoleApplication1\ConsoleApplication1\ConsoleApplication1.cpp(21,139): error C2065: 'AnnoyIndexMultiThreadedBuildPolicy': undeclared identifier
1>C:\Users\Acer\source\repos\ConsoleApplication1\ConsoleApplication1\ConsoleApplication1.cpp(21,92): error C2923: 'AnnoyIndex': 'AnnoyIndexMultiThreadedBuildPolicy' is not a valid template type argument for parameter 'ThreadedBuildPolicy'
1>C:\Users\Acer\source\repos\ConsoleApplication1\ConsoleApplication1\ConsoleApplication1.cpp(21,92): error C2955: 'AnnoyIndex': use of class template requires template argument list
1>F:\SofewareSet\faiss\install_package\other\annoy-master\src\annoylib.h(841): message : see declaration of 'AnnoyIndex'
1>C:\Users\Acer\source\repos\ConsoleApplication1\ConsoleApplication1\ConsoleApplication1.cpp(21,90): error C2512: 'AnnoyIndex': no appropriate default constructor available
1>F:\SofewareSet\faiss\install_package\other\annoy-master\src\annoylib.h(841,3): message : see declaration of 'AnnoyIndex'
1>Done building project "ConsoleApplication1.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by novoselrok** [comment]
Can replace the usages of `AnnoyIndexMultiThreadedBuildPolicy` with `AnnoyIndexSingleThreadedBuildPolicy` in your code, and try compiling again?

**Comment by HLH13297997663** [comment]
> Can you replace the usages of `AnnoyIndexMultiThreadedBuildPolicy` with `AnnoyIndexSingleThreadedBuildPolicy` in your code, and try compiling again?

Thank you very much, It works.
Is there some API for C + +？

**Comment by zejunwang1** [comment]
use  g++ -DANNOYLIB_MULTITHREADED_BUILD -pthread your-cpp-file -o your-cpp to compile!
