### ISSUE TITLE
Kernel dies when trying to add items ( similar to #446)

### ISSUE THREAD

**Issue by saggu** [spotify/annoy#512]
I am trying to create a Annoy index for the whole Wikidata ( > 1 Billion qnodes).

The issue, as mentioned in #446 , the OS is killing the process when id becomes too big. In this case, it is happening around 1 billion mark.

Is there any planned solution for this ?

**Comment by erikbern** [comment]
you're probably just running out of memory :(

**Comment by saggu** [comment]
Could be, I can try this on a bigger machine with more than 32GB RAM. Will report back.

However, I did notice OS is killing the process when I try to use an id > 10000000

**Comment by saggu** [comment]
I think I may have mislead, I am trying to create an Annoy index with a sample of 240K qnodes first. Eventually I would like to build an index with all of Wikidata.

For the 240K qnodes, I changed my id assigning approach (starting with 1) and it works. But if I use a number > 1 billion as id, then it fails

**Comment by erikbern** [comment]
yes makes sense, it will allocate a billion vectors of memory if you do that
