### ISSUE TITLE
Error with example code

### ISSUE THREAD

**Issue by mathisloevenich** [spotify/annoy#514]
I just copied and pasted the code:
```
from annoy import AnnoyIndex
import random

f = 40
t = AnnoyIndex(f, 'angular')  # Length of item vector that will be indexed
for i in range(1000):
    v = [random.gauss(0, 1) for z in range(f)]
    t.add_item(i, v)

t.build(10) # 10 trees
t.save('test.ann')

# ...

u = AnnoyIndex(f, 'angular')
u.load('test.ann') # super fast, will just mmap the file
print(u.get_nns_by_item(0, 1000)) # will find the 1000 nearest neighbors
```

The result is:
```
Process finished with exit code 132 (interrupted by signal 4: SIGILL)
```

I am running this in a virtual environment with python 3.7 which should actually work, I also recognized,
that the crucial part is the method *t.add_item*,  which leads to this problem.

It might be just my computer (7 year old MacBook Air), but I want to share this, in case if it's a new problem.

In any case I would love to hear a reason and a solution for this, if you guys are familiar with this problem.

Best regards
Mathis

**Comment by Sidneys1** [comment]
Happening here in a dockerized environment while running under Celery. SIGILL when calling `get_nns_by_vector`, both with the binary package and built from souce.

**Comment by mathisloevenich** [comment]
Sorry @Sidneys1, but I am not getting it. Do you know a solution for me. 
I have no experience, so it would be nice if you can explain it as detailed as possible.

**Comment by Sidneys1** [comment]
I figured out my issue late yesterday. It seems that by default this compiles with `gcc -march=native`, which allows generation of AVX code, however there seems to be a bug running AVX instructions under Docker on KVM-virtualized machines. Unfortunately, I don't know if this applies to your code.

What you can try is preventing AVX instructions from generating by building `annoy` from source. Edit `setup.py` and change the default `-march=native` to `-march=x86-64`. I also added `-mno-avx`. This tells GCC not to generate extension instruction sets like AVX that aren't supported by *all* x64 processors, and resolved the issue for me.

**Comment by Sidneys1** [comment]
A good way to track down *what* the illegal instruction is is to run `gdb --args python my_code.py` (or attach GDB to a running instance of your code with `gdb -p <python's pid>`) and letting your code continue until the `SIGILL` is met. When this happens, enter `view asm` in GDB and it will show you the assembly for the offending line, which in my case was an AVX instruction.

Good luck! :+1:

**Comment by erikbern** [comment]
thanks for the clarification

i think we need run-time detection of AVX at some point. until then, closing this
