### ISSUE TITLE
Is it natural getting distance 0 when I input vector exist on tree? 

### ISSUE THREAD

**Issue by paper-cat** [spotify/annoy#515]
Hi. I have some issue about distance.

I try to find distance with most near one, which has same vector value.

The same vector is came out from tree but the distance is not 0. Its like 0.00013.... (Im using angular distance)

Is It natural? Or, if I run tree on different OS, is the distance changed? (I build tree on Windows, and run tree on Linux)

**Comment by erikbern** [comment]
Mind sharing the vectors? It's possible there's some rounding error. `float` doesn't have super great precision

**Comment by paper-cat** [comment]
> Mind sharing the vectors? It's possible there's some rounding error. `float` doesn't have super great precision

Sure. It was like,
[ 0.5919957   4.992956    6.681292    5.1266212  -3.02988    -3.9802523 
  -0.3386706   1.222729   -5.988745   -8.597135   -6.6439147  -2.466082 
  15.865893   -6.7283344   4.017529   -5.145651    6.757753    2.005116 
   1.2858996   7.5490704   2.318944   -0.4962753  -3.2094913   0.5795827 
  -1.7032346  -2.659414    0.15874588 -1.425204    2.7710829   3.4158878 ]

So do you recommend not to use float because of rounding error? Or any other suggestion?

**Comment by erikbern** [comment]
there's no way to not use float

i don't think this is a big problem in practice – it's a small rounding error
