### ISSUE TITLE
Unable to build Annoy 1.7.0 on Ubuntu 20.04.1 LTS

### ISSUE THREAD

**Issue by mpenkov** [spotify/annoy#516]
I'm encountering a strange issue building Annoy as part of a Travis CI job.

Using Ubuntu 20.04.1 LTS and gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, I get this while trying to install annoy via pip:

    Python 3.6.8
    Collecting annoy
    Downloading annoy-1.17.0.tar.gz (646 kB)
    Building wheels for collected packages: annoy
    Building wheel for annoy (setup.py): started
    Building wheel for annoy (setup.py): finished with status 'error'
    ...
    ERROR: Command errored out with exit status 1:
    x86_64-linux-gnu-gcc: error: unrecognized command line option '-std=c++14'
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

This seems extremely strange to me, as the version of gcc I'm using (9.3.0) should definitely support `-std=c++14`. I'm out of ideas - is this something that has been reported before?

[Here's](https://travis-ci.org/github/RaRe-Technologies/gensim-wheels/jobs/741274157) the full output of our failing build, in case it contains useful info that I neglected to include directly here.

**Comment by mpenkov** [comment]
We figured out the cause, the build was running inside another container running an older version of gcc.

**Comment by bikegirl** [comment]
How was this issue solved?  Can you elaborate more, I am also having the same error.

**Comment by mpenkov** [comment]
It was over a year ago, so I can't remember all the details, but long story short: There were several layers of Docker involved (yuck...), and we thought the build was running inside one container, when it was running in another (older) one deeper down the rabbithole.

**Comment by dyuan1111** [comment]
Look through all answers regarding this and the consensus is that it is due to the old version of gcc. I am not a root user thus cannot upgrade gcc. However, I found that installing annoy through conda-forge instead of pip successfully installed annoy. 

conda install conda-forge::python-annoy
