### ISSUE TITLE
Dot Product with L2 Norm

### ISSUE THREAD

**Issue by loretoparisi** [spotify/annoy#519]
Is it possibile to add L2 norm to Dot (inner) product like

```python
for v1,v2 in zip(features1,features2):
    n1 = np.linalg.norm(v1)
    n2 = np.linalg.norm(v2)
    outputs.append(np.dot(v1, v2) / n1 / n2)
```

Thank you

**Comment by erikbern** [comment]
it looks like your code is computing the cosine so couldn't you just use the angular distance?

**Comment by loretoparisi** [comment]
@erikbern I'm doing the dot product `np.dot` of normalized values `n1` and `n2` against `v1` and `v2` using `np.linalg.norm`.

**Comment by erikbern** [comment]
ok, I don't really understand the request, but I'm pretty sure you should be able to solve it outside of Annoy
