### ISSUE TITLE
Python equivalent of Angular distance. 

### ISSUE THREAD

**Issue by iamrishab** [spotify/annoy#528]
Annoy uses Euclidean distance of normalized vectors for its angular distance, which for two vectors u,v is equal to `sqrt(2(1-cos(u,v)))`

Based on the above statement, can anyone confirm if the below implementation is the correct `python` equivalent. TIA!

```
def angular_distance(x:np.ndarray, y:np.ndarray):
    distance = np.sqrt(np.sum(np.square(x - y)))
    return np.sqrt(2*(1 - np.cos(distance)))
```

**Comment by Saahil-Agr** [comment]
This is correct only if the two vectors are normalized. So first you need to scale x and y to ensure that their L2 norm is 1.

**Comment by erikbern** [comment]
doesn't look correct to me. in general the dot product of two vectors is |u| * |v| * cos(u, v) so i think what you want is maybe (but i haven't tested it)

cos = np.dot(x, y) / (numpy.dot(x, x) * numpy.dot(y, y)) ** 0.5
return (2 * (1 - cos)) ** 0.5

**Comment by loretoparisi** [comment]
According to the ANN Benchmarks [distance](https://github.com/erikbern/ann-benchmarks/blob/main/ann_benchmarks/distance.py) impl, we have

```python
 distance=lambda a, b: 1 - np.dot(a, b) / (norm(a) * norm(b))
```
