### ISSUE TITLE
What is the 'angular' distance metric?

### ISSUE THREAD

**Issue by stevesmit** [spotify/annoy#530]
Hi there

Thank you for the great library! I had a question about the `angular` distance metric. The Readme doesn't provide a definition for it and I am interested in recovering cosine _similarity_ from it. 

I have assumed that the definition of "cosine distance" in the Readme:

```
Cosine distance is equivalent to Euclidean distance of normalized vectors = sqrt(2-2*cos(u, v))
```

is really the formula that is used by this library for `angular` distance. Can you confirm that? And that if I wanted to recover cosine similarity between the two vectors, I could just transform every distance given as follows:

```
def cosine_similarity_transform(angular_distance):
    return (2-(angular_distance**2))/2
```

**Comment by tomhaber** [comment]
I was just looking into this myself as it's not the cosine distance I expected, which was something like https://docs.scipy.org/doc/scipy-0.16.0/reference/generated/scipy.spatial.distance.cosine.html

 It is indeed the formula in the Readme: sqrt(2-2*cos)
The function you provided does the conversion to cosine similarity and (angular^2)/2 transforms into what scipy and others call "cosine distance".

**Comment by erikbern** [comment]
Great we sorted it out
