### ISSUE TITLE
How to use annoy incrementally?

### ISSUE THREAD

**Issue by johann-petrak** [spotify/annoy#537]
The README says: "After calling build, no more items can be added." 

However, when I run this on Linux, Python 3.6.9, it the library does not complain about adding items after calling build. While one can use the additional items for search, they are apparently not included in the index, so nothing is re-built.  Explicitly invoking build() a second time throws and exception.

```
from annoy import AnnoyIndex
import random

f = 40
t = AnnoyIndex(f, 'angular')  # Length of item vector that will be indexed
for i in range(1000):
    v = [random.gauss(0, 1) for z in range(f)]
    if i == 500:
        remember = v
    t.add_item(i, v)

t.build(20) # 10 trees

# This works without a problem! 
for i in range(1001, 2000):
    v = [random.gauss(0, 1) for z in range(f)]
    if i == 1500:
        v = remember
    t.add_item(i, v)

print("N items:", t.get_n_items())
print("5 neighbors for item 500:\n", t.get_nns_by_item(500,5,include_distances=True))
print("5 neighbors for item 1500:\n", t.get_nns_by_item(1500,5,include_distances=True))

t.save('test.ann')

try:
    for i in range(2001, 3000):
        v = [random.gauss(0, 1) for z in range(f)]
        t.add_item(i, v)
except:
    print("Got exception")
```

So I wonder what the suggested approach is in a situation where new items constantly arrive? I guess this is actually what spotify is confronted with as well?

So I am getting a few hundred new vectors each second and would like to be able to search vectors that have arrived until e.g. one minute ago. 

Do I have to completely throw away everything and re-add everything so I can do a build() on a new AnnoyIndex instance? That sounds like a waste since the existing instance already contains almost all the vectors, just the trees would have to be created again (no idea if those trees could get updated instead, probably not). 

So far I have been talking about an index instance that is in-memory, but apparently saving the instance also causes it go become read-only. So how to do pseudo/block incremental indexing when the index needs to be stored because it gets so big? 

Sorry if this has been asked before but I was unable to find any documentation or other information apart from the README.

**Comment by erikbern** [comment]
Hi @johann-petrak! I think you must have run into some weird undocumented feature that shouldn't work – I'm not sure how it works, but I definitely wouldn't rely on it, and we should probably fix Annoy so you can't add items once the index has been built.

Annoy was never built with the incremental use case in mind, unfortunately. It's possible you can build around it by having different indexes under the hood and running lookups against all of them – depends on your use case.

**Comment by johann-petrak** [comment]
Thank you for clearing this up! 
I think that FAISS is probably a better choice for me (and anyone else who needs updatable indices) then.

**Comment by erikbern** [comment]
interesting, i didn't know FAISS support incremental additions
