### ISSUE TITLE
How does Spotify update their index?

### ISSUE THREAD

**Issue by labriedion** [spotify/annoy#541]
Hi, I've been researching which ANN search implementation would best fit our use case, and from what I understand, it's not possible to update the index in Annoy to include new vectors. My question then is, how does Spotify include new songs and users in their index? Do they frequently recalculate the index? It seems costly when other ANN implementations support indexing new documents.

**Comment by erikbern** [comment]
Yeah just rebuild it with some frequency. I left Spotify 6 years ago but generally new music doesn't appear that frequently (and doesn't have data to support recommendations anyway) so it's totally fine to rebuild it nightly or even less frequently.
