### ISSUE TITLE
The first nearest neighbor is the vector itself?

### ISSUE THREAD

**Issue by beichenc** [spotify/annoy#543]
When using get_nns_by_vector, is the first one in the list returned the vector itself, or the neighbor closest to the vector v?

I found that using small datasets, the first nearest neighbor has a distance of 0.0 which means it must be the vector v itself. But using larger datasets the first nearest neighbor doesn't have distance 0...

**Comment by erikbern** [comment]
Yeah, the get_nns_by_vector doesn't filter out the vector itself. Since it's an _approximate_ search, it will not always find itself when it searches. You might have to increase `search_k` for this to happen.
