### ISSUE TITLE
Python type annotations

### ISSUE THREAD

**Issue by chdsbd** [spotify/annoy#545]
Hi,

Would you accept a pull request to add type annotations? If not, would you be okay with type annotations being added for annoy in http://github.com/python/typeshed?

Also, if type annotations were added, would you want to also type check the annoy tests?

**Comment by erikbern** [comment]
yeah would definitely love to add type annotations – I guess that means we'll have to deprecate older Python versions, but that seems fine to do

**Comment by chdsbd** [comment]
Great. I've opened #548 to add type annotations via stub file. Since the annotations are in a separate stub file we don't need to deprecate older Python versions.
