### ISSUE TITLE
Missing error checks in Python extension code

### ISSUE THREAD

**Issue by JelleZijlstra** [spotify/annoy#546]
The code in https://github.com/spotify/annoy/blob/master/src/annoymodule.cc that interacts with the CPython API mostly doesn't check the return value of called functions. This can lead to crashes:

```
% python -c 'import annoy
class X:
    def __len__(self): return 42
ann = annoy.AnnoyIndex(42)
ann.get_nns_by_vector(X(), 42)
'
<string>:4: FutureWarning: The default argument for metric will be removed in future version of Annoy. Please pass metric='angular' explicitly.
zsh: segmentation fault  python -c 
```
Similarly, calling `get_nns_by_vector()` with a vector of objects that aren't floats throws a `SystemError`.

There are also no checks on the return value of functions like `PyList_New`. In theory, this could lead to segfaults, because the function returns NULL on error. I believe that only happens if the system is out of memory though.

**Comment by erikbern** [comment]
is it easy to fix? sounds worth doing
