### ISSUE TITLE
Enhancement request, add fractional distance

### ISSUE THREAD

**Issue by ivan-marroquin** [spotify/annoy#551]
Hi,

Many thanks for such great package.

I bumped into this research work https://bib.dbvis.de/uploadedFiles/155.pdf, in which the authors propose a fractional distance to deal better with the notion of near/far neighbors in high dimensional data sets. According to their results, the fractional distance can provide better outcomes compared to Euclidean (or Manhattan) distance.

So, I would like to submit this enhancement request: include fractional distance in ANNOY package.

Kind regards,

Ivan

**Comment by ivan-marroquin** [comment]
I think a way to go is to implement the minkowski distance metric.

**Comment by erikbern** [comment]
Feel free to implement it :)
