### ISSUE TITLE
Custom Metric

### ISSUE THREAD

**Issue by Chokerino** [spotify/annoy#553]
Hello,

I wanted to perform NN search on a dataset of genomes. For this task, the distance between 2 datapoints is calculated by a custom script? Is there I can incorporate this without having to create the entire NN search algorithm myself and only modify some parts of your code?

**Comment by emibarrod** [comment]
Did you get a solution for this? I am also trying to use a custom metric

**Comment by Chokerino** [comment]
@emibarrod No

**Comment by emibarrod** [comment]
Sad. Thanks!

**Comment by mannaudur** [comment]
One possible approach is to use MDS (multidimensional scaling) to create a distance matrix which approximates the distances between the elements, derived from the custom script, to Euclidean space of some n dimensions. Then run that data on annoy. This is of course an abstraction of the original data, but perhaps it is applicable.

**Comment by tctco** [comment]
looking forward to this feature
