### ISSUE TITLE
Why angular distance is > 1?

### ISSUE THREAD

**Issue by CristhianBoujon** [spotify/annoy#558]
By definition, cosine distance outcome is neatly bounded in [0,1] but in my case I get 1.64 as max value of two vectors using angular.
I know that cosine similarity is implemented like euclidean distance of normalized vectors for its angular distance but I expect that the range be equal, that is, between 0 and 1.

Am I doing something wrong?

```
f = 100
t = AnnoyIndex(f, 'angular')  # Length of item vector that will be indexed
for domain_id, domain_emb in zip(domain_ids, domain_embeddings):
    t.add_item(domain_id, domain_emb)
t.build(400)


result = []
for a, b in combinations(domain_ids, 2):
    d = t.get_distance(a, b)
    result.append((a, b, d))

r = pd.DataFrame(result)


r[2].max()
#  1.6421096324920654

r[2].min()
#  0.0
```

**Comment by erikbern** [comment]
Euclidean distance of two normalized vectors is within [0, 2] – consider the vectors [-1] and [1]. The _square_ of the distance is within [0, 4]
