### ISSUE TITLE
need help understanding the algorithm

### ISSUE THREAD

**Issue by gasparian** [spotify/annoy#561]
### Intro
I'm trying to re-implement the "annoy-style" lsh search in golang, just for the sake of learning. 
For building a binary search tree, without going deep into details, I use an approach that, as I understood right, has been used in the earlier versions of annoy: 
 - pick up 2 random points;  
 - generate plane between them;  
 - recursively repeat that for both sides of the generated plane;  

[code](https://github.com/gasparian/lsh-search-go/blob/master/lsh/hasher.go#L164).  

I don't keep original "training" points inside trees. I only keep plane coefs there. For each point I'm generating 64-bit hash, by traversing the tree and calculating the plane side where the point lies on, and save it to the provided storage (the simplest option - just a hash map).  

For validation, I'm using 4 datasets from the [ann-benchmarks](https://github.com/erikbern/ann-benchmarks):  
 - fashion mnist (euclidean);  
 - SIFT (euclidean);  
 - NY times (angular);  
 - Glove (angular);  

And it looks like my implementation works "~ok" on datasets with the euclidean distance metric (30x-70x speed up in search time compared to the "exact" nearest neighbors). But when it comes to datasets with angular metric - I got only slightly speed up with the larger decrease in metrics values, I played with parameters like a number of trees and a minimum number of points in a leave - but I keep getting "bad" results (see tables [here](https://github.com/gasparian/lsh-search-go#results)).  

### Questions  
 1. Do I understand right, that during the generation of the trees we should **always** apply l2 normalization on vectors, according to the annoy code? (and do the same for query points before any calculations). I did it only when experimenting with the angular metric (I've experimented with disabling the normalization at all - got a bit worse results, but no significant changes, actually).  
 2. Maybe I miss something, and before starting the validation, should I apply any other sort of preprocessing, like standard scaling? (I don't do anything in the current implementation)  
 3. In the annoy code I saw that for angular metric, there is used a euclidean distance of normalized vectors instead of just regular cosine distance. I experimented with that - seems it doesn't help in my case. But still, what is the motivation for using such an approach if during the validation we have to re-calculate cosine distances anyway (to compare it with ground truth dist.) ?  

### P.S.  
I understand that it can be some issue with my implementation, or maybe a bug or smth. And I keep searching for the root cause, but, still, appreciate any answer ;) And tell if you need any more details.

**Comment by gasparian** [comment]
@erikbern (sorry for mentioning you) I understand that my question is not related to any real issues with annoy...
But maybe you can give advice, or suggest smth to read or another person to ask) Or maybe my questions are not clear enough.

**Comment by erikbern** [comment]
Sounds like you're implementing it correctly. I would encourage you to look at the code.

For angular distance generally the key thing is to normalize everywhere. Also note that the hyperplanes should have no offset, just a vector (whereas hyperplanes in Euclidean distances has an offset as well)
