### ISSUE TITLE
Cannot install annoy in new apple silicon (m1)

### ISSUE THREAD

**Issue by gonzoramos** [spotify/annoy#563]
I am trying to install and use annoy on my mac, but pip install fails. In particular it sems that clang fails.

`clang: error: the clang compiler does not support '-march=native'`

Any tips about how to get things going would be greatly appreciated!

**Comment by erikbern** [comment]
Weird – I have an M1 mac and it works for me to run `pip install annoy`

**Comment by erikbern** [comment]
Any other relevant information?

**Comment by gonzoramos** [comment]
I was able to install it now... weird :/ - closing issue. Thank you!!
