### ISSUE TITLE
Performance degradation in build

### ISSUE THREAD

**Issue by fferroni** [spotify/annoy#565]
Hi,

I was testing this library. I would like to build an index of tens of millions of items that are represented by a 512 feature vector, and thus the on-disk index building functionality seemed interesting; however, I am stuck at the build phase. I am using euclidean distance.

Trying to scale the number of elements in the index (28-core machine):

With 5k items (50 trees), it takes 0.02 seconds.
With 50k items (500 trees), it takes ~5 seconds.
With 500k items (5000 trees), it takes ~1070 seconds.

It doesn't look so good if I want to scale to orders of magnitude larger dataset.

Can you suggest some heuristics on how I can scale the number of trees while still maintaining suitable retrieval accuracy? 

Thanks!

**Comment by erikbern** [comment]
You don't need that many trees. You're probably running up against RAM limits and then it starts to swap.

Try using just 10-50 trees and see what happens?
