### ISSUE TITLE
How can I found how many node I passed

### ISSUE THREAD

**Issue by dlwjddms** [spotify/annoy#566]
Hi, I want to know how many nodes and leaves each tree has. And also want to see how many nodes I pass while searching. Is there any way to do those things?

**Comment by erikbern** [comment]
No but you can set search_k to control how many nodes are searched

**Comment by dlwjddms** [comment]
Hmm so If I set search_k as a  default that means each tree searches same number of nodes? And if I set search_k as 10 each tree searches 10 nodes?

**Comment by dlwjddms** [comment]
Also  with verbose function I was able to print out the total number of nodes.
So, my item number was 12100 
And with 1 tree I could get 12118 nodes= 12100 + 18 which make sense
Ans also with 2 trees I could get 12136 nodes = 12100 + 18 + 18 which also make sense.
But staring from three trees I got 12152 how could this happen?
