### ISSUE TITLE
search become slow when memory decrease 

### ISSUE THREAD

**Issue by ganguagua** [spotify/annoy#569]
I have many annoy_index and some annoy_index will be updated frequently.
Some annoy_index seems to be unload from physical memory when I update other annoy_index, because I see the memory usage decrease. After that, the search become slow.

initial state

![image](https://user-images.githubusercontent.com/28615695/131314865-e8a31a11-aa58-460b-aa4a-2a54a291eb6b.png)

after some annoy_index updated
![image](https://user-images.githubusercontent.com/28615695/131316364-d8b439c3-225b-4628-b4fa-fc5ba94eacb2.png)

I will execute unload firstly when I update the annoy_index.
Did I use it correctly ？

**Comment by erikbern** [comment]
If the index is no longer in RAM, it will be swapped out to disk, and it will be slow – that's right. This is how the Linux page cache works. I don't know any great workaround other than doing random queries against the index to keep the cache "warm"

**Comment by ganguagua** [comment]
> If the index is no longer in RAM, it will be swapped out to disk, and it will be slow – that's right. This is how the Linux page cache works. I don't know any great workaround other than doing random queries against the index to keep the cache "warm"

It's a good idea. Thanks very much.
It would be great if the page cache can be release automatically.
