### ISSUE TITLE
Different results got on different operating systems

### ISSUE THREAD

**Issue by cquzys** [spotify/annoy#571]
Hello,
   I got different results (such as different neighbors) when running Annoy on ubuntu 16(gcc 5.4) and ubuntu 18(gcc 7.5).  I want to ask two questions. First, what is the main reason that different results I got when running Annoy on different operating systems? Second, How can I solve it?

Thank you very much!

**Comment by erikbern** [comment]
The construction of trees is randomized so you might get slightly different result. You can set the seed to the same number if this is very important to fix. Another thought is that if you're having low recall (which is the case when the randomness can have large effects) then try setting `search_k` to a much larger number.
