### ISSUE TITLE
Error when importing annoy undefined symbol: _ZTVN10__cxxabiv120__si_class_type_infoE

### ISSUE THREAD

**Issue by dashbenhur** [spotify/annoy#588]
Hi,
I'm getting this error message below. I've tried the following but still I'm getting the same issue

- https://stackoverflow.com/a/51693840, Not sure whats missing from my manjaro installation, but I've tried setting `extra_link_args = ['-Wl', '--no-undefined', '-lstdc++']`  in `setup.py`
- Tried installing from source
- Tried re-installing python after setting `pacman -S base-devel` as described in https://bbs.archlinux.org/viewtopic.php?id=39935

Not sure where to go from here, any suggestions ?

```
Python 3.9.7 (default, Nov 20 2021, 10:38:40) 
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from annoy import AnnoyIndex
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dashbenhur/.pyenv/versions/3.9.7/lib/python3.9/site-packages/annoy/__init__.py", line 16, in <module>
    from .annoylib import Annoy as AnnoyIndex
ImportError: /home/dashbenhur/.pyenv/versions/3.9.7/lib/python3.9/site-packages/annoy/annoylib.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZTVN10__cxxabiv120__si_class_type_infoE
```

**Comment by erikbern** [comment]
sorry – not sure what's causing this!

**Comment by dashbenhur** [comment]
Resolved by using `anaconda` with `pyenv`. I still can't get it to work with python `3.9.7`
