### ISSUE TITLE
On Disk Build Doesn't Complete With > 60 Million Items

### ISSUE THREAD

**Issue by barrycarey** [spotify/annoy#595]
I've been using v1.16.3 for several years.  I typically build indexes in excess of 200 million items (64 in size).

I upgraded to the latest version to try the multi threaded build.   Index builds in a few minutes with 50 million items (fantastic!).  However, once I increase the size beyond this the building never completes.  There is heavy disk reading for each thread  and minimal CPU usage(see screenshot).  I've let it run for 16 hours with no change. 

I'm unsure if this is related to the on disk build or not.  I don't have enough memory to test in memory. 

OS: Ubuntu 20.04
Py Ver: 3.8

![Screenshot from 2022-05-31 14-14-14](https://user-images.githubusercontent.com/3161456/171256443-762a3dfa-09d9-4343-b7d7-afb40dcea457.png)
![Screenshot from 2022-05-31 14-15-21](https://user-images.githubusercontent.com/3161456/171256597-82256137-83ec-4cc9-ad54-3fa8576e3430.png)

**Comment by barrycarey** [comment]
I kicked off another build 6 hours ago with verbose enabled.  It appears it is still building the index, just extremely slowly.

**Comment by erikbern** [comment]
Are you saying the same code started running much slower upgrading to the latest version? That's quite strange.

**Comment by barrycarey** [comment]
It's significantly faster if I run it with 40 million items.  It's significantly slower if I run it with 50 million. 

I let one build with 60 million items run for 16 hours and it did not complete. 

Here's a gist that mimics what I'm doing. https://gist.github.com/barrycarey/29f6ce820af067ebd69e8ab935d6d1bb

Here's results I get with the example. 

20 million:  113s
30 million: 198s
40 million:  246s
50 million: Not finished after 20 minutes

Not sure if it's useful, but there's a pretty big disparity in resource usage between 40m items and 50m. When building 40m CPU usage per thread is close to 100% with mostly light disk writes.  When doing 50m + CPU usage is around 10% with very high reads. 


**CPU & Disk w/ 50,000,000**
![Screenshot from 2022-05-31 19-06-58](https://user-images.githubusercontent.com/3161456/171298232-fab7de7e-3bc3-4b76-97d8-765887245dac.png)
![Screenshot from 2022-05-31 19-06-52](https://user-images.githubusercontent.com/3161456/171298234-5e7e62af-047c-4656-a839-b9ccc45f9efb.png)

**CPU & Disk w/ 40,000,000**
![Screenshot from 2022-05-31 19-11-31](https://user-images.githubusercontent.com/3161456/171298850-cfd6798d-fb50-4dcb-8446-a1585b16f2f1.png)

![Screenshot from 2022-05-31 19-12-58](https://user-images.githubusercontent.com/3161456/171298842-4b49ce29-9957-4840-8686-6b998597852b.png)

**Comment by erikbern** [comment]
what's happening is most likely that you're running out of RAM at some point right after 40M items and your computer starts swapping. you might want to build with fewer trees (or reduce dimensionality)

**Comment by Lavriz** [comment]
@barrycarey hey! did you solve this issue in the end? I'm planning on using more than 60m data and wondering whether I encounter the same problem

**Comment by barrycarey** [comment]
@Lavriz seems to be memory related. Once I through more memory at it the builds completes
