### ISSUE TITLE
Gcc error while Installing in Docker with python:3.8-alpine as base image

### ISSUE THREAD

**Issue by anmol4210** [spotify/annoy#596]
Hi
I'm trying to install Annoy in my Docker image but unfortunately, I'm getting the below error while installing it. 
![error](https://user-images.githubusercontent.com/23002352/173231561-6c1e12b9-e426-461d-b975-c32ee8917591.PNG)

Does anyone have any idea what's this error and how to resolve it?

My Docker File:

`FROM python:3.8-alpine

RUN sed -i 's/https/http/' /etc/apk/repositories

RUN apk --no-cache add lapack libstdc++ && apk --no-cache add --virtual .builddeps g++ gcc gfortran musl-dev lapack-dev git

RUN apk update && apk upgrade && apk add curl gcc g++ gnupg unixodbc-dev python3-dev libc-dev libffi-dev musl-dev openblas

RUN apk update && apk upgrade
RUN apk add -f

COPY . /app
WORKDIR /app

RUN pip3 install --trusted-host pypi.org --trusted-host files.pythonhosted.org annoy==1.17.0`

Any help would be great.

**Comment by erikbern** [comment]
should probably add `-fpermissive` to the gcc flags. i can do that.

**Comment by rtf-const** [comment]
Shouldn't this PR be merged and new version published to PyPi. Build is broken now.
I hope this project isn't abandoned

**Comment by erikbern** [comment]
Thanks for the ping. I'll push a new version to PyPI
