### ISSUE TITLE
How to prevent add_item from printing progress?

### ISSUE THREAD

**Issue by Deesus** [spotify/annoy#600]
When adding an item, `a.add_item(i, v)`, Annoy prints out the progress. So, if I were to add multiple items, I get something like this:
```
1/1 [==============================] - 0s 72ms/step
1/1 [==============================] - 0s 62ms/step
1/1 [==============================] - 0s 71ms/step
1/1 [==============================] - 0s 71ms/step
```
Is there a way to prevent Annoy from printing this? If I'm running a Jupyter notebook, it looks very unpleasant to have a long list taking up so much notebook space.

**Comment by erikbern** [comment]
Annoy doesn't print anything by default, although there's an (undocumented) function `.verbose(bool)` you can use. Maybe you're turning verbose mode on somewhere?
