### ISSUE TITLE
Size of index dimensions

### ISSUE THREAD

**Issue by MartinPedersenpp** [spotify/annoy#601]
Hello

I have found posts like this one: https://github.com/spotify/annoy/issues/148
when searching for material for a project I am doing of a similar size.
@erikbern mentions that when the dimensions go above 1000 it might not be feasible for the ANNOY index.
Has there been any benchmarks or where would I go about researching how large I could go with the dimensions or how small I could make the dimensions when searching for feature vectors before losing detailed information?

**Comment by erikbern** [comment]
It works quite well even for 1000 – you can take a look at https://github.com/erikbern/ann-benchmarks/ for instance

**Comment by MartinPedersenpp** [comment]
Thank you @erikbern 
As far as I can see, the biggest dimension used in the benchmark of Annoy is Fashion-mnist-784 dimensions where it performs alright, but good to known and thanks for the link!
