### ISSUE TITLE
Batch processing hundreds of .ann files to save memory ?

### ISSUE THREAD

**Issue by TylerRankin** [spotify/annoy#602]
I have a search engine (azure web app) that is restricted to 35gb of memory. My .ann file is 50gb, so im thinking of creating 100 or so .ann files and looping through them, taking the top 5 results of each file and sorting after. Is this logical or am I missing something ? Thanks a ton.

**Comment by johnjamespj** [comment]
You can read Annoy Index from disk without loading it into memory. This is the default behavior for annoy. Index is only read to the memory if index.load(filename, prefault=True) but prefault's default value is false. [Read More About index.load here](https://github.com/spotify/annoy#full-python-api)

**Comment by erikbern** [comment]
I don't think it will be more efficient than just creating a 50GB file. Basically it will be very slow either way. When the index doesn't fit in memory, you're going to have to hit disk, and that's going to be slow.

Ideally you can find some way to fit it in memory, maybe by using fewer trees, or smaller dimensionality.

**Comment by TylerRankin** [comment]
Thanks Erik, I really appreciate your response. Im using pretrained transformer model from SentenceTransformers so I could compromise and switch models which would downsize dimensionality back from 768 to 362. Ill tune down the trees from 500 until the recall (compared to exhaustive search) takes a hit that im not comfortable with.

In the long run, I am going to to need a clever way to pre filter "garbage" sentences. Ill update my findings in case anyone else stumbles across this question.

**Comment by erikbern** [comment]
500 trees sounds like a lot. I would recommend setting the trees to the max number you can afford (e.g. when you hit the memory capacity) and then set search_k to whatever works with your performance/accuracy tradeoff

**Comment by erikbern** [comment]
Smaller dimensionality might also help!
