### ISSUE TITLE
Possible set_seed() regression in 1.17.0

### ISSUE THREAD

**Issue by willsthompson** [spotify/annoy#603]
One of our internal tests to verify consistency across seeded indexes failed after upgrading from 1.16.3 to 1.17.0. Our test is similar to your seeding test in the sense that it compares things we build based on calls to `get_nns_by_vector()`, but the simplest thing I could build to demonstrate the behavior change was comparing the serialized indexes directly.

Using 1.16.3 the indexes always match, but in 1.17.0 they _almost_ always fail to match (larger n_trees values fail more reliably).

```python
import numpy as np
from importlib.metadata import version
from annoy import AnnoyIndex
from tempfile import NamedTemporaryFile

data = np.array([
    [-0.16666666666666666, 0.5555555555555556, 0.6],
    [0.8333333333333334, -0.4444444444444444, -0.4],
    [0.16666666666666666, 0.5555555555555556, 0.0],
    [0.8333333333333334, -0.4444444444444444, 0.0],
    [0.8333333333333334, -0.6666666666666666, 0.0],
    [0.8333333333333334, 0.5555555555555556, -0.4],
    [0.8333333333333334, -0.4444444444444444, 0.0]
])


def build_seeded_index(X, seed=1234, n_trees=10, metric="manhattan"):
    index = AnnoyIndex(X.shape[1], metric)
    index.set_seed(seed)
    for i, key in enumerate(X):
        index.add_item(i, X[i, :])
    index.build(n_trees)
    return index


def get_index_bytes(index):
    with NamedTemporaryFile() as tf:
        index.save(tf.name)
        with open(tf.name, 'rb') as f:
            return f.read()


@pytest.mark.parametrize("repeat", range(10))
def test_seed(repeat, n_trees=10, X=data):
    print(version('annoy'))

    index1 = build_seeded_index(X, n_trees=n_trees)
    index1_bytes = get_index_bytes(index1)
    index2 = build_seeded_index(X, n_trees=n_trees)
    index2_bytes = get_index_bytes(index2)

    assert index1_bytes == index2_bytes
```

Please let me know if there's anything else I can do to help troubleshoot.

**Comment by erikbern** [comment]
That's pretty odd. But maybe it's because building trees is threaded now? If you can, try to run `build` with `n_jobs=1` and see if the indexes are still not deterministic

**Comment by willsthompson** [comment]
Yep, that seems like it. With `n_jobs=1` the comparison didn't fail in 10k iterations. I missed that 1.17 defaults to multithreaded. We want to run single-threaded anyway, so I think we should be unaffected after setting that param. Thanks for bringing that to my attention.

**Comment by erikbern** [comment]
Great!

**Comment by willsthompson** [comment]
Would you consider keeping this open as a low priority? We're not blocked now, but threading seems like a great future opportunity to reduce latency when needed, and I suspect more users will eventually run into it if they haven't already (and maybe haven't noticed). I understand it's and edge of an edge, though.

**Comment by erikbern** [comment]
I would rather close it out. But maybe the "fix" to this is just to add something to the README to warn about it?
