### ISSUE TITLE
Using ANNOY with complex numbers?

### ISSUE THREAD

**Issue by MartinPedersenpp** [spotify/annoy#608]
Hi
I saw somewhere that ANNOY uses Float32 internally as datatype so that is probably why I am getting this error.
I am trying to build an index of feature vectors extracted from a 2D Fourier transforms of depth images.
I can add all the values to the index and build it, but when I want to perform a query, I get met with a :

> ComplexWarning: Casting complex values to real discards the imaginary part

Warning. Which in turn results in my query returning empty.
Is there any way to use a complex datatype with annoy or do I have to convert my feature vector to real numbers before adding them?

Best regards
Martin

**Comment by erikbern** [comment]
Sorry, it doesn't support complex numbers. You *might* be able to recompile the C++ code with complex numbers instead of floats (it's templatized over it) but I have no idea if it will work :)

**Comment by MartinPedersenpp** [comment]
> Sorry, it doesn't support complex numbers. You _might_ be able to recompile the C++ code with complex numbers instead of floats (it's templatized over it) but I have no idea if it will work :)

👍🏼👍🏼
