### ISSUE TITLE
Anyway to adapt this to lookup orthogonal vectors.

### ISSUE THREAD

**Issue by henrycharlesworth91** [spotify/annoy#610]
I noticed there is an option to use metric='dot', based on the paper: https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/XboxInnerProduct.pdf that looks to maximise dot products between the query and the returned indices. I was wondering if there is anyway to adapt this to my problem case where I want to lookup vectors that have a dot product close to 0 with the query (i.e. are orthogonal to the query)? I guess this is the same as minimising | x.q |

**Comment by erikbern** [comment]
Sorry, there's no way in Annoy. Not sure how that query would work actually – the subspace that's orthogonal to a certain vector is large and kind of cuts through the whole space
