### ISSUE TITLE
Memory leak while using concurrent.futures

### ISSUE THREAD

**Issue by evanokeeffe** [spotify/annoy#617]
Using the Annoy library and building the index for some 3D data. 

I'm then using ProcessPoolExecutor from concurrent.futures to distribute some queries across processes. 

in the function that is called I call the mmap file like so

t = AnnoyIndex(3,'euclidean')
t.load(filename) # super fast, will just mmap the file

and then it loops through some queries calling  t.get_nns_by_vector(v, neighbours, include_distances=True)

the query results are written to a memory mapped file, which works fine but I've noticed that on larger datasets the 
memory usage is going up and up until it fills 32GB and then all the swap space too. This method shouldn't be doing this,
the memory is suppose to be stable after the initial large result memory mapped array is created. 

I did a memory profile and this line is generating the excess memory 
Mem Usage              Occurrences     Line Contents
345484.652 MiB       58152                 idx,dists = t.get_nns_by_vector(v, neighbours, include_distances=True)

I unload the index at the end using this 
t.unload()
del t
t = None

but my memory usage just keeps climbing.

I've tried Process and Threads but same outcome

**Comment by erikbern** [comment]
That's super strange – I haven't seen anything like it. Do you have any more details?

**Comment by evanokeeffe** [comment]
So I've tried to free the memory usage per process using gc.collect() .
Using this with a single process per chunk of queries doesn't increase the memory, using 8 workers and the same gc.collect, my memory usage goes up by 100MB per iteration 

Think this might be more of an issue with how processes release memory after being called

**Comment by evanokeeffe** [comment]
here's a breakdown on what I'm doing.

I build a tree for some data.

I then use concurrent.futures.ProcessPoolExcutor with a max worker of 8 at the moment. I submit the queries as batches to a function that does some calculations.

in the function I create the annoyIndex , load the already built tree and call get_nns_by_vector(v, neighbours, include_distances=True) for each query in that batch

I then unload the index and return

Testing the function by itself sequentially, I see no changes in the memory used. I ran it for a long time to check.
 
But once I add more processes, using this function starts to increase the memory usage over time. 

Is there anything I need to do to cleanup after loading the memmap index and calling get_nns_by_vector a bunch of times?

**Comment by evanokeeffe** [comment]
Apologies,  this is actually a python issue. Python processes and threads will not release memory back to the OS until the main process has ended.

The issue doesn't occur when using C++, so not an issue with the library
