### ISSUE TITLE
Time complexity

### ISSUE THREAD

**Issue by jianshu93** [spotify/annoy#618]
Hello Team,

What is the theoretical time complexity of annoy, in terms of finding K neighbors of each element in the database, compare to K-graph? It is widely used. However I never see a theoretical analysis.

Thanks,

Jianshu

**Comment by erikbern** [comment]
There is no theoretical complexity – frankly it's more of an empirical science

**Comment by jianshu93** [comment]
I am very confused about this then. how should I compare it with nns algorithms that have a detailed time complexity analysis. For example，hnsw，N*log（N）for building and log（N）for search？ There must be a limiting step.

Thanks，

Jianshu

**Comment by erikbern** [comment]
I don't think there's any such complexities for high dimensional search algorithms. It's really more of an empirical science.
