### ISSUE TITLE
Add method or parameter for returning (itemid, score) tuples

### ISSUE THREAD

**Issue by a1k0n** [spotify/annoy#62]
It would be nice to be able to iterate over a `get_nns` call with not just the itemid but the score also, especially as it's available to the C++ code; currently you have to reconstruct the score manually by normalizing and taking your own dot product in numpy or something.

**Comment by erikbern** [comment]
yes this would be great to add as a new method. can you do it :)

**Comment by a1k0n** [comment]
I'm just relaying a request from your annoy-users@ mailing list. Are you on it?

**Comment by erikbern** [comment]
Just realized I haven't been seeing annoy-user emails.

I was registered using my spotify email and then when I signed up again I accidentally hit the "don't send me updates" option. Fixed now so I'll keep an eye on the email list going forward!

**Comment by erikbern** [comment]
See #93 – should resolve this issue

**Comment by erikbern** [comment]
Although instead of returning a list of tuples, I return a tuple with two lists. Made the code marginally simpler

**Comment by a1k0n** [comment]
Yeah, that makes sense. More compact in memory too. Cool, thanks Erik.
