### ISSUE TITLE
a.load() taking > 30 seconds on 13GB file (Linux based azure web app with 32GB memory) 

### ISSUE THREAD

**Issue by TylerRankin** [spotify/annoy#620]
Hi Erik!  

For reasons beyond my level of understanding using a.load() to load in .ann file from Azure Storage (which supposed to act as fast as local drive) is taking really long. I played with setting prefault=True which significantly sped up getting nearest neighbors without effecting load-in time much.

I need to load in, compute and load out because the sum of the size of the 8 Annoy files I use are > memory limit of 32 gb. 

On my 8gb RAM laptop running windows the same load takes 0.00445 seconds, so am I wondering if Linux may be refusing to MMAP and instead writing to disk? Or perhaps it is not possible to MMAP from Azure Blob Storage even if it is mounted to the web app?

Running some speed tests loading in different sized .ann files:
3GB file: 10 seconds
12GB file: 30 seconds
13GB file: 45 seconds

Any help is extremely appreciated and thank you for the continued support on this project!

Some info on the web app plan:
![image](https://user-images.githubusercontent.com/59891679/208224557-8a4a9e20-d980-44c6-94bc-431a5b67f3c2.png)

Dockerfile:
![image](https://user-images.githubusercontent.com/59891679/208225603-5216c6b4-649b-44b4-8375-72f492fd9051.png)

**Comment by erikbern** [comment]
weird – is it the load call in itself that takes 30s or does that include searching the index?

**Comment by TylerRankin** [comment]
> weird – is it the load call in itself that takes 30s or does that include searching the index?
Thanks for the quick response!

Strictly the local call is slow.  Searching of index and unloading are both very fast:

![image](https://user-images.githubusercontent.com/59891679/208263065-4799dd35-0a97-468a-9782-1077033fa818.png)

![image](https://user-images.githubusercontent.com/59891679/208262997-b1da4a53-4005-44c0-839b-f4a99f8b1ce7.png)

 My fear is that it may be a latency issue with Azure blob storage when loading the annoy file. The App and Blob Storage are connected through a Virtual Network. Additionally, the storage is mounted in the App settings.... so I dont know if I can conclude that it is a latency issue due to the nature of Azure Storage quite yet... I did my due diligence of reading though all the Closed Issues and couldn't find anyone with the same problem.  Any ideas?

**Comment by erikbern** [comment]
I'm not sure how mmap works with different file systems, but my guess is that something with your situation causes the whole index to be read into memory, as opposed to the expected behavior, which is that the page cache reads the data lazily

**Comment by TylerRankin** [comment]
> I'm not sure how mmap works with different file systems, but my guess is that something with your situation causes the whole index to be read into memory, as opposed to the expected behavior, which is that the page cache reads the data lazily

I believe that is the case as well, but I dont know the cause. I saved the .ann files to the local disk drive of the web app, and the files are even slower to load in than the Mounted azure storage... do you think that Azure's dynamic or local cache features could have anything to do with it? 
https://github.com/projectkudu/kudu/wiki/Configurable-settings#turning-on-the-dynamic-cache-feature

Highly unlikely to be a Django setting because everything works perfectly locally. I created the .ann files on windows machine but I dont see why that would matter.

**Comment by erikbern** [comment]
Sorry, I'm not really sure what's the issue. If you save it to local disk, then loading should in theory be very fast.

**Comment by TylerRankin** [comment]
> Sorry, I'm not really sure what's the issue. If you save it to local disk, then loading should in theory be very fast.

Loading from local disk and not azure storage is actually very fast if prefault=False (less than a second). But the computation now takes 30 seconds even with a very low nearest neighbours (10) and search_k (tried 10000, 100 and 10 with minor difference). 

Ive read a lot of suggestions about warming up the index as alternative to Prefault=True, but in my case I need to load in, compute, and unload quickly to clear memeory, so does this warm index become redundant after using unload() ?. Is there any recommendations for my situation? Is what I described still abnormal behavior? Thanks so much for your time! Your dedication to this project means a lot :)

**Comment by erikbern** [comment]
There's no great solution to the situation you described, since fast lookups basically depends on having the index in RAM (not on disk). Unfortunately high dimensional nearest neighbors require a lot of lookups so it's hard to do that with slow memory access :(

**Comment by TylerRankin** [comment]
Thanks Erik,

I appreciate the insights, if I figure out how to speed up the load in from Azure Storage ill leave a comment :). Looking like the "local" storage goes to Azure Storage past 2GB, so there is some distance between App and Files even in same Virtual Network.
