### ISSUE TITLE
Decrease memory usage by decreasing the number of trees, or decreasing dimensionality?

### ISSUE THREAD

**Issue by gusgordon** [spotify/annoy#622]
I have about ~1m vectors I would like to search through, each with 1000 dimensions. Ideally, I would like to keep the size of the index under 500mb. I believe I have two levers to pull for allowing the index to fit in memory:

1. Reduce the number of trees. For example, in my testing, reducing the # of trees from 70 to 10 cut the memory usage in ~half.
2. Reduce dimensionality. For example, reducing dimensionality from 1000 to 500 to also cut the memory usage in ~half. I could do something like `TruncatedSVD` ([sklearn docs](https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.TruncatedSVD.html)) to do this (but lmk if there's a better method).

Of course, I could also do some combination of these two. What are the tradeoffs between both methods of reducing memory usage?

**Comment by erikbern** [comment]
If you can decrease dimensionality in some way (using some sort of dimensionality reduction) then that's probably better. 1000 is a fair amount (although not outrageous) so if you can get it down to like 100, that would save a _lot_ of memory!
