### ISSUE TITLE
Error when trying to install on mac 13.1, intel cpu with python 3.11.1

### ISSUE THREAD

**Issue by dk8827** [spotify/annoy#626]
I am trying to install annoy on mac os 13.1 with Python 3.11.1
`pip3 install --user annoy`

and i get this error:

Collecting annoy
  Using cached annoy-1.17.1.tar.gz (647 kB)
  Preparing metadata (setup.py) ... done
Installing collected packages: annoy
  DEPRECATION: annoy is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for annoy ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for annoy did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      WARNING: The wheel package is not available.
      running install
      /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-cpython-311
      creating build/lib.macosx-10.9-universal2-cpython-311/annoy
      copying annoy/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/annoy
      copying annoy/__init__.pyi -> build/lib.macosx-10.9-universal2-cpython-311/annoy
      copying annoy/py.typed -> build/lib.macosx-10.9-universal2-cpython-311/annoy
      running build_ext
      building 'annoy.annoylib' extension
      creating build/temp.macosx-10.9-universal2-cpython-311
      creating build/temp.macosx-10.9-universal2-cpython-311/src
      /usr/bin/clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c src/annoymodule.cc -o build/temp.macosx-10.9-universal2-cpython-311/src/annoymodule.o -D_CRT_SECURE_NO_WARNINGS -fpermissive -march=native -O3 -ffast-math -fno-associative-math -DANNOYLIB_MULTITHREADED_BUILD -std=c++14 -mmacosx-version-min=10.12
      clang: error: the clang compiler does not support '-march=native'
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> annoy

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by magahernandez** [comment]
I also had this error with Monterey v12.6. Then when I upgrade to Ventura v13.1, I still had exactly the same error

**Comment by erikbern** [comment]
Interesting – maybe I need to take a look at Python 3.11!

**Comment by doublethefish** [comment]
Also getting this with `Python 3.10.10` on Monteray but with homebrew clang:

```
clang++ --version
Homebrew clang version 16.0.1
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
```

**Comment by erikbern** [comment]
Looks like the solution is to avoid `-march=native` for clang 14 on M1: https://stackoverflow.com/questions/65966969/why-does-march-native-not-work-on-apple-m1

Let me see if it's easy to add

**Comment by doublethefish** [comment]
Just to be clear, Apple-M1/M2 are fine, it is Apple-Intel that does not work.

**Comment by doublethefish** [comment]
Any chance of getting a version with this fix published?

**Comment by erikbern** [comment]
OK, done!
