### ISSUE TITLE
How many trees should I use?

### ISSUE THREAD

**Issue by Maxl94** [spotify/annoy#630]
Hi,

can you provide a rule of thumb how many trees one should select for `n` features and `m` samples and `x` different classes?

I have around 3.9 mio samples, that belong to 300k classes with about 12k features. I don't know if I should chose, 10 trees, 100 oder maybe 10k.

Thanks for your help.

**Comment by erikbern** [comment]
the higher number, the better – it depends on your time/memory budget. somewhere between 10 and 100 is usually good, but if you can afford it, go higher!

**Comment by Maxl94** [comment]
Thanks!
