### ISSUE TITLE
Add sample weights to distance metric?

### ISSUE THREAD

**Issue by Xunius** [spotify/annoy#638]
Hi all,

I'm experimenting `annoy` to speed up my search function implemented in `numpy`, and it is giving me a HUGH boost in performance. However, I'd like to give different weights to the different dimensions when computing, for instance, the Manhattan distance. Is it possible to achieve this in current versions of `annoy`? 

Thanks in advance.

**Comment by erikbern** [comment]
Sorry, there's no such functionality!

**Comment by jiangweiatgithub** [comment]
This would be a great feature to have!

**Comment by jiangweiatgithub** [comment]
Some related discussion on Stackechange:
https://datascience.stackexchange.com/questions/6786/weighted-k-nearest-neighbor-search#:~:text=If%20you%20want%20to%20weight%20one%20dimension%20higher,metric%20and%20leave%20the%20most%20important%20dimension%20un-scaled.
