### ISSUE TITLE
_Vector should use position-only parameter for the index

### ISSUE THREAD

**Issue by adampauls** [spotify/annoy#646]
Pyright complains when calling `.add_item(i: int, v: list[float])`. I think the error is the same as the one discussed [here](https://github.com/microsoft/pyright/issues/3116): Pyright demands that `__getitem__` be a position-only parameter, i.e. the signature for `__getitem__` in `_Vector` needs a `/`.

**Comment by erikbern** [comment]
I'm confused – what are you suggesting we should change? Thanks

**Comment by adampauls** [comment]
Or, according to the linked bug, 
```python
class _Vector(Protocol, Sized):
    def __getitem__(self, __index: int) -> float: ...
```

should also work.
