### ISSUE TITLE
How do you reduce a vector to 2 coordinates

### ISSUE THREAD

**Issue by JeremyMahieu** [spotify/annoy#647]
I see in the readme you have an image with essentially a 2D map (+a color) of vectors. What python function can you use to get the x and y coordinates to draw such a map?

My best guess is that you use the distances you get for (at least) two elements and draw the points like that. (The three first points would have to be placed on the 2D map arbitrarily. This would define the scale and rotation of the map. Which can later be rescaled.)
Could a feature of this library be that a function would exist to give such 2D coordinates?

**Comment by erikbern** [comment]
You could use something like this maybe: https://umap-learn.readthedocs.io/en/latest/
