### ISSUE TITLE
Regarding updating an existing ANNOY model

### ISSUE THREAD

**Issue by shina181** [spotify/annoy#655]
Hey,

I wanted to know if there is way to update an existing ANNOY model. 
For instance, I have about a million entries on which my ANNOY model is already trained and saved to the disk. Now I have say 100 newer entries and wish to update the training to account for the newer examples, but not re-train from like scratch, is that possible?

Thanks in advance :)

**Comment by pogzyb** [comment]
I was going to ask the same question :)

This is what I've come up with so far. Not sure if this is a good pattern or if I'm doing it wrong, so I'd like to hear it from someone else. 

Pretty much I just take the vectors from the original loaded index and add them to a new one. After which you can append your new stuff.

![Screenshot from 2023-07-26 08-16-05](https://github.com/spotify/annoy/assets/12061211/2b6f0fa8-8c87-4aa2-95fb-a19a0874d5f9)
