### ISSUE TITLE
Anyone tried storing trees and nodes in DynamoDB?

### ISSUE THREAD

**Issue by joshpassenger** [spotify/annoy#656]
Hey @erikbern I am looking at scaling and caching via DynamoDB and adding updates, mostly for dense vector searching to back RAG solutions, how important are the priority queue and other optimisations, unoptimised with no caching is performant in DynamoDB already for moderate tree and forest sizes. Has anyone externalised ANNOY to a Key Vector Store?

**Comment by erikbern** [comment]
Sorry Annoy doesn't have a generalizable backend for things like this
