### ISSUE TITLE
What are you using Annoy for?

### ISSUE THREAD

**Issue by erikbern** [spotify/annoy#86]
(I couldn't think of a better way than filing a ticket to ask for)

I'm planning to speak at the NYC ML meetup later this year about ANN and was curious if people are happy to share some use cases for Annoy!

**Comment by zachmayer** [comment]
Nothing yet, but link to your slides here when you're done =D

**Comment by JohnNay** [comment]
Using it for a baseline model to compare to deep learning and gradient boosting machines, we're building a system to that trains on hundreds of millions of examples of remotely sensed values of vegetation health and lagged values of other remotely sensed (NASA satellite data) variables at high spatial resolution for Sri Lanka for the past ten years to forecast future values of vegetation health in drought prone farming areas. I'm using annoy to look up pixel-time observations closest in space and time in the trianing data and use their values of vegetation health as the predictions for the holdout data to compare to the more complex models to see if they will be worth deploying.

**Comment by erikbern** [comment]
That's super cool – so some sort of k-NN classifier on satellite images?

**Comment by JohnNay** [comment]
Yeah k-NN regression on a vegetation health index measured from satellite images (http://modis.gsfc.nasa.gov/data/). Thanks for this software by the way!

**Comment by erikbern** [comment]
Curious to see how k-NN compares to deep learning (tbh I would suspect the latter is better, given enough data)

**Comment by JohnNay** [comment]
I'll share the results with you once I have them if you would like

**Comment by lenguyenthedat** [comment]
I'm going to build a recommendation engine with Annoy.
After a good amount of testing I've done myself, it turned out to be the fastest implementation of k-NN I've tried so far - that can handle a large amount of training data.

**Comment by duhaime** [comment]
This is an old thread, but I wanted to drop a quick line to say thanks for putting together this awesome library! I'm using it to study patterns in text reuse within literary history (imitations, plagiarisms, etc). I have a [simple repo](https://github.com/duhaime/visualize-text-reuse) that couples Annoy with D3 for some interactive visualizations in case you're curious. Thanks again for sharing this great work!

**Comment by shawnjhenry** [comment]
I would like to say thanks for building this, too!  I'm indexing an archive of chat messages with distributed document representations and Annoy for semantic similarity search.
