### ISSUE TITLE
small typo in the API documentation

### ISSUE THREAD

**Issue by pjiangtw** [spotify/annoy#87]
Hi there,

In the "Full Python API" section under README.rst, this method
a.get_item_vector_item(i)
should be
a.get_item_vector(i)

Best,
Pei

**Comment by erikbern** [comment]
Oops thanks. I can fix – feel free to submit a PR next time :)

**Comment by erikbern** [comment]
Fixed per 84b98a1be2848fa7bc298f7d782f5750e50bafa6
