### ISSUE TITLE
cannot import name AnnoyIndex

### ISSUE THREAD

**Issue by npes87184** [spotify/annoy#92]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/home/itri/Desktop/annoy.py in <module>()
----> 1 from annoy import AnnoyIndex
      2 import random
      3 
      4 f = 40
      5 t = AnnoyIndex(f)  # Length of item vector that will be indexed

/home/itri/Desktop/annoy.py in <module>()
----> 1 from annoy import AnnoyIndex
      2 import random
      3 
      4 f = 40
      5 t = AnnoyIndex(f)  # Length of item vector that will be indexed

ImportError: cannot import name AnnoyIndex

the log of install:
Running setup.py install for annoy
Successfully installed annoy-1.5.1

And my OS is redhat 7 

thanks~

**Comment by erikbern** [comment]
Isn't the problem that your file is annoy.py so when you do `from annoy import AnnoyIndex` you end up trying to import it from the same file not from the package? Try renaming the script to something else and run again

**Comment by npes87184** [comment]
Thanks!
I think I am sleeping that time.  LOL
