### ISSUE TITLE
Use 8-bit elements

### ISSUE THREAD

**Issue by erikbern** [spotify/annoy#94]
I bet you can quantize the vector elements to 8 bit and make the index 4x smaller – this should help with cache locality as well as fitting more trees in the same index. Will try at some point

**Comment by a1k0n** [comment]
For the angular split planes, certainly. I've always been advocating for this :)

**Comment by erikbern** [comment]
I meant for everything. It's a bit nontrivial to change just the split planes and not the item vectors and I also think the benefit is the same for both.

Why did you specifically mention the angular split planes? Should work for both right?

**Comment by a1k0n** [comment]
Well, if you start to quantize the input elements, you can no longer compute exact distances from your query to the points in the dataset; for an ANN library, I guess that's OK.

Rescaling everything from -128..127 in the angular domain is all fine with me, but I was concerned about what happens in Euclidean space. Maybe it's fine, though. A pathological dataset with a relatively huge diameter but with relatively small clusters might be badly served by that, but on second thought it's probably fine for any reasonable dataset.

**Comment by erikbern** [comment]
Yeah but it should be fine. I ran some tests on GloVe (same as the unit tests) and accuracy was hardly affected by quantizing the vectors. Might be a good option that doesn't have to be enabled by default

The bottleneck is really memory latency so to get the big benefit you need both the split planes and the vectors to be stored compactly – especially the latter since more vectors are fetched compared to split planes

Might put together something quick and benchmark

**Comment by erikbern** [comment]
Doesn't seem to work super well. For GloVe (f=25) the index size goes down from 289M -> 209M (angular) and 332M -> 259M (euclidean).

Interestingly, accuracy goes up slightly. I think it's because `_K` gets smaller so each leaf node stores more items

Unfortunately search time goes up as well, from 60s to 100s (for angular + euclidean).

I think what happens is this
* Conversion to/from 8bit is negligible and quantization has no impact on quality
* The RAM access time is mostly dominated by latency not throughput. So every random access has the same penalty no matter how big the request is
* Leaf size has some impact and most likely if you push leaf size down, you need to search more internal nodes -> higher total number of RAM requests -> slower (but marginally higher quality)

**Comment by a1k0n** [comment]
Yeah, exactly... since leaf size must be == vector size (which is sort of an odd tradeoff) your leaves are 1/4th the size. Can those be made independent? You don't *really* need them to be equivalent, but the indexing would be a bit more involved.

**Comment by erikbern** [comment]
Yeah not sure what the tradeoff is actually. Smaller leaf sizes seem better.

Another thing worth trying at some point is more than 2 child nodes per split – should improve performance too

**Comment by erikbern** [comment]
It's kind of convenient that they have the same size though. I've been thinking about adding support for incremental adds at some point and in that case it would be really useful – you can mix vectors with tree nodes all over the index.

**Comment by erikbern** [comment]
Btw will try the 8-bit thing with larger vector sizes too – might have to do something with the size of a cache line
