### ISSUE TITLE
Use LMDB for storage

### ISSUE THREAD

**Issue by erikbern** [spotify/annoy#96]
@LongbinChen pointed out that LMDB would be a good way to support a series of things.

http://symas.com/mdb/microbench/

If we swap out the storage to rely in LMDB we would get a lot of features for free
- Ability to use any key, not just integers
- Out-of-core data (dataset doesn't fit in RAM)
- Decouple index structure from nodes (could potentially set `_K` independently and optimize for it).
- Incremental add_item (and deletes) would be much easier to implement

I'm not sure how tricky this would be, but probably not more than 5-10h. Mentioning it in case someone wants to give it a shot :)

**Comment by LongbinChen** [comment]
best way to celebrate the labor day is to work. I will work on this for this weekend and hopefully come out something.

**Comment by erikbern** [comment]
Nice! Let me know if you need any help!

**Comment by erikbern** [comment]
Did you end up doing anything with this? I've been thinking more and more about this and might spend some time on it

**Comment by LongbinChen** [comment]
I added something that are not working yet. I can make a pull request and
so you can see what I have done.

and feel free to take from there.

On Wed, Sep 9, 2015 at 12:38 PM, Erik Bernhardsson <notifications@github.com

**Comment by LongbinChen** [comment]
pull request made.

**Comment by LongbinChen** [comment]
do you still have the access to spotify/annoy?

**Comment by erikbern** [comment]
Yeah I do. I think with LMDB it might be worth considering moving this somewhere else though – it's a big non-compatible change anyway

**Comment by LongbinChen** [comment]
and houzz would be happy to host the repo if you like.

**Comment by rikenmehta03** [comment]
@LongbinChen Are above mentioned support implemented or someone working on that..?

**Comment by erikbern** [comment]
not afaik
