### ISSUE TITLE
AnnoyIndex's bulk load option

### ISSUE THREAD

**Issue by lenguyenthedat** [spotify/annoy#98]
I have to load in, says 1 millions (700 dims) records from a csv file or pandas dataframe.
Is there any way to do a bulk load for AnnoyIndex instead of loading each record one by one with `add_item(i, v)`?

**Comment by erikbern** [comment]
Sorry no

**Comment by lenguyenthedat** [comment]
Thanks for clarifying!
`add_item(i,v)` turned out to be fast enough for me anyway.

**Comment by erikbern** [comment]
yeah i think it should be pretty fast in practice
