### ISSUE TITLE
Item ids must be sequential starting at zero

### ISSUE THREAD

**Issue by bgreen-litl** [spotify/annoy#99]
It was non-obvious to me that the integer ids supplied to add_item() must be sequential and start at zero. But if they are not, get_n_items() returns bogus counts. Is this the intended contract?  It seems like if the ids are simply increasing sequential integers that AnnoyIndex would manage incrementing the ids.  Why have to specify it in add_item() at all? Am I missing something?

For example, this appears to work:
    >>> t = annoy.AnnoyIndex(3)
    >>> t.add_item(0, [1, 2, 3])
    >>> t.add_item(1, [2, 2, 3])
    >>> t.add_item(2, [3, 2, 3])
    >>> t.build(1)
    True
    >>> t.get_n_items()
    3

But use arbitrary ids, and the counts are tricked:
    >>> t = annoy.AnnoyIndex(3)
    >>> t.add_item(1, [1, 2, 3])
    >>> t.build(1)
    True
    >>> t.get_n_items()
    2

Or:
    >>>
    >>> t = annoy.AnnoyIndex(3)
    >>> t.add_item(100, [1, 2, 3])
    >>> t.build(1)
    True
    >>> t.get_n_items()
    101

**Comment by erikbern** [comment]
n_items will return max(id)+1

They don't have to be sequential at all. You can add item 5 and then item 3 and then item 1. n_items will be 6 in that case.

**Comment by erikbern** [comment]
You can think of it as how a matrix works in numpy, it's just that it resizes dynamically

**Comment by erikbern** [comment]
Not saying this is perfect behavior, but it was by far the easiest thing to implement and it supports most use cases with minor extra work (sometimes a dict mapping to unique id's)
